In [11]:
import networkx as nx
import numpy as np
import pandas as pd
import networkx as nx
import seaborn as sns
import matplotlib.pyplot as plt
import csv
import ast
import re

import urllib.request as urlrequest
from collections import Counter
from goose3 import Goose
from goose3.network import NetworkError
from bertopic import BERTopic
from scipy.cluster import hierarchy as sch
from sklearn.feature_extraction.text import CountVectorizer
from urllib.parse import urlparse
from scipy.spatial.distance import pdist, squareform
import umap
from sklearn.preprocessing import MinMaxScaler
from scipy.spatial.distance import cdist
import torch

In [2]:
pd.reset_option("all")

As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead.

: boolean
    use_inf_as_null had been deprecated and will be removed in a future
    version. Use `use_inf_as_na` instead.

In [97]:
pd.set_option('expand_frame_repr', True)
pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [105]:
#d_200908 = pd.read_csv('200908.CSV',sep='\t',header=None)
#d_20140523 = pd.read_csv('20140523.export.CSV',sep='\t',header=None)
d_20140524 = pd.read_csv('20140524.export.CSV',sep='\t',header=None)
d_20140524 = [(d_20140524['Actor1Geo_CountryCode'] == 'US') | 
            (d_20140524['Actor2Geo_CountryCode'] == 'US') | 
            (d_20140524['ActionGeo_CountryCode'] == 'US')]
##elliot rodgers CA
d_20160612 = pd.read_csv('20160612.export.CSV',sep='\t',header=None)
d_20160612 = [(d_20160612['Actor1Geo_CountryCode'] == 'US') | 
            (d_20160612['Actor2Geo_CountryCode'] == 'US') | 
            (d_20160612['ActionGeo_CountryCode'] == 'US')]
##orlando night club FL
d_20170812 = pd.read_csv('20170812.export.CSV',sep='\t',header=None)
d_20170812 = [(d_20170812['Actor1Geo_CountryCode'] == 'US') | 
            (d_20170812['Actor2Geo_CountryCode'] == 'US') | 
            (d_20170812['ActionGeo_CountryCode'] == 'US')]
##charlottesville VA
d_20171031 = pd.read_csv('20171031.export.CSV',sep='\t',header=None)
d_20171031 = [(d_20171031['Actor1Geo_CountryCode'] == 'US') | 
            (d_20171031['Actor2Geo_CountryCode'] == 'US') | 
            (d_20171031['ActionGeo_CountryCode'] == 'US')]
##truck attack NY
#d_20180423 = pd.read_csv('20180423.export.CSV',sep='\t',header=None)
##TORONTO skip for now
#d_20200526 = pd.read_csv('20200526.export.CSV',sep='\t',header=None)
##george floyd MN
#d_20250101 = pd.read_csv('20250101.export.CSV',sep='\t',header=None)
##truck attack neworleans TN
d_20250602 = pd.read_csv('20250602.export.CSV',sep='\t',header=None)
d_20250602 = [(d_20250602['Actor1Geo_CountryCode'] == 'US') | 
            (d_20250602['Actor2Geo_CountryCode'] == 'US') | 
            (d_20250602['ActionGeo_CountryCode'] == 'US')]
#anti israel CO

/Users/emilylugos/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning:

Columns (8,9,11,14) have mixed types.Specify dtype option on import or set low_memory=False.

KeyError: 'Actor1Geo_CountryCode'

In [104]:
len(d_20250602)

125531

In [15]:
d_20140523_CA = pd.read_csv('d_20140524_CA.csv')
#102
#309
d_20160612_FL= pd.read_csv('d_20160612_FL.csv')
#2349
d_20170812_VA= pd.read_csv('d_20170812_VA.csv')
#1037
d_20171031_NY= pd.read_csv('d_20171031_NY.csv')
#2873 most likely half)]
##not viable
d_20250602_CO = pd.read_csv('d_20250602_CO.csv')

In [16]:
mbfcs = pd.read_csv('data/mbfc_source_data.csv')
def replace_nans(text_list, replacement=""):
    return ["" if str(x).strip().lower() == "nan" or x != x else x for x in text_list]

def target(df, mbfcs):
    df = df.drop_duplicates(subset="text", keep="first").reset_index(drop=True)
    df['factual_reporting'] = ''  # Initialize column as object type
    df['factual_reporting'] = df['factual_reporting'].astype('object')
    # Normalize mbfcs keys for matching
    mbfcs['normalized_display_name'] = mbfcs['display_name'].str.lower().str.replace(" ", "", regex=False)
    mbfcs['normalized_website'] = mbfcs['website'].apply(lambda x: urlparse(x).hostname if pd.notnull(x) else '').str.lower()

    for i in df.index:
        
        target_clean = str(df.loc[i, 'target']).lower().replace(" ", "")
        domain_clean = str(df.loc[i, 'domain']).lower().replace(" ", "")

        match = mbfcs[mbfcs['normalized_display_name'] == target_clean]
        if not match.empty:
            df.at[i, 'factual_reporting'] = match.iloc[0]['factual_reporting']
            continue

        match = mbfcs[mbfcs['normalized_website'] == domain_clean]
        if not match.empty:
            df.at[i, 'factual_reporting'] = match.iloc[0]['factual_reporting']
        else:
            df.at[i, 'factual_reporting'] = None
    df = df.dropna(axis=0, subset=['text'])
    return df


d_20171031_NY = target(d_20171031_NY, mbfcs)
d_20170812_VA = target(d_20170812_VA, mbfcs)
d_20160612_FL = target(d_20160612_FL, mbfcs)
d_20250602_CO = target(d_20250602_CO, mbfcs)
d_20140524_CA = target(d_20140523_CA, mbfcs)

result_series = set(d_20140524_CA.loc[d_20140524_CA['factual_reporting'].isnull(), 'domain']) | \
                set(d_20171031_NY.loc[d_20171031_NY['factual_reporting'].isnull(), 'domain'])| \
                set(d_20170812_VA.loc[d_20170812_VA['factual_reporting'].isnull(), 'domain'])| \
                set(d_20160612_FL.loc[d_20160612_FL['factual_reporting'].isnull(), 'domain'])| \
                set(d_20250602_CO.loc[d_20250602_CO['factual_reporting'].isnull(), 'domain'])

In [9]:
def search_keyword(df, keywords):
    if isinstance(keywords, str):
        pattern = keywords
    else:
        # Join keywords with regex OR operator
        pattern = '|'.join(map(re.escape, keywords))

    mask = df['text'].str.contains(pattern, case=False, na=False, regex=True)
    return df[mask]

In [17]:
d_20171031_NY = search_keyword(d_20171031_NY, ['truck','attack', 'injured','NYC'])

In [19]:
d_20170812_VA = search_keyword(d_20170812_VA, ['Charlottesville', 'white supremacist', 'terrorist'])
d_20160612_FL = search_keyword(d_20160612_FL, ['Orlando', 'gunman', 'Pulse', 'nightclub'])
d_20250602_CO = search_keyword(d_20250602_CO, ['Boulder', 'attack', 'Palestine', 'Israel'])
d_20140524_CA = search_keyword(d_20140523_CA, ['Isla Vista', 'Santa Barbara', 'killed', 'dead'])

In [23]:
d_20140524_CA

,GlobalEventID,date,Year,IsRootEvent,EventCode,EventBaseCode,EventRootCode,QuadClass,GoldsteinScale,NumMentions,...,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL,domain,target,title,text,description
0,298548627,20140517,2014,1,12,12,1,1,-0.4,2,...,36.17,-119.746,CA,20140524,http://www.cbsnews.com/news/elliot-rodger-cali...,www.cbsnews.com,cbsnews,Shooting spree suspect son of longtime Hollywo...,"Elliot Rodger, the suspect in Friday's deadly ...","A life of ""sadness, anger and hatred,"" accordi..."
1,298551064,20140524,2014,1,173,173,17,4,-5.0,3,...,36.17,-119.746,CA,20140524,http://news.yahoo.com/farmers-death-still-myst...,news.yahoo.com,news,"Yahoo News: Latest and Breaking News, Headline...",\n• None A tiny California city prone to tsuna...,The latest news and headlines from Yahoo News....
4,298556473,20140524,2014,1,190,190,19,4,-10.0,116,...,36.17,-119.746,CA,20140524,http://www.dw.de/california-gunman-was-hollywo...,www.dw.com,dw,US gunman 'was director's son' – DW – 05/25/2014,A Hollywood director says he believes his son ...,A Hollywood director says he believes his son ...
5,298558408,20140524,2014,0,190,190,19,4,-10.0,4,...,36.17,-119.746,CA,20140524,http://losangeles.cbslocal.com/2014/05/24/shoo...,www.cbsnews.com,cbsnews,Shooting Rampage Victim's Father Tearfully Ask...,GOLETA (AP) — A man whose son was among the vi...,Christopher Ross Michael-Martinez was the last...
6,298558433,20140524,2014,0,190,190,19,4,-10.0,4,...,36.17,-119.746,CA,20140524,http://www.theguardian.com/world/2014/may/25/e...,www.theguardian.com,theguardian,California killings: UK-born Elliot Rodger bla...,Police have named the deceased suspect in the ...,Six people and the suspect dead after Isla Vis...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,298635073,20140524,2014,0,190,190,19,4,-10.0,1,...,36.17,-119.746,CA,20140524,http://www.ibtimes.com/uc-santa-barbara-shooti...,www.ibtimes.com,ibtimes,UC Santa Barbara Shooting Update: 3 Stabbing V...,"Update 9:20 p.m. EDT: Elliot Rodger, the alleg...",The gunman allegedly began his murderous spree...
129,298635186,20140524,2014,0,10,10,1,1,0.0,20,...,36.17,-119.746,CA,20140524,http://www.odt.co.nz/news/world/303498/six-kil...,www.odt.co.nz,odt,"'Madman' killer stabs three, shoots three",A gunman described as severely mentally distur...,A gunman described as severely mentally distur...
131,298637362,20140524,2014,1,193,193,19,4,-10.0,12,...,36.17,-119.746,CA,20140524,http://www.thestar.com.my/News/World/2014/05/2...,www.thestar.com.my,thestar,Suspect in California shootings apparently kil...,(Reuters) - The suspected gunman in the Isla V...,(Reuters) - The suspected gunman in the Isla V...
132,298637364,20140524,2014,1,193,193,19,4,-10.0,6,...,36.17,-119.746,CA,20140524,http://www.reuters.com/article/2014/05/25/us-u...,web.archive.org,web,Suspect in California shootings apparently kil...,The suspected gunman drove through Isla Vista ...,NaN
133,298637367,20140524,2014,1,193,193,19,4,-10.0,2,...,36.17,-119.746,CA,20140524,http://www.reuters.com/article/2014/05/25/us-u...,web.archive.org,web,Suspect in California shootings apparently kil...,The suspected gunman drove through Isla Vista ...,NaN

In [42]:
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(l_20250602_CO)
hierarchical_topics = topic_model.hierarchical_topics(l_20250602_CO)
vectorizer_model = CountVectorizer(stop_words="english")
tm_20250602_CO = BERTopic(vectorizer_model=vectorizer_model)
tm_20250602_CO_topics, tm_20250602_CO_probs = tm_20250602_CO.fit_transform(l_20250602_CO)

  0%|          | 0/32 [00:00<?, ?it/s]/Users/emilylugos/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py:5516: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

100%|██████████| 32/32 [00:00<00:00, 337.03it/s]

In [24]:
l_20160612_FL = d_20160612_FL['text'].tolist()
l_20160612_FL = replace_nans(l_20160612_FL)
l_20250602_CO = d_20250602_CO['text'].tolist()
l_20250602_CO = replace_nans(l_20250602_CO)
l_20140524_CA = d_20140524_CA['text'].tolist()
l_20140524_CA = replace_nans(l_20140524_CA)
l_20171031_NY = d_20171031_NY['text'].tolist()
l_20171031_NY = replace_nans(l_20171031_NY)
l_20170812_VA = d_20170812_VA['text'].tolist()
l_20170812_VA = replace_nans(l_20170812_VA)

In [36]:
# Define custom vectorizer to remove stop words
vectorizer_model = CountVectorizer(stop_words="english")
# Initialize BERTopic with custom vectorizer
tm_20250602_CO = BERTopic(vectorizer_model=vectorizer_model, min_topic_size=5)
# Fit the model on your documents
tm_20250602_CO_topics, tm_20250602_CO_probs = tm_20250602_CO.fit_transform(l_20250602_CO)
# Use the same model instance to generate hierarchical topics
tm_20250602_CO_htopics = tm_20250602_CO.hierarchical_topics(l_20250602_CO)

# Initialize BERTopic with custom vectorizer
tm_20160612_FL = BERTopic(vectorizer_model=vectorizer_model,min_topic_size=5)
# Fit the model on your documents
tm_20160612_FL_topics, tm_20160612_FL_probs = tm_20160612_FL.fit_transform(l_20160612_FL)
# Use the same model instance to generate hierarchical topics
tm_20160612_FL_htopics = tm_20160612_FL.hierarchical_topics(l_20160612_FL)

# Initialize BERTopic with custom vectorizer
tm_20140524_CA = BERTopic(vectorizer_model=vectorizer_model,min_topic_size=5)
# Fit the model on your documents
tm_20140524_CA_topics, tm_20140524_CA_probs = tm_20140524_CA.fit_transform(l_20140524_CA)
# Use the same model instance to generate hierarchical topics
tm_20140524_CA_htopics = tm_20140524_CA.hierarchical_topics(l_20140524_CA)

# Initialize BERTopic with custom vectorizer
tm_20171031_NY = BERTopic(vectorizer_model=vectorizer_model,min_topic_size=5)
# Fit the model on your documents
tm_20171031_NY_topics, tm_20171031_NY_probs = tm_20171031_NY.fit_transform(l_20171031_NY)
# Use the same model instance to generate hierarchical topics
tm_20171031_NY_htopics = tm_20171031_NY.hierarchical_topics(l_20171031_NY)

# Initialize BERTopic with custom vectorizer
tm_20170812_VA = BERTopic(vectorizer_model=vectorizer_model,min_topic_size=5)
# Fit the model on your documents
tm_20170812_VA_topics, tm_20170812_VA_probs = tm_20170812_VA.fit_transform(l_20170812_VA)
# Use the same model instance to generate hierarchical topics
tm_20170812_VA_htopics = tm_20170812_VA.hierarchical_topics(l_20170812_VA)

100%|██████████| 13/13 [00:00<00:00, 362.24it/s]
100%|██████████| 11/11 [00:00<00:00, 331.32it/s]
100%|██████████| 2/2 [00:00<00:00, 380.23it/s]
100%|██████████| 1/1 [00:00<00:00, 237.48it/s]
100%|██████████| 7/7 [00:00<00:00, 413.83it/s]

In [41]:
tm_20160612_FL.visualize_topics()

In [55]:
tm_20140524_CA_info = tm_20140524_CA.get_topic_info()
# Example: distance between topic 0 and topic 1
tm_20140524_CA_coordinates = tm_20140524_CA.topic_embeddings_  # shape: (n_topics, 2)
# Step 2: Compute the pairwise Euclidean distances
tm_20140524_CA_matrix = squareform(pdist(tm_20140524_CA_coordinates, metric='euclidean'))
# Step 3: Create topic labels
tm_20140524_CA_labels = [f"Topic {i}" for i in range(-1,len(tm_20140524_CA_coordinates)-1)]
# Step 4: Create a DataFrame for better formatting
tm_20140524_CA_dist_df = pd.DataFrame(tm_20140524_CA_matrix, index=tm_20140524_CA_labels, columns=tm_20140524_CA_labels)
# Step 5: Print the full matrix

tm_20250602_CO_info = tm_20250602_CO.get_topic_info()
# Example: distance between topic 0 and topic 1
tm_20250602_CO_coordinates = tm_20250602_CO.topic_embeddings_  # shape: (n_topics, 2)
# Step 2: Compute the pairwise Euclidean distances
tm_20250602_CO_matrix = squareform(pdist(tm_20250602_CO_coordinates, metric='euclidean'))
# Step 3: Create topic labels
tm_20250602_CO_labels = [f"Topic {i}" for i in range(-1,len(tm_20250602_CO_coordinates)-1)]
# Step 4: Create a DataFrame for better formatting
tm_20250602_CO_dist_df = pd.DataFrame(tm_20250602_CO_matrix, index=tm_20250602_CO_labels, columns=tm_20250602_CO_labels)

tm_20160612_FL_info = tm_20160612_FL.get_topic_info()
# Example: distance between topic 0 and topic 1
tm_20160612_FL_coordinates = tm_20160612_FL.topic_embeddings_  # shape: (n_topics, 2)
# Step 2: Compute the pairwise Euclidean distances
tm_20160612_FL_matrix = squareform(pdist(tm_20160612_FL_coordinates, metric='euclidean'))
# Step 3: Create topic labels
tm_20160612_FL_labels = [f"Topic {i}" for i in range(-1,len(tm_20160612_FL_coordinates)-1)]
# Step 4: Create a DataFrame for better formatting
tm_20160612_FL_dist_df = pd.DataFrame(tm_20160612_FL_matrix, index=tm_20160612_FL_labels, columns=tm_20160612_FL_labels)

tm_20171031_NY_info = tm_20171031_NY.get_topic_info()
# Example: distance between topic 0 and topic 1
tm_20171031_NY_coordinates = tm_20171031_NY.topic_embeddings_  # shape: (n_topics, 2)
# Step 2: Compute the pairwise Euclidean distances
tm_20171031_NY_matrix = squareform(pdist(tm_20171031_NY_coordinates, metric='euclidean'))
# Step 3: Create topic labels
tm_20171031_NY_labels = [f"Topic {i}" for i in range(-1,len(tm_20171031_NY_coordinates)-1)]
# Step 4: Create a DataFrame for better formatting
tm_20171031_NY_dist_df = pd.DataFrame(tm_20171031_NY_matrix, index=tm_20171031_NY_labels, columns=tm_20171031_NY_labels)

tm_20170812_VA_info = tm_20170812_VA.get_topic_info()
# Example: distance between topic 0 and topic 1
tm_20170812_VA_coordinates = tm_20170812_VA.topic_embeddings_  # shape: (n_topics, 2)
# Step 2: Compute the pairwise Euclidean distances
tm_20170812_VA_matrix = squareform(pdist(tm_20170812_VA_coordinates, metric='euclidean'))
# Step 3: Create topic labels
tm_20170812_VA_labels = [f"Topic {i}" for i in range(-1,len(tm_20170812_VA_coordinates)-1)]
# Step 4: Create a DataFrame for better formatting
tm_20170812_VA_dist_df = pd.DataFrame(tm_20170812_VA_matrix, index=tm_20170812_VA_labels, columns=tm_20170812_VA_labels)

In [81]:
tm_20250602_CO_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,19,-1_measles_attack_colorado_said,"[measles, attack, colorado, said, terror, heal...","[(EL PASO COUNTY, Colo.) — A third case of mea..."
1,0,299,0_said_attack_boulder_people,"[said, attack, boulder, people, colorado, soli...","[Here's what we know about the Boulder, Colora..."
2,1,20,1_said_attack_people_police,"[said, attack, people, police, suspect, man, c...",[Multiple people have been injured after a man...

In [58]:
def make_matrix(topics):
    ctfidf = topics.c_tf_idf_.toarray()
    topic_indices = list(topics.topic_labels_.keys())
    vectors = ctfidf[topic_indices]
    umap_model = umap.UMAP(n_neighbors=2, n_components=2, metric="hellinger", random_state=42)
    scaler = MinMaxScaler()
    scaled = scaler.fit_transform(vectors)
    coords = umap_model.fit_transform(scaled)

    distance_matrix = pd.DataFrame(cdist(coords, coords), 
                                index=[f"Topic {i}" for i in range(len(coords))], 
                                columns=[f"Topic {i}" for i in range(len(coords))])

    return coords, distance_matrix

In [ ]:
def merge_topics_by_global_std_indices(distance_df, threshold_std=2):
    # Convert to numpy matrix
    mat = distance_df.values

    # Get all off-diagonal upper triangle values
    off_diag = mat[np.triu_indices_from(mat, k=1)]

    # Compute global avg and std
    avg = np.mean(off_diag)
    std = np.std(off_diag)
    cutoff = avg - threshold_std * std

    print(f"Global avg: {avg:.4f}, std: {std:.4f}, cutoff: {cutoff:.4f}")

    visited = set()
    clusters = []

    for i, topic in enumerate(distance_df.index):
        if topic in visited:
            continue

        # Find indices of topics whose distance is below cutoff
        distances = distance_df.loc[topic]
        close_topics = distances[distances < cutoff].index.tolist()

        group = sorted(set([topic] + close_topics))
        if len(group) > 1:
            clusters.append([int(t.split()[-1]) if isinstance(t, str) and t.startswith("Topic") else int(t) for t in group])
            visited.update(group)

    return clusters

,Topic -1,Topic 0,Topic 1,Topic 2,Topic 3,Topic 4,Topic 5,Topic 6,Topic 7,Topic 8
Topic -1,0.000000,0.345867,0.341206,0.442518,0.394791,0.397361,0.334337,0.438061,0.419597,0.451457
Topic 0,0.345867,0.000000,0.388915,0.575340,0.578752,0.318539,0.382416,0.426482,0.476313,0.534394
Topic 1,0.341206,0.388915,0.000000,0.469867,0.627966,0.407570,0.414932,0.366104,0.393167,0.364978
Topic 2,0.442518,0.575340,0.469867,0.000000,0.545093,0.589646,0.564892,0.667869,0.521785,0.468920
Topic 3,0.394791,0.578752,0.627966,0.545093,0.000000,0.635632,0.578596,0.712966,0.671969,0.605619
Topic 4,0.397361,0.318539,0.407570,0.589646,0.635632,0.000000,0.369610,0.440093,0.483332,0.554323
Topic 5,0.334337,0.382416,0.414932,0.564892,0.578596,0.369610,0.000000,0.504825,0.432117,0.600019
Topic 6,0.438061,0.426482,0.366104,0.667869,0.712966,0.440093,0.504825,0.000000,0.535850,0.564876
Topic 7,0.419597,0.476313,0.393167,0.521785,0.671969,0.483332,0.432117,0.535850,0.000000,0.525083
Topic 8,0.451457,0.534394,0.364978,0.468920,0.605619,0.554323,0.600019,0.564876,0.525083,0.000000

In [ ]:
def calc_avg_per_column(df):
    # Extract the upper triangle of the matrix without the diagonal
    upper_triangle_values = df.where(np.triu(np.ones(df.shape), k=1).astype(bool)).stack()

    df_no_diag = df.mask(np.eye(len(df), dtype=bool))

    # Calculate inter-topic average for each column (excluding diagonal)
    intertopic_avg_per_column = df_no_diag.mean(axis=0)
    intertopic_std_per_column = df_no_diag.std(axis=0)
    print(f"avg:{intertopic_avg_per_column} stdev: {intertopic_std_per_column}")

    within_stdev = {}
    for topic, avg in intertopic_avg_per_column.items():
        std = intertopic_std_per_column[topic]
        lower = avg - std
        upper = avg + std
        similar_topics = intertopic_avg_per_column[(intertopic_avg_per_column <= lower)].index.tolist()
        print('topic:',topic,'similar:', similar_topics)
        #similar_topics.remove(topic)  # exclude self
        within_stdev[topic] = similar_topics

    return within_stdev

In [71]:
def merge_topics_by_global_std_indices(distance_df, threshold_std=3):
    # Convert to numpy matrix
    mat = distance_df.values

    # Get all off-diagonal upper triangle values
    off_diag = mat[np.triu_indices_from(mat, k=1)]

    # Compute global avg and std
    avg = np.mean(off_diag)
    std = np.std(off_diag)
    cutoff = avg - threshold_std * std

    print(f"Global avg: {avg:.4f}, std: {std:.4f}, cutoff: {cutoff:.4f}")

    visited = set()
    clusters = []

    for i, topic in enumerate(distance_df.index):
        if topic in visited:
            continue

        # Find indices of topics whose distance is below cutoff
        distances = distance_df.loc[topic]
        close_topics = distances[distances < cutoff].index.tolist()

        group = sorted(set([topic] + close_topics))
        if len(group) > 1:
            clusters.append([int(t.split()[-1]) if isinstance(t, str) and t.startswith("Topic") else int(t) for t in group])
            visited.update(group)

    return clusters

In [72]:
avg_CA = merge_topics_by_global_std_indices(tm_20140524_CA_dist_df)
#avg_20160612_FL = calc_avg(tm_20160612_FL_dist_df)
#avg_20171031_NY = calc_avg(tm_20171031_NY_dist_df)
#avg_20170812_VA = calc_avg(tm_20170812_VA_dist_df)

Global avg: 0.6204, std: 0.0919, cutoff: 0.3447

In [10]:
coords, w_202506202_CO = make_matrix(tm_20250602_CO)

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("facebook/roberta-hate-speech-dynabench-r4-target")
model = AutoModelForSequenceClassification.from_pretrained("facebook/roberta-hate-speech-dynabench-r4-target")

In [37]:
l_20140524_CA.to_csv('l_20140524_CA.csv',index=False)
l_20250602_CO.to_csv('l_20250602_CO.csv', index=False)
l_20160612_FL.to_csv('l_20160612_FL.csv',index=False)
l_20170812_VA.to_csv('l_20170812_VA.csv',index=False)
l_20171031_NY.to_csv('l_20171031_NY.csv', index=False)

AttributeError: 'list' object has no attribute 'to_csv'

In [39]:
# Specify the filename for your CSV
filename = 'l_20140524_CA.csv'

# Open the CSV file in write mode ('w') with newline=''
# newline='' is crucial to prevent extra blank rows in the CSV
with open(filename, 'w', newline='') as csvfile:
    # Create a csv.writer object
    csv_writer = csv.writer(csvfile)

    # Write all rows at once using writerows()
    csv_writer.writerows(l_20140524_CA)

In [82]:
df = pd.DataFrame({"text": l_20140524_CA})
df.to_csv("l_20140524_CA.csv", index=False)
df = pd.DataFrame({"text": l_20250602_CO})
df.to_csv("l_20250602_CO.csv", index=False)
df = pd.DataFrame({"text": l_20160612_FL})
df.to_csv("l_20160612_FL.csv", index=False)
df = pd.DataFrame({"text": l_20170812_VA})
df.to_csv("l_20170812_VA.csv", index=False)
df = pd.DataFrame({"text": l_20171031_NY})
df.to_csv("l_20171031_NY.csv", index=False)

In [38]:
hatebert_CO = pd.read_csv('hatebert_CO.csv')
hatebert_CA = pd.read_csv('hatebert_CA.csv')
hatebert_FL = pd.read_csv('hatebert_FL.csv')
hatebert_NY = pd.read_csv('hatebert_NY.csv')
hatebert_VA = pd.read_csv('hatebert_VA.csv')

In [108]:
fb_CO = pd.read_csv('fb_CO_08042025.csv')
fb_CA = pd.read_csv('fb_CA_08042025.csv')
fb_FL = pd.read_csv('fb_FL_08042025.csv')
fb_NY = pd.read_csv('fb_NY_08042025.csv')
fb_VA = pd.read_csv('fb_NY_08042025.csv')
twitter_CO = pd.read_csv('twitter_CO_08042025.csv')
twitter_CA = pd.read_csv('twitter_CA_08042025.csv')
twitter_FL = pd.read_csv('twitterhate_FL_08042025.csv')
twitter_NY = pd.read_csv('twitter_NY_08042025.csv')
twitter_VA = pd.read_csv('twitterhate_VA_08042025.csv')

hateexplain_CO = pd.read_csv('hateexplain_CO_08042025.csv')
hateexplain_CA = pd.read_csv('hatexplain_CA_08042025.csv')
hateexplain_FL = pd.read_csv('hateexplain_FL_08042025.csv')
hateexplain_NY = pd.read_csv('hateexplain_NY_08042024.csv')
hateexplain_VA = pd.read_csv('hatexplain_VA_08042025.csv')

In [109]:
def sort_ratio(df):
    # Ensure class_ratio column is a dictionary
    df = df.drop_duplicates(subset="text", keep="first").reset_index(drop=True)

    df["class_ratio"] = df["class_ratio"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

    # Find the highest class ID present in any row
    max_class = max(
        (max(ratio.keys()) for ratio in df["class_ratio"] if isinstance(ratio, dict) and ratio),
        default=0
    )

    # Create a new column for that max class's ratio
    df["max_class_ratio"] = df["class_ratio"].apply(lambda r: r.get(max_class, 0.0))

    # Sort by that column descending
    df_sorted = df.sort_values(by="max_class_ratio", ascending=False)

    return df_sorted

In [111]:

hateexplain_CA = sort_ratio(hateexplain_CA)
hateexplain_CO = sort_ratio(hateexplain_CO) 
hateexplain_FL = sort_ratio(hateexplain_FL)
hateexplain_NY = sort_ratio(hateexplain_NY)
hateexplain_VA = sort_ratio(hateexplain_VA)
twitter_CO = sort_ratio(twitter_CO)
twitter_CA = sort_ratio(twitter_CA) 
twitter_FL = sort_ratio(twitter_FL)
twitter_NY = sort_ratio(twitter_NY)
twitter_VA = sort_ratio(twitter_VA)
fb_CO = sort_ratio(fb_CO)
fb_CA = sort_ratio(fb_CA) 
fb_FL = sort_ratio(fb_FL)
fb_NY = sort_ratio(fb_NY)
fb_VA = sort_ratio(fb_VA)

In [152]:
above = twitter_CA[twitter_CA['max_class_ratio'] > 0.0]

In [153]:
above

,text,predicted_class,class_ratio,max_class_ratio
67,LOS ANGELES — A drive-by shooter went on a “ma...,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.95, 1: 0.05}",0.050
61,The gunman who killed six people when he opene...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.966, 1: 0.034}",0.034
44,The son of a Hollywood film director has been ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...","{0: 0.966, 1: 0.034}",0.034
48,SANTA BARBARA — The gunman who killed six peop...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.968, 1: 0.032}",0.032
5,The parents of British-born Elliot Rodger desp...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.983, 1: 0.017}",0.017

In [68]:
def pair_closest_topics(df):
    mat = df.values

    # Get all off-diagonal upper triangle values
    off_diag = mat[np.triu_indices_from(mat, k=1)]
    avg = np.mean(off_diag)
    std = np.std(off_diag)  
# Drop column and row labeled 'Topic -1' if it exists
    if 'Topic -1' in df.columns:
        df = df.drop(columns='Topic -1', errors='ignore')
    if 'Topic -1' in df.index:
        df = df.drop(index='Topic -1', errors='ignore')

    pairs = {}
    for topic in df.columns:
        distances = df[topic].copy()
        distances[topic] = np.inf  # Ignore self-distance
        closest_topic = distances.idxmin()
        pairs[topic] = closest_topic
    return pairs, avg,std

# Get closest topic pairs
closest_pairs,avg,std = pair_closest_topics(tm_20160612_FL_dist_df)
closest_pairs_df = pd.DataFrame(list(closest_pairs.items()), columns=["Topic", "Closest_Topic"])

In [118]:
above

,text,predicted_class,class_ratio,max_class_ratio
225,"Mara Gay: Mamdani has done something special, ...",[1],{1: 1.0},1.000
183,"On second thought, it was depressing to think ...","[0, 0, 1]","{0: 0.667, 1: 0.333}",0.333
96,"The last two pro-Hamas terrorist attacks, the ...","[1, 0, 0, 0, 0, 0, 1, 0]","{1: 0.25, 0: 0.75}",0.250
326,The Defense Department (DOD) is starting a vol...,"[0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]","{0: 0.833, 1: 0.167}",0.167
267,"Yesterday’s violent attack in Boulder, Colorad...","[0, 0, 0, 0, 0, 0, 0, 1]","{0: 0.875, 1: 0.125}",0.125
95,[Want even more content from FPM? Sign up for ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","{0: 0.917, 1: 0.083}",0.083
285,SAN DIEGO (SDJW) — More reactions to the fiery...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","{0: 0.933, 1: 0.067}",0.067
194,A second terrorist attack aimed at Jews and pr...,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","{1: 0.062, 0: 0.938}",0.062
141,HEGSETH: CHINA THREAT ‘COULD BE IMMINENT’: In ...,"[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, ...","{0: 0.94, 1: 0.06}",0.060
25,Colorado police responded to a terror attack a...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...","{0: 0.941, 1: 0.059}",0.059
280,The Department of Justice today announced fede...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","{0: 0.941, 1: 0.059}",0.059
320,The man accused of attacking an event organize...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.944, 1: 0.056}",0.056
296,The morning after an attack on a group of peop...,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.947, 1: 0.053}",0.053
192,EXCLUSIVE: One of four Jewish Republicans serv...,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.947, 1: 0.053}",0.053
290,Colorado Attorney General Phil Weiser said one...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.952, 1: 0.048}",0.048
196,"BOULDER, Colorado — Eight people were injured ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","{0: 0.955, 1: 0.045}",0.045
266,Alex Thompson tried to explain away left-wing ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.974, 1: 0.026}",0.026
29,Blumhouse's The Black Phone became an unexpect...,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.974, 1: 0.026}",0.026
288,Colorado firebomb attack was year in the makin...,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...","{0: 0.976, 1: 0.024}",0.024
104,The home of an illegal alien suspected of comm...,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","{0: 0.979, 1: 0.021}",0.021

In [90]:
def pair_closest_topics_filtered(df):
    # Drop column and row labeled 'Topic -1' if it exists
    if 'Topic -1' in df.columns:
        df = df.drop(columns='Topic -1', errors='ignore')
    if 'Topic -1' in df.index:
        df = df.drop(index='Topic -1', errors='ignore')

    # Compute overall average and standard deviation of off-diagonal values
    mat = df.values
    off_diag = mat[np.triu_indices_from(mat, k=1)]
    avg = np.mean(off_diag)
    std = np.std(off_diag)
    cutoff = avg - std

    # Pair topics only if their closest distance is below the cutoff
    pairs = {}
    for topic in df.columns:
        distances = df[topic].copy()
        distances[topic] = np.inf  # Ignore self-distance
        min_value = distances.min()
        closest_topic = distances.idxmin()
        pairs[topic] = closest_topic if min_value < cutoff else None

    return pairs, avg, std

# Apply the updated function
filtered_pairs, global_avg, global_std = pair_closest_topics_filtered(tm_20250602_CO_dist_df)
filtered_pairs_df = pd.DataFrame(list(filtered_pairs.items()), columns=["Topic", "Closest_Topic"])

In [91]:
filtered_pairs, global_avg, global_std

({'Topic 0': None, 'Topic 1': None}, 0.41105899306080335, 0.0)

In [89]:
tm_20171031_NY.visualize_topics()

In [93]:
tm_20171031_NY_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,162,-1_new_said_percent_people,"[new, said, percent, people, york, say, time, ...",[Investigators worked through the night to det...
1,0,96,0_manafort_trump_campaign_russian,"[manafort, trump, campaign, russian, papadopou...",[This is an archived article and the informati...
2,1,67,1_said_truck_police_people,"[said, truck, police, people, path, york, atta...","[NEW YORK, United States — A man in a rented p..."
3,2,52,2_police_mcgowan_said_warrant,"[police, mcgowan, said, warrant, sexual, new, ...","[Actress Rose McGowan, who has emerged as a pr..."
4,3,39,3_israel_said_puerto_new,"[israel, said, puerto, new, nuclear, president...",[Did you know that Truthout is a nonprofit and...
5,4,35,4_attack_saipov_said_police,"[attack, saipov, said, police, new, truck, peo...",[\n• None At least eight dead and a dozen inju...
6,5,34,5_irish_halloween_new_crows,"[irish, halloween, new, crows, french, america...","[Why, after decades of commercial and cultural..."
7,6,32,6_spacey_rapp_kevin_actor,"[spacey, rapp, kevin, actor, gay, cards, sexua...",[The House of Cards actor had been due to be a...
8,7,28,7_weinstein_sexual_women_allegations,"[weinstein, sexual, women, allegations, harass...",[Police in the United Kingdom have widened the...
9,8,28,8_30_september_ended_2017,"[30, september, ended, 2017, million, quarter,...",[A sprint between two tech companies to provid...
10,9,24,9_building_said_city_new,"[building, said, city, new, sanders, blasio, m...","[Sanders, a Brooklyn native who favors higher ..."
11,10,23,10_tax_state_taxes_deduction,"[tax, state, taxes, deduction, republicans, co...",[WASHINGTON (Reuters) - U.S. Republicans on Tu...
12,11,22,11_ads_facebook_ad_google,"[ads, facebook, ad, google, russian, twitter, ...",[WASHINGTON (AP) — As revelations emerged that...
13,12,22,12_military_united_justice_states,"[military, united, justice, states, war, force...",[U.S. President Donald Trump said overnight th...
14,13,19,13_crow_gerwig_like_corvis,"[crow, gerwig, like, corvis, draven, cuevo, st...",[NEW YORK (AP) — A mural of Run-DMC's Jam Mast...
15,14,17,14_new_york_attack_said,"[new, york, attack, said, people, police, city...",[At least eight people were killed and 11 othe...
16,15,16,15_journalism_greenhouse_journalist_millennials,"[journalism, greenhouse, journalist, millennia...",[Former New York Times reporter Linda Greenhou...
17,16,13,16_economics_aea_wu_reich,"[economics, aea, wu, reich, berkeley, ejmr, re...",[Any person with disabilities who needs help a...
18,17,12,17_rathburn_body_parts_brokers,"[rathburn, body, parts, brokers, records, poe,...",[The Danish inventor who’s been charged with m...