In [28]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
#from cuml.feature_extraction.text import TfidfVectorizer
import numpy as np

In [29]:
from collections import Counter

In [4]:
import spacy
nlp = spacy.load("en_core_web_lg")

/home/jupyter/miniconda3/envs/jupyter-lab/lib/python3.12/site-packages/torch/cuda/__init__.py:716: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")

In [30]:
input_file = "/data/elugos/event_embedding/train_20251216162745.csv"


df = pd.read_csv(input_file)

df.columns

/tmp/ipykernel_3082198/3586366695.py:4: DtypeWarning: Columns (40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

Index(['index', 'GlobalEventID', 'date', 'Year', 'Actor1Code', 'Actor1Name',
       'Actor1CountryCode', 'Actor1EthnicCode', 'Actor2Code', 'Actor2Name',
       'Actor2CountryCode', 'Actor2EthnicCode', 'IsRootEvent', 'EventCode',
       'EventBaseCode', 'EventRootCode', 'QuadClass', 'GoldsteinScale',
       'NumMentions', 'NumSources', 'NumArticles', 'AvgTone',
       'Actor1Geo_CountryCode', 'Actor2Geo_CountryCode', 'ActionGeo_Type',
       'ActionGeo_Fullname', 'ActionGeo_CountryCode', 'ActionGeo_ADM1Code',
       'ActionGeo_Lat', 'ActionGeo_Long', 'ActionGeo_FeatureID', 'DATEADDED',
       'SOURCEURL', 'domain', 'target', 'title', 'text', 'description',
       'sbert_text_title', 'embedding_json_title', 'sbert_text',
       'embedding_json', 'first_para', 'first_para_emb', 'PloverCode',
       'EventLabel'],
      dtype='object')

In [31]:
drop_file = "/data/elugos/event_embedding/train_202512161628_drop_dupe_titles.csv"

df_drop = pd.read_csv(drop_file)

/tmp/ipykernel_3082198/1228214834.py:3: DtypeWarning: Columns (40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df_drop = pd.read_csv(drop_file)

In [6]:
tfidf = TfidfVectorizer(
    dtype=np.float32,
    stop_words='english',
    max_df=0.7,
    max_features=50
)
#x_tfidf = tfidf.fit_transform(df['title']).toarray().get()

In [32]:
#all catergories
dfs = {k: v for k, v in df.groupby("EventLabel")}

In [33]:
dfs_drop = {k: v for k, v in df_drop.groupby("EventLabel")}

In [34]:
for i in dfs_drop:
    print(i)

AGREE
AID
ASSAULT
COERCE
CONCEDE
CONSULT
COOPERATE
DEMAND
DISAPPROVE
MOBILIZE
PROTEST
REJECT
RETREAT
SANCTION
SUPPORT
THREATHEN

In [35]:
def add_top_words_per_group(dfs, text_col="text", top_k=5):
    out = {}

    for key, sub_df in dfs.items():
        sub_df = sub_df.copy()

        # Handle empty or all-null text safely
        texts = sub_df[text_col].fillna("").astype(str)

        tfidf = TfidfVectorizer(
            dtype=np.float32,
            stop_words="english",
            max_df=0.7,
            max_features=50
        )

        X = tfidf.fit_transform(texts)
        feature_names = np.array(tfidf.get_feature_names_out())

        # Extract top words per row
        top_words = []
        for row in X:
            if row.nnz == 0:
                top_words.append([])
            else:
                indices = row.toarray().ravel().argsort()[-top_k:][::-1]
                top_words.append(feature_names[indices].tolist())

        sub_df["top_words"] = top_words
        out[key] = sub_df

    return out

In [36]:
dfs_with_tfidf = add_top_words_per_group(dfs,top_k=20)

In [42]:
dfs_with_tfidf['AID']

,index,GlobalEventID,date,Year,Actor1Code,Actor1Name,Actor1CountryCode,Actor1EthnicCode,Actor2Code,Actor2Name,...,description,sbert_text_title,embedding_json_title,sbert_text,embedding_json,first_para,first_para_emb,PloverCode,EventLabel,top_words
12,16,1200205786,20240925,2024,USA,FLORIDA,USA,NaN,NaN,NaN,...,Tropical Storm Helene's trajectory threatens t...,"Tropical Storm Helene threatens the U.S., Mexico","[0.007524872664362192, 0.10208725184202194, 0....",NaN,NaN,Tropical storm and hurricane watches were issu...,"[0.008987472392618656, 0.0025142861995846033, ...",AID,AID,"[florida, water, told, national, just, state, ..."
83,107,1200222653,20240925,2024,USA,FLORIDA,USA,NaN,USAGOV,UNITED STATES,...,Ron DeSantis’ administration is funding ads de...,DeSantis Spends Taxpayer Money to Warn About '...,"[0.04595786705613136, 0.09839852899312973, -0....",NaN,NaN,Conservative Florida Gov. Ron DeSantis is pull...,"[-0.003946694079786539, 0.0418684221804142, -0...",AID,AID,"[florida, health, state, says, department, pub..."
84,108,1200222707,20240925,2024,USAMED,FLORIDA,USA,NaN,GOV,ADMINISTRATION,...,Ron DeSantis’ administration is funding ads de...,DeSantis Spends Taxpayer Money to Warn About '...,"[0.04595786705613136, 0.09839852899312973, -0....",NaN,NaN,Conservative Florida Gov. Ron DeSantis is pull...,"[-0.003946694079786539, 0.0418684221804142, -0...",AID,AID,"[florida, health, state, says, department, pub..."
110,155,1200236068,20240925,2024,USAGOV,NASA,USA,NaN,NaN,NaN,...,NASA-SpaceX Crew 9 mission has now been schedu...,"NASA, SpaceX delay Crew-9 mission tasked to br...","[-0.04266781359910965, 0.01877169869840145, 0....",NaN,NaN,"NASA’s SpaceX Crew-9 mission, which has been t...","[-0.036593664437532425, -0.057864680886268616,...",AID,AID,"[florida, said, program, day, help, just, time..."
112,157,1200236082,20240925,2024,USAGOV,NASA,USA,NaN,USA,UNITED STATES,...,NASA-SpaceX Crew 9 mission has now been schedu...,"NASA, SpaceX delay Crew-9 mission tasked to br...","[-0.04266781359910965, 0.01877169869840145, 0....",NaN,NaN,"NASA’s SpaceX Crew-9 mission, which has been t...","[-0.036593664437532425, -0.057864680886268616,...",AID,AID,"[florida, said, program, day, help, just, time..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89856,122790,679642700,20170808,2017,USA,VIRGINIA,USA,NaN,NaN,NaN,...,"Avizia, a leading provider of system-wide tele...",Avizia to expand healthcare IT operation in Fa...,"[0.062479496002197266, 0.04440399631857872, -0...",NaN,NaN,"Avizia, a leading provider of system-wide tele...","[0.043314699083566666, -0.05537300184369087, -...",AID,AID,"[county, company, new, said, like, health, wor..."
89858,122792,679642839,20170808,2017,USA,UNITED STATES,USA,NaN,EDU,STUDENT,...,Kelly Shushok creates an environment for self-...,Interfaith consultant analyzes spiritual cultu...,"[0.03528764471411705, 0.03554699942469597, -0....",NaN,NaN,Shushok’s commitment to the Blacksburg communi...,"[-0.02673555538058281, 0.03598686307668686, -0...",AID,AID,"[people, work, said, help, years, united, comm..."
89870,122805,679647647,20170808,2017,USA,UNITED STATES,USA,NaN,NaN,NaN,...,NaN,Business & Practice,"[0.012175978161394596, 0.03666186332702637, -0...",NaN,NaN,I’ve taken both personal delight and dismay at...,"[-0.06365057826042175, 0.045531973242759705, 0...",AID,AID,"[million, world, government, public, including..."
89871,122806,679647649,20170808,2017,USA,CALIFORNIA,USA,NaN,NaN,NaN,...,This is just insane… it’s national suicide if ...,Left Claiming 'Apartheid' If Non-citizens Are ...,"[0.007430342957377434, 0.07771247625350952, -0...",NaN,NaN,Left Claiming ‘Apartheid’ If Non-citizens Are ...,"[0.0047860643826425076, 0.07197187840938568, -...",AID,AID,"[california, law, state, federal, american, go..."
89931,122889,679695391,20170808,2017,USA,UNITED STATES,USA,NaN,BUS,COMPANY,...,"Draftco Inc., a machine and fabrication shop, ...","Draftco Inc. to invest $450,000, create 16 new...","[-0.013736411929130554, -0.023327047005295753,...",NaN,NaN,"Draftco Inc., a machine and fabrication shop, ...","[-0.03974677994847298, 0.006161803845316172, -...",AID,AID,"[county, company, new, support, said, work, 00..."

In [75]:
drops_w_tfidf = add_top_words_per_group(dfs_drop,top_k=20)

In [41]:
drops_w_tfidf['AID']

NameError: name 'drops_w_tfidf' is not defined

In [38]:
from collections import Counter

word_counts = {}

for key, sub_df in dfs_with_tfidf.items():
    counter = Counter()

    for words in sub_df["top_words"]:
        counter.update(words)   # words is a list

    word_counts[key] = dict(counter.most_common())

In [39]:
drop_word_counts = {}

for key, sub_df in drops_w_tfidf.items():
    counter = Counter()

    for words in sub_df["top_words"]:
        counter.update(words)   # words is a list

    drop_word_counts[key] = dict(counter.most_common())

NameError: name 'drops_w_tfidf' is not defined

In [40]:
for k,v in word_counts.items():
    print(k,v)

AGREE {'said': 5634, 'york': 4964, 'years': 4881, 'says': 4869, 'year': 4577, 'work': 4194, 'world': 4083, 'way': 4002, 'new': 3966, 'white': 3912, 'trump': 3856, 'told': 3852, 'time': 3795, 'school': 3765, 'united': 3575, 'state': 3111, 'support': 2618, 'people': 2599, 'think': 2508, 'states': 2421, 'president': 2201, 'like': 2070, 'just': 1978, 'including': 1725, 'according': 1626, 'city': 1614, 'day': 1592, 'make': 1582, 'right': 1557, 'news': 1502, 'help': 1492, 'public': 1446, 'going': 1440, '000': 1430, 'did': 1411, 'know': 1364, 'american': 1288, 'don': 1256, 'national': 1231, 'law': 1218, 'department': 1186, 'house': 1169, 'million': 1163, 'government': 1136, 'company': 1030, 'florida': 1000, 'california': 994, 'police': 889, 'court': 855, 'attack': 753}
AID {'public': 3392, 'right': 3342, 'said': 3336, 'york': 3312, 'years': 3184, 'year': 3069, 'work': 2729, 'time': 2622, 'new': 2579, 'world': 2547, 'united': 2536, 'trump': 2485, 'water': 2323, 'state': 2318, 'told': 2308, 'support': 2099, 'people': 2039, 'states': 1896, 'says': 1604, 'president': 1519, 'just': 1427, 'like': 1426, 'including': 1391, 'help': 1351, 'according': 1319, '000': 1268, 'city': 1202, 'million': 1173, 'school': 1168, 'make': 1159, 'need': 1124, 'news': 1121, 'federal': 1120, 'national': 1105, 'day': 1099, 'government': 1041, 'american': 1027, 'house': 978, 'department': 977, 'community': 951, 'funding': 933, 'law': 903, 'florida': 868, 'program': 864, 'county': 763, 'california': 755, 'campaign': 745, 'company': 744, 'health': 710, 'north': 689}
ASSAULT {'president': 9287, 'york': 9068, 'right': 8993, 'years': 8703, 'year': 8475, 'told': 7980, 'trump': 7730, 'time': 7267, 'white': 7208, 'world': 7158, 'times': 6550, 'people': 6506, 'new': 6319, 'say': 5945, 'state': 5900, 'suspect': 5778, 'states': 5321, 'shot': 4667, 'police': 4664, 'shooting': 4305, 'says': 4144, 'just': 3895, 'according': 3604, 'like': 3566, 'killed': 3545, 'city': 3518, 'news': 3441, 'attack': 3382, 'including': 3187, 'old': 3173, 'man': 3079, 'day': 3077, 'did': 3076, 'called': 2826, 'law': 2762, 'know': 2738, 'department': 2651, 'going': 2611, 'home': 2596, 'group': 2581, 'country': 2563, 'officials': 2508, 'family': 2499, 'american': 2496, 'florida': 2351, 'community': 2209, 'case': 2118, 'california': 1951, 'court': 1833, 'orlando': 1396}
COERCE {'president': 5555, 'york': 5262, 'said': 5248, 'years': 4926, 'police': 4869, 'trump': 4826, 'year': 4645, 'time': 4094, 'new': 4065, 'united': 4030, 'white': 3945, 'told': 3862, 'states': 3700, 'trial': 3662, 'prison': 3607, 'state': 3519, 'people': 3232, 'say': 2772, 'public': 2628, 'right': 2414, 'according': 2097, 'court': 2055, 'just': 2036, 'like': 1947, 'law': 1890, 'federal': 1876, 'including': 1863, 'case': 1863, 'old': 1774, 'news': 1766, 'city': 1748, 'did': 1724, 'day': 1665, 'office': 1632, 'department': 1618, 'charges': 1616, 'donald': 1594, 'attorney': 1593, 'man': 1544, 'criminal': 1504, 'house': 1464, '000': 1451, 'justice': 1431, 'media': 1419, 'government': 1408, 'national': 1378, 'judge': 1287, 'attack': 1270, 'county': 1172, 'biden': 834}
CONCEDE {'president': 2139, 'trump': 1994, 'said': 1825, 'york': 1821, 'public': 1796, 'years': 1748, 'year': 1613, 'time': 1577, 'told': 1554, 'white': 1547, 'state': 1423, 'times': 1421, 'right': 1397, 'states': 1395, 'think': 1293, 'people': 1113, 'son': 1030, 'say': 945, 'says': 890, 'just': 883, 'like': 869, 'political': 800, 'donald': 712, 'news': 695, 'law': 692, 'federal': 681, 'including': 675, 'house': 674, 'did': 664, 'office': 656, 'according': 639, 'case': 638, 'city': 605, 'department': 599, 'american': 591, 'country': 570, 'court': 569, 'going': 568, 'don': 565, 'biden': 565, 'government': 546, 'justice': 542, 'election': 540, 'charges': 524, 'family': 512, 'campaign': 506, 'police': 471, 'pardon': 441, 'florida': 330, 'hunter': 317}
CONSULT {'say': 20406, 'york': 20382, 'years': 19760, 'says': 19497, 'year': 18633, 'said': 17898, 'work': 16881, 'way': 16554, 'new': 16447, 'world': 16399, 'white': 16366, 'told': 15576, 'trump': 15380, 'time': 15290, 'united': 15082, 'people': 12213, 'times': 12112, 'state': 11580, 'think': 10648, 'school': 10095, 'states': 9870, 'just': 9150, 'like': 8976, 'president': 8869, 'city': 7296, 'including': 7224, 'according': 7171, 'news': 7084, 'day': 6949, 'make': 6432, 'did': 6406, 'know': 6319, 'going': 6000, 'right': 5984, 'american': 5827, 'don': 5813, 'home': 5718, 'country': 5707, 'public': 5680, 'national': 5472, 'family': 5395, 'life': 5364, 'house': 5252, 'law': 5220, 'police': 4813, 'government': 4772, 'florida': 4230, 'attack': 4078, 'court': 3606, 'israel': 2004}
COOPERATE {'said': 2160, 'public': 1948, 'york': 1912, 'years': 1892, 'year': 1839, 'work': 1631, 'says': 1587, 'united': 1535, 'world': 1533, 'new': 1461, 'told': 1429, 'time': 1415, 'times': 1397, 'trump': 1346, 'weinstein': 1251, 'state': 1240, 'support': 1087, 'states': 1064, 'people': 1058, 'security': 931, 'president': 819, 'like': 773, 'including': 737, 'according': 730, 'just': 725, 'help': 635, 'city': 626, '000': 614, 'news': 613, 'department': 592, 'day': 587, 'need': 585, 'make': 579, 'did': 565, 'law': 527, 'national': 522, 'police': 510, 'federal': 504, 'office': 502, 'old': 502, 'million': 471, 'american': 466, 'government': 455, 'county': 450, 'company': 449, 'california': 407, 'north': 390, 'florida': 366, 'assistance': 342, 'foreign': 181}
DEMAND {'president': 1259, 'york': 1157, 'political': 1139, 'years': 1100, 'trump': 1044, 'year': 1013, 'time': 955, 'united': 935, 'new': 919, 'white': 901, 'state': 900, 'work': 892, 'told': 889, 'states': 846, 'public': 817, 'people': 768, 'right': 645, 'say': 589, 'security': 566, 'just': 532, 'says': 522, 'like': 500, 'law': 448, 'news': 438, 'including': 435, 'did': 432, 'according': 431, 'federal': 421, 'called': 415, 'make': 413, 'day': 412, 'city': 408, 'department': 387, 'court': 375, 'going': 369, 'police': 369, 'office': 365, 'don': 363, 'government': 362, 'case': 360, 'national': 355, '000': 351, 'house': 342, 'order': 327, 'family': 306, 'administration': 302, 'election': 290, 'attack': 258, 'judge': 232, 'county': 206}
DISAPPROVE {'president': 8950, 'york': 8354, 'trump': 8236, 'political': 8194, 'years': 7606, 'year': 7258, 'told': 6819, 'united': 6658, 'white': 6568, 'time': 6522, 'new': 6467, 'times': 5993, 'states': 5898, 'public': 5629, 'state': 5500, 'people': 5321, 'statement': 4984, 'right': 4334, 'say': 3977, 'says': 3842, 'just': 3391, 'like': 3370, 'news': 3093, 'did': 3035, 'according': 3008, 'including': 2971, 'police': 2949, 'city': 2924, 'donald': 2882, 'called': 2802, 'media': 2664, 'law': 2604, 'day': 2601, 'country': 2566, 'federal': 2538, 'house': 2533, 'american': 2532, 'case': 2528, 'court': 2497, 'know': 2484, 'going': 2470, 'attack': 2414, 'group': 2372, 'department': 2322, 'government': 2091, 'campaign': 1910, 'election': 1786, 'florida': 1684, 'company': 1575, 'biden': 1174}
MOBILIZE {'york': 306, 'president': 305, 'year': 288, 'public': 288, 'trump': 279, 'white': 239, 'world': 239, 'people': 212, 'new': 209, 'violent': 206, 'tuesday': 204, 'told': 202, 'troops': 200, 'state': 194, 'police': 178, 'truck': 177, 'states': 176, 'city': 175, 'time': 172, 'say': 166, 'security': 161, 'national': 135, 'including': 123, 'like': 123, 'says': 122, 'officials': 116, 'according': 107, 'day': 106, 'attack': 105, 'just': 104, '000': 103, 'law': 103, 'department': 102, 'news': 99, 'federal': 96, 'man': 94, 'local': 92, 'military': 88, 'guard': 87, 'enforcement': 85, 'officers': 83, 'near': 81, 'administration': 81, 'florida': 78, 'center': 75, 'cities': 67, '2024': 47, 'path': 45, 'crime': 43, 'data': 34}
PROTEST {'said': 1282, 'protests': 1270, 'york': 1261, 'rally': 1214, 'trump': 1186, 'year': 1140, 'white': 1049, 'told': 1015, 'new': 945, 'violence': 945, 'people': 930, 'time': 915, 'university': 883, 'right': 847, 'times': 842, 'state': 806, 'states': 761, 'president': 708, 'protesters': 692, 'saturday': 678, 'say': 675, 'students': 671, 'city': 651, 'protest': 626, 'police': 555, 'like': 537, 'just': 530, 'day': 509, 'including': 502, 'country': 474, 'called': 456, 'according': 443, 'group': 443, 'news': 439, 'american': 428, 'donald': 426, 'government': 426, 'man': 422, 'outside': 421, 'media': 407, 'america': 373, 'political': 367, 'law': 354, 'anti': 354, 'officers': 309, 'charlottesville': 275, 'israel': 273, 'black': 253, 'kings': 186, 'floyd': 106}
REJECT {'said': 2883, 'york': 2483, 'right': 2451, 'years': 2303, 'trump': 2253, 'year': 2202, 'say': 2047, 'new': 2027, 'united': 1860, 'white': 1849, 'work': 1848, 'time': 1805, 'told': 1758, 'times': 1619, 'state': 1583, 'people': 1459, 'trial': 1392, 'president': 1368, 'states': 1345, 'says': 1286, 'think': 1256, 'like': 1120, 'just': 1057, 'public': 998, 'did': 983, 'including': 920, 'according': 906, 'news': 891, 'court': 884, 'law': 877, 'day': 851, 'make': 836, 'donald': 830, 'case': 814, 'city': 786, 'don': 770, 'going': 765, 'federal': 761, 'house': 754, 'american': 750, 'know': 740, 'national': 736, 'government': 735, 'political': 722, 'media': 717, 'department': 692, 'election': 597, 'judge': 545, 'police': 539, 'florida': 527}
RETREAT {'said': 2065, 'york': 1860, 'right': 1851, 'years': 1803, 'year': 1711, 'time': 1608, 'trump': 1606, 'united': 1541, 'work': 1539, 'told': 1468, 'world': 1467, 'times': 1311, 'state': 1278, 'santos': 1206, 'states': 1108, 'think': 1087, 'people': 945, 'say': 913, 'says': 822, 'just': 794, 'like': 786, 'release': 750, 'president': 736, 'released': 733, 'according': 704, 'including': 661, 'news': 656, 'city': 590, 'day': 588, 'make': 574, 'public': 572, 'did': 548, 'don': 510, 'american': 509, 'law': 500, 'department': 498, 'know': 492, 'country': 491, '000': 491, 'going': 482, 'life': 469, 'federal': 465, 'house': 454, 'case': 436, 'court': 436, 'police': 435, 'government': 430, 'family': 425, 'company': 313, 'biden': 203}
SANCTION {'said': 809, 'public': 797, 'york': 795, 'right': 770, 'years': 762, 'year': 716, 'trump': 666, 'work': 642, 'told': 631, 'white': 630, 'new': 626, 'time': 623, 'world': 597, 'wednesday': 566, 'united': 553, 'state': 551, 'people': 527, 'support': 455, 'states': 454, 'president': 434, 'statement': 373, 'like': 339, 'just': 336, 'including': 307, 'according': 301, 'news': 301, 'day': 268, 'city': 267, 'did': 262, 'national': 258, 'house': 249, 'called': 249, '000': 246, 'government': 244, 'federal': 243, 'law': 240, 'american': 239, 'media': 238, 'office': 235, 'officials': 229, 'country': 227, 'administration': 219, 'department': 210, 'court': 197, 'company': 194, 'case': 193, 'california': 193, 'power': 191, 'police': 156, 'contract': 52}
SUPPORT {'said': 7197, 'say': 6291, 'york': 6195, 'years': 6102, 'year': 5791, 'time': 5402, 'work': 5285, 'trump': 5221, 'white': 5152, 'world': 5149, 'united': 5088, 'says': 4998, 'told': 4894, 'support': 4311, 'state': 4158, 'think': 3880, 'states': 3808, 'people': 3776, 'president': 3135, 'school': 3092, 'like': 2741, 'just': 2698, 'right': 2476, 'including': 2398, 'city': 2186, 'public': 2154, 'day': 2078, 'make': 2075, 'according': 2065, 'news': 2033, 'did': 1978, 'american': 1967, 'national': 1887, 'know': 1861, 'country': 1859, 'house': 1784, 'community': 1774, 'law': 1762, 'going': 1722, 'government': 1722, '000': 1688, 'department': 1584, 'federal': 1552, 'political': 1548, 'police': 1380, 'campaign': 1294, 'attack': 1257, 'florida': 1229, 'court': 1223, 'israel': 580}
THREATHEN {'people': 1911, 'york': 1774, 'trump': 1721, 'police': 1697, 'president': 1635, 'years': 1633, 'year': 1541, 'state': 1504, 'united': 1488, 'told': 1466, 'time': 1435, 'states': 1372, 'new': 1360, 'white': 1355, 'public': 1066, 'security': 1058, 'say': 921, 'says': 882, 'right': 840, 'like': 761, 'according': 724, 'just': 718, 'city': 676, 'officials': 669, 'including': 634, 'news': 633, 'donald': 614, 'national': 611, 'called': 608, 'day': 606, 'make': 603, 'country': 587, 'did': 566, 'attack': 563, '000': 559, 'going': 551, 'know': 550, 'american': 549, 'law': 548, 'department': 542, 'house': 537, 'federal': 514, 'government': 487, 'florida': 444, 'court': 387, 'california': 357, 'north': 332, 'mr': 196, 'israel': 173, 'iran': 102}

In [78]:
for k,v in drop_word_counts.items():
    print(k,v)

AGREE {'said': 2544, 'public': 2267, 'york': 2260, 'years': 2241, 'year': 2116, 'way': 1974, 'time': 1962, 'work': 1929, 'world': 1874, 'says': 1809, 'united': 1799, 'new': 1777, 'trump': 1777, 'told': 1707, 'state': 1328, 'think': 1285, 'support': 1237, 'states': 1170, 'people': 1156, 'president': 1019, 'school': 998, 'like': 938, 'just': 884, 'including': 778, 'make': 757, 'city': 725, 'day': 705, 'according': 697, 'help': 675, 'news': 673, 'going': 646, '000': 633, 'know': 617, 'need': 612, 'did': 606, 'long': 603, 'american': 564, 'national': 548, 'don': 543, 'million': 525, 'florida': 518, 'house': 507, 'community': 502, 'law': 502, 'company': 487, 'government': 481, 'federal': 466, 'california': 445, 'police': 389, 'health': 345}
AID {'president': 1651, 'public': 1638, 'york': 1577, 'years': 1546, 'year': 1506, 'said': 1470, 'way': 1310, 'work': 1294, 'time': 1284, 'united': 1243, 'new': 1188, 'trump': 1184, 'water': 1146, 'told': 1113, 'state': 1072, 'right': 1041, 'people': 1027, 'support': 1022, 'states': 938, 'just': 657, 'like': 652, 'including': 615, 'help': 614, 'according': 586, '000': 565, 'school': 560, 'million': 541, 'make': 535, 'city': 529, 'need': 528, 'news': 497, 'federal': 494, 'national': 490, 'day': 489, 'american': 451, 'government': 449, 'funding': 447, 'department': 445, 'community': 445, 'going': 435, 'house': 414, 'florida': 405, 'law': 387, 'county': 375, 'california': 363, 'north': 345, 'health': 337, 'company': 337, 'campaign': 299, 'carolina': 184}
ASSAULT {'right': 4004, 'say': 4001, 'york': 3955, 'years': 3833, 'year': 3678, 'world': 3237, 'united': 3217, 'victims': 3201, 'white': 3172, 'told': 3075, 'trump': 2980, 'time': 2885, 'people': 2805, 'times': 2686, 'new': 2660, 'state': 2437, 'says': 2135, 'states': 2125, 'shooting': 2038, 'shot': 1795, 'police': 1762, 'just': 1697, 'president': 1688, 'like': 1582, 'killed': 1564, 'attack': 1496, 'according': 1485, 'city': 1467, 'news': 1453, 'old': 1378, 'including': 1325, 'man': 1302, 'day': 1261, 'did': 1241, 'law': 1174, 'know': 1173, 'florida': 1115, 'going': 1110, 'country': 1103, 'home': 1100, 'group': 1095, 'american': 1057, 'officials': 1043, 'department': 1040, 'family': 1036, 'community': 949, 'california': 815, 'gun': 765, 'orlando': 742, 'mateen': 423}
COERCE {'people': 2501, 'york': 2378, 'said': 2316, 'police': 2280, 'years': 2254, 'year': 2200, 'trump': 2096, 'president': 2058, 'united': 1900, 'time': 1854, 'white': 1812, 'told': 1779, 'new': 1762, 'states': 1739, 'state': 1655, 'trial': 1625, 'public': 1351, 'say': 1238, 'right': 1059, 'according': 982, 'old': 923, 'just': 915, 'like': 864, 'court': 859, 'including': 824, 'law': 798, 'news': 794, 'city': 787, 'case': 779, 'federal': 772, 'did': 756, 'office': 741, 'department': 713, 'man': 711, 'day': 710, 'attorney': 689, 'charges': 677, '000': 666, 'donald': 663, 'home': 633, 'national': 615, 'criminal': 615, 'house': 612, 'media': 608, 'attack': 556, 'justice': 555, 'county': 547, 'government': 539, 'judge': 507, 'florida': 493}
CONCEDE {'president': 1001, 'political': 893, 'trump': 885, 'york': 868, 'said': 863, 'years': 851, 'year': 784, 'time': 772, 'white': 732, 'way': 724, 'work': 708, 'told': 676, 'times': 652, 'public': 615, 'state': 598, 'states': 533, 'people': 527, 'think': 523, 'right': 517, 'just': 420, 'like': 401, 'make': 309, 'news': 308, 'according': 307, 'donald': 306, 'office': 299, 'did': 299, 'law': 298, 'federal': 294, 'day': 294, 'know': 293, 'including': 292, 'house': 292, 'don': 285, 'police': 281, 'city': 275, 'going': 272, 'country': 271, 'case': 268, 'american': 263, 'department': 257, 'government': 249, 'election': 240, 'court': 240, 'campaign': 218, 'charges': 211, 'biden': 209, 'justice': 208, 'pardon': 152, 'hunter': 107}
CONSULT {'say': 7301, 'york': 7214, 'years': 7126, 'says': 7035, 'year': 6701, 'work': 6139, 'said': 6096, 'way': 5986, 'world': 5881, 'white': 5790, 'new': 5606, 'told': 5374, 'time': 5371, 'united': 5295, 'trump': 5168, 'people': 4146, 'times': 4122, 'state': 3909, 'think': 3639, 'school': 3537, 'states': 3288, 'just': 3255, 'like': 3182, 'president': 2720, 'city': 2490, 'including': 2480, 'according': 2409, 'news': 2380, 'day': 2364, 'make': 2267, 'know': 2183, 'did': 2163, 'going': 2065, 'don': 2050, 'right': 2032, 'home': 1943, 'public': 1927, 'american': 1861, 'life': 1840, 'national': 1822, '000': 1792, 'family': 1788, 'group': 1779, 'house': 1758, 'community': 1675, 'law': 1673, 'florida': 1648, 'police': 1601, 'company': 1348, 'attack': 1301}
COOPERATE {'people': 987, 'years': 913, 'york': 896, 'police': 884, 'year': 856, 'said': 824, 'united': 767, 'work': 760, 'time': 746, 'world': 733, 'told': 689, 'support': 688, 'president': 687, 'trump': 685, 'new': 679, 'state': 633, 'states': 552, 'public': 473, 'says': 411, 'like': 372, 'according': 344, 'just': 335, 'including': 323, '000': 283, 'help': 277, 'city': 273, 'news': 272, 'office': 265, 'day': 264, 'department': 264, 'make': 263, 'need': 262, 'did': 252, 'know': 243, 'home': 231, 'million': 229, 'law': 228, 'going': 223, 'national': 221, 'country': 221, 'information': 218, 'american': 215, 'company': 209, 'federal': 207, 'family': 204, 'north': 202, 'county': 201, 'government': 198, 'florida': 190, 'california': 188}
DEMAND {'president': 611, 'political': 566, 'york': 559, 'years': 543, 'year': 492, 'trump': 474, 'time': 473, 'way': 472, 'white': 464, 'work': 446, 'united': 437, 'new': 434, 'told': 428, 'public': 395, 'state': 384, 'people': 369, 'states': 349, 'think': 341, 'right': 323, 'say': 297, 'just': 259, 'like': 236, 'including': 204, 'news': 202, 'called': 202, 'did': 201, 'make': 199, 'law': 197, 'federal': 196, 'according': 192, 'day': 188, 'city': 184, 'don': 177, 'department': 176, 'police': 173, 'going': 171, '000': 170, 'government': 169, 'know': 168, 'national': 168, 'country': 166, 'american': 165, 'case': 165, 'house': 164, 'media': 154, 'court': 154, 'america': 146, 'family': 129, 'attack': 115, 'florida': 113}
DISAPPROVE {'york': 3767, 'right': 3748, 'public': 3706, 'years': 3506, 'year': 3367, 'trump': 3345, 'white': 3118, 'violence': 2943, 'united': 2903, 'world': 2867, 'new': 2843, 'told': 2732, 'time': 2619, 'times': 2570, 'people': 2305, 'say': 2296, 'president': 2208, 'state': 2127, 'states': 2072, 'statement': 1869, 'says': 1599, 'like': 1515, 'just': 1509, 'according': 1331, 'did': 1324, 'news': 1322, 'including': 1301, 'city': 1264, 'donald': 1264, 'called': 1204, 'day': 1164, 'media': 1164, 'make': 1119, 'law': 1116, 'country': 1113, 'know': 1112, 'going': 1091, 'house': 1071, 'police': 1071, 'case': 1065, 'american': 1063, 'don': 1059, 'attack': 1053, 'court': 1024, 'political': 1023, 'federal': 1023, 'group': 1014, 'government': 857, 'florida': 779, 'company': 695}
MOBILIZE {'york': 125, 'say': 124, 'reports': 119, 'years': 113, 'year': 111, 'work': 97, 'united': 97, 'white': 95, 'world': 93, 'trump': 92, 'told': 84, 'new': 84, 'tuesday': 83, 'people': 82, 'state': 79, 'time': 73, 'support': 67, 'security': 65, 'states': 64, 'police': 62, 'city': 59, 'president': 54, 'including': 50, 'says': 50, 'day': 49, 'national': 48, 'officials': 47, 'like': 44, 'department': 42, 'according': 42, 'attack': 40, 'news': 38, 'just': 38, 'county': 37, 'country': 37, 'law': 36, 'officers': 36, 'force': 35, 'man': 35, 'federal': 34, 'military': 33, 'center': 32, 'near': 31, 'local': 31, 'florida': 30, 'guard': 29, 'enforcement': 29, 'home': 26, 'north': 22, 'crime': 17}
PROTEST {'said': 553, 'protests': 552, 'york': 538, 'rally': 538, 'trump': 522, 'year': 497, 'white': 474, 'violence': 441, 'told': 419, 'time': 409, 'university': 396, 'people': 394, 'virginia': 390, 'new': 383, 'state': 366, 'right': 362, 'saturday': 308, 'say': 306, 'president': 303, 'students': 294, 'protesters': 271, 'city': 264, 'protest': 258, 'rights': 257, 'police': 233, 'like': 229, 'just': 220, 'day': 209, 'including': 208, 'called': 196, 'country': 192, 'donald': 192, 'group': 189, 'according': 188, 'news': 180, 'did': 180, 'american': 180, 'outside': 178, 'man': 174, 'media': 173, 'government': 169, 'political': 143, 'officers': 135, 'charlottesville': 133, 'black': 109, 'israel': 99, 'kings': 72, 'mr': 53, 'google': 47, 'floyd': 44}
REJECT {'right': 1192, 'public': 1169, 'york': 1159, 'said': 1152, 'years': 1116, 'year': 1033, 'trump': 1033, 'new': 931, 'time': 930, 'united': 925, 'white': 898, 'work': 887, 'told': 865, 'state': 824, 'think': 801, 'say': 703, 'states': 696, 'people': 681, 'president': 643, 'security': 519, 'just': 514, 'like': 514, 'says': 464, 'did': 437, 'including': 418, 'according': 395, 'law': 394, 'news': 388, 'make': 388, 'day': 380, 'don': 359, 'donald': 357, 'court': 352, 'going': 352, 'city': 343, 'american': 341, 'political': 337, 'national': 336, 'case': 335, 'house': 329, 'know': 327, 'federal': 323, 'government': 321, 'media': 307, 'florida': 250, 'election': 239, 'party': 237, 'police': 229, 'company': 217, 'judge': 200}
RETREAT {'york': 892, 'public': 883, 'years': 861, 'press': 836, 'year': 808, 'said': 802, 'trump': 761, 'time': 739, 'work': 721, 'told': 712, 'world': 708, 'new': 693, 'states': 661, 'times': 647, 'state': 605, 'release': 515, 'released': 480, 'people': 440, 'says': 432, 'right': 417, 'like': 368, 'president': 366, 'just': 365, 'according': 321, 'news': 309, 'including': 298, 'city': 284, 'day': 270, 'did': 259, 'make': 258, 'long': 244, 'know': 239, 'don': 235, 'department': 233, '000': 231, 'police': 231, 'law': 219, 'life': 210, 'going': 209, 'house': 208, 'american': 203, 'federal': 196, 'home': 192, 'million': 191, 'government': 191, 'media': 190, 'case': 184, 'court': 177, 'company': 166, 'attack': 160}
SANCTION {'people': 413, 'president': 395, 'said': 364, 'york': 364, 'years': 359, 'year': 341, 'trump': 320, 'time': 308, 'white': 304, 'united': 302, 'work': 298, 'public': 288, 'support': 288, 'told': 285, 'new': 280, 'state': 245, 'states': 231, 'right': 218, 'storm': 173, 'like': 158, 'just': 154, 'including': 142, 'according': 137, 'news': 132, 'make': 126, 'did': 126, 'officials': 122, 'city': 120, 'day': 119, '000': 118, 'house': 116, 'national': 114, 'law': 106, 'american': 105, 'going': 105, 'country': 105, 'federal': 103, 'donald': 100, 'california': 100, 'government': 98, 'home': 97, 'group': 96, 'know': 94, 'case': 84, 'florida': 77, 'north': 75, 'company': 74, 'court': 72, 'county': 63, 'hurricane': 46}
SUPPORT {'say': 2989, 'york': 2930, 'years': 2914, 'says': 2868, 'year': 2733, 'said': 2543, 'work': 2483, 'white': 2404, 'world': 2394, 'way': 2381, 'new': 2360, 'united': 2247, 'trump': 2233, 'time': 2207, 'told': 2169, 'support': 1852, 'state': 1789, 'people': 1735, 'think': 1533, 'states': 1449, 'school': 1398, 'president': 1353, 'like': 1291, 'just': 1275, 'including': 1078, 'city': 980, 'make': 959, 'day': 937, 'right': 926, 'according': 924, 'news': 918, 'public': 897, 'american': 870, 'did': 865, 'know': 852, 'country': 825, 'national': 814, 'community': 813, 'house': 811, 'don': 799, 'going': 795, '000': 772, 'law': 758, 'group': 747, 'government': 712, 'florida': 628, 'campaign': 575, 'police': 558, 'attack': 539, 'israel': 218}
THREATHEN {'president': 889, 'said': 818, 'public': 813, 'york': 803, 'years': 761, 'trump': 749, 'year': 734, 'united': 664, 'time': 644, 'tuesday': 643, 'new': 627, 'told': 620, 'state': 575, 'people': 557, 'water': 543, 'right': 538, 'states': 529, 'storm': 438, 'security': 388, 'like': 345, 'just': 342, 'says': 326, 'according': 321, 'city': 319, 'including': 299, 'news': 290, 'police': 286, 'donald': 278, 'national': 275, 'country': 274, 'make': 272, 'day': 267, 'called': 262, '000': 252, 'going': 251, 'american': 242, 'know': 238, 'law': 237, 'officials': 235, 'department': 233, 'house': 232, 'attack': 229, 'don': 224, 'media': 220, 'government': 215, 'florida': 207, 'federal': 205, 'california': 183, 'north': 142, 'israel': 66}

In [ ]:
remove_words = ['trump','york','years','year','president']
remove_set = set(remove_words)

filtered_word_counts = {
    key: {word: count
          for word, count in counts.items()
          if word not in remove_set}
    for key, counts in word_counts.items()
}

In [79]:
drop_filtered_word_counts = {
    key: {word: count
          for word, count in counts.items()
          if word not in remove_set}
    for key, counts in drop_word_counts.items()
}

In [36]:
for k,v in filtered_word_counts.items():
    print(k,v)

AGREE {'said': 5634, 'says': 4869, 'work': 4194, 'world': 4083, 'way': 4002, 'new': 3966, 'white': 3912, 'told': 3852, 'time': 3795, 'school': 3765, 'united': 3575, 'state': 3111, 'support': 2618, 'people': 2599, 'think': 2508, 'states': 2421, 'like': 2070, 'just': 1978, 'including': 1725, 'according': 1626, 'city': 1614, 'day': 1592, 'make': 1582, 'right': 1557, 'news': 1502, 'help': 1492, 'public': 1446, 'going': 1440, '000': 1430, 'did': 1411, 'know': 1364, 'american': 1288, 'don': 1256, 'national': 1231, 'law': 1218, 'department': 1186, 'house': 1169, 'million': 1163, 'government': 1136, 'company': 1030, 'florida': 1000, 'california': 994, 'police': 889, 'court': 855, 'attack': 753}
AID {'public': 3392, 'right': 3342, 'said': 3336, 'work': 2729, 'time': 2622, 'new': 2579, 'world': 2547, 'united': 2536, 'water': 2323, 'state': 2318, 'told': 2308, 'support': 2099, 'people': 2039, 'states': 1896, 'says': 1604, 'just': 1427, 'like': 1426, 'including': 1391, 'help': 1351, 'according': 1319, '000': 1268, 'city': 1202, 'million': 1173, 'school': 1168, 'make': 1159, 'need': 1124, 'news': 1121, 'federal': 1120, 'national': 1105, 'day': 1099, 'government': 1041, 'american': 1027, 'house': 978, 'department': 977, 'community': 951, 'funding': 933, 'law': 903, 'florida': 868, 'program': 864, 'county': 763, 'california': 755, 'campaign': 745, 'company': 744, 'health': 710, 'north': 689}
ASSAULT {'right': 8993, 'told': 7980, 'time': 7267, 'white': 7208, 'world': 7158, 'times': 6550, 'people': 6506, 'new': 6319, 'say': 5945, 'state': 5900, 'suspect': 5778, 'states': 5321, 'shot': 4667, 'police': 4664, 'shooting': 4305, 'says': 4144, 'just': 3895, 'according': 3604, 'like': 3566, 'killed': 3545, 'city': 3518, 'news': 3441, 'attack': 3382, 'including': 3187, 'old': 3173, 'man': 3079, 'day': 3077, 'did': 3076, 'called': 2826, 'law': 2762, 'know': 2738, 'department': 2651, 'going': 2611, 'home': 2596, 'group': 2581, 'country': 2563, 'officials': 2508, 'family': 2499, 'american': 2496, 'florida': 2351, 'community': 2209, 'case': 2118, 'california': 1951, 'court': 1833, 'orlando': 1396}
COERCE {'said': 5248, 'police': 4869, 'time': 4094, 'new': 4065, 'united': 4030, 'white': 3945, 'told': 3862, 'states': 3700, 'trial': 3662, 'prison': 3607, 'state': 3519, 'people': 3232, 'say': 2772, 'public': 2628, 'right': 2414, 'according': 2097, 'court': 2055, 'just': 2036, 'like': 1947, 'law': 1890, 'federal': 1876, 'including': 1863, 'case': 1863, 'old': 1774, 'news': 1766, 'city': 1748, 'did': 1724, 'day': 1665, 'office': 1632, 'department': 1618, 'charges': 1616, 'donald': 1594, 'attorney': 1593, 'man': 1544, 'criminal': 1504, 'house': 1464, '000': 1451, 'justice': 1431, 'media': 1419, 'government': 1408, 'national': 1378, 'judge': 1287, 'attack': 1270, 'county': 1172, 'biden': 834}
CONCEDE {'said': 1825, 'public': 1796, 'time': 1577, 'told': 1554, 'white': 1547, 'state': 1423, 'times': 1421, 'right': 1397, 'states': 1395, 'think': 1293, 'people': 1113, 'son': 1030, 'say': 945, 'says': 890, 'just': 883, 'like': 869, 'political': 800, 'donald': 712, 'news': 695, 'law': 692, 'federal': 681, 'including': 675, 'house': 674, 'did': 664, 'office': 656, 'according': 639, 'case': 638, 'city': 605, 'department': 599, 'american': 591, 'country': 570, 'court': 569, 'going': 568, 'don': 565, 'biden': 565, 'government': 546, 'justice': 542, 'election': 540, 'charges': 524, 'family': 512, 'campaign': 506, 'police': 471, 'pardon': 441, 'florida': 330, 'hunter': 317}
CONSULT {'say': 20406, 'says': 19497, 'said': 17898, 'work': 16881, 'way': 16554, 'new': 16447, 'world': 16399, 'white': 16366, 'told': 15576, 'time': 15290, 'united': 15082, 'people': 12213, 'times': 12112, 'state': 11580, 'think': 10648, 'school': 10095, 'states': 9870, 'just': 9150, 'like': 8976, 'city': 7296, 'including': 7224, 'according': 7171, 'news': 7084, 'day': 6949, 'make': 6432, 'did': 6406, 'know': 6319, 'going': 6000, 'right': 5984, 'american': 5827, 'don': 5813, 'home': 5718, 'country': 5707, 'public': 5680, 'national': 5472, 'family': 5395, 'life': 5364, 'house': 5252, 'law': 5220, 'police': 4813, 'government': 4772, 'florida': 4230, 'attack': 4078, 'court': 3606, 'israel': 2004}
COOPERATE {'said': 2160, 'public': 1948, 'work': 1631, 'says': 1587, 'united': 1535, 'world': 1533, 'new': 1461, 'told': 1429, 'time': 1415, 'times': 1397, 'weinstein': 1251, 'state': 1240, 'support': 1087, 'states': 1064, 'people': 1058, 'security': 931, 'like': 773, 'including': 737, 'according': 730, 'just': 725, 'help': 635, 'city': 626, '000': 614, 'news': 613, 'department': 592, 'day': 587, 'need': 585, 'make': 579, 'did': 565, 'law': 527, 'national': 522, 'police': 510, 'federal': 504, 'office': 502, 'old': 502, 'million': 471, 'american': 466, 'government': 455, 'county': 450, 'company': 449, 'california': 407, 'north': 390, 'florida': 366, 'assistance': 342, 'foreign': 181}
DEMAND {'political': 1139, 'time': 955, 'united': 935, 'new': 919, 'white': 901, 'state': 900, 'work': 892, 'told': 889, 'states': 846, 'public': 817, 'people': 768, 'right': 645, 'say': 589, 'security': 566, 'just': 532, 'says': 522, 'like': 500, 'law': 448, 'news': 438, 'including': 435, 'did': 432, 'according': 431, 'federal': 421, 'called': 415, 'make': 413, 'day': 412, 'city': 408, 'department': 387, 'court': 375, 'going': 369, 'police': 369, 'office': 365, 'don': 363, 'government': 362, 'case': 360, 'national': 355, '000': 351, 'house': 342, 'order': 327, 'family': 306, 'administration': 302, 'election': 290, 'attack': 258, 'judge': 232, 'county': 206}
DISAPPROVE {'political': 8194, 'told': 6819, 'united': 6658, 'white': 6568, 'time': 6522, 'new': 6467, 'times': 5993, 'states': 5898, 'public': 5629, 'state': 5500, 'people': 5321, 'statement': 4984, 'right': 4334, 'say': 3977, 'says': 3842, 'just': 3391, 'like': 3370, 'news': 3093, 'did': 3035, 'according': 3008, 'including': 2971, 'police': 2949, 'city': 2924, 'donald': 2882, 'called': 2802, 'media': 2664, 'law': 2604, 'day': 2601, 'country': 2566, 'federal': 2538, 'house': 2533, 'american': 2532, 'case': 2528, 'court': 2497, 'know': 2484, 'going': 2470, 'attack': 2414, 'group': 2372, 'department': 2322, 'government': 2091, 'campaign': 1910, 'election': 1786, 'florida': 1684, 'company': 1575, 'biden': 1174}
MOBILIZE {'public': 288, 'white': 239, 'world': 239, 'people': 212, 'new': 209, 'violent': 206, 'tuesday': 204, 'told': 202, 'troops': 200, 'state': 194, 'police': 178, 'truck': 177, 'states': 176, 'city': 175, 'time': 172, 'say': 166, 'security': 161, 'national': 135, 'including': 123, 'like': 123, 'says': 122, 'officials': 116, 'according': 107, 'day': 106, 'attack': 105, 'just': 104, '000': 103, 'law': 103, 'department': 102, 'news': 99, 'federal': 96, 'man': 94, 'local': 92, 'military': 88, 'guard': 87, 'enforcement': 85, 'officers': 83, 'near': 81, 'administration': 81, 'florida': 78, 'center': 75, 'cities': 67, '2024': 47, 'path': 45, 'crime': 43, 'data': 34}
PROTEST {'said': 1282, 'protests': 1270, 'rally': 1214, 'white': 1049, 'told': 1015, 'new': 945, 'violence': 945, 'people': 930, 'time': 915, 'university': 883, 'right': 847, 'times': 842, 'state': 806, 'states': 761, 'protesters': 692, 'saturday': 678, 'say': 675, 'students': 671, 'city': 651, 'protest': 626, 'police': 555, 'like': 537, 'just': 530, 'day': 509, 'including': 502, 'country': 474, 'called': 456, 'according': 443, 'group': 443, 'news': 439, 'american': 428, 'donald': 426, 'government': 426, 'man': 422, 'outside': 421, 'media': 407, 'america': 373, 'political': 367, 'law': 354, 'anti': 354, 'officers': 309, 'charlottesville': 275, 'israel': 273, 'black': 253, 'kings': 186, 'floyd': 106}
REJECT {'said': 2883, 'right': 2451, 'say': 2047, 'new': 2027, 'united': 1860, 'white': 1849, 'work': 1848, 'time': 1805, 'told': 1758, 'times': 1619, 'state': 1583, 'people': 1459, 'trial': 1392, 'states': 1345, 'says': 1286, 'think': 1256, 'like': 1120, 'just': 1057, 'public': 998, 'did': 983, 'including': 920, 'according': 906, 'news': 891, 'court': 884, 'law': 877, 'day': 851, 'make': 836, 'donald': 830, 'case': 814, 'city': 786, 'don': 770, 'going': 765, 'federal': 761, 'house': 754, 'american': 750, 'know': 740, 'national': 736, 'government': 735, 'political': 722, 'media': 717, 'department': 692, 'election': 597, 'judge': 545, 'police': 539, 'florida': 527}
RETREAT {'said': 2065, 'right': 1851, 'time': 1608, 'united': 1541, 'work': 1539, 'told': 1468, 'world': 1467, 'times': 1311, 'state': 1278, 'santos': 1206, 'states': 1108, 'think': 1087, 'people': 945, 'say': 913, 'says': 822, 'just': 794, 'like': 786, 'release': 750, 'released': 733, 'according': 704, 'including': 661, 'news': 656, 'city': 590, 'day': 588, 'make': 574, 'public': 572, 'did': 548, 'don': 510, 'american': 509, 'law': 500, 'department': 498, 'know': 492, 'country': 491, '000': 491, 'going': 482, 'life': 469, 'federal': 465, 'house': 454, 'case': 436, 'court': 436, 'police': 435, 'government': 430, 'family': 425, 'company': 313, 'biden': 203}
SANCTION {'said': 809, 'public': 797, 'right': 770, 'work': 642, 'told': 631, 'white': 630, 'new': 626, 'time': 623, 'world': 597, 'wednesday': 566, 'united': 553, 'state': 551, 'people': 527, 'support': 455, 'states': 454, 'statement': 373, 'like': 339, 'just': 336, 'including': 307, 'according': 301, 'news': 301, 'day': 268, 'city': 267, 'did': 262, 'national': 258, 'house': 249, 'called': 249, '000': 246, 'government': 244, 'federal': 243, 'law': 240, 'american': 239, 'media': 238, 'office': 235, 'officials': 229, 'country': 227, 'administration': 219, 'department': 210, 'court': 197, 'company': 194, 'case': 193, 'california': 193, 'power': 191, 'police': 156, 'contract': 52}
SUPPORT {'said': 7197, 'say': 6291, 'time': 5402, 'work': 5285, 'white': 5152, 'world': 5149, 'united': 5088, 'says': 4998, 'told': 4894, 'support': 4311, 'state': 4158, 'think': 3880, 'states': 3808, 'people': 3776, 'school': 3092, 'like': 2741, 'just': 2698, 'right': 2476, 'including': 2398, 'city': 2186, 'public': 2154, 'day': 2078, 'make': 2075, 'according': 2065, 'news': 2033, 'did': 1978, 'american': 1967, 'national': 1887, 'know': 1861, 'country': 1859, 'house': 1784, 'community': 1774, 'law': 1762, 'going': 1722, 'government': 1722, '000': 1688, 'department': 1584, 'federal': 1552, 'political': 1548, 'police': 1380, 'campaign': 1294, 'attack': 1257, 'florida': 1229, 'court': 1223, 'israel': 580}
THREATHEN {'people': 1911, 'police': 1697, 'state': 1504, 'united': 1488, 'told': 1466, 'time': 1435, 'states': 1372, 'new': 1360, 'white': 1355, 'public': 1066, 'security': 1058, 'say': 921, 'says': 882, 'right': 840, 'like': 761, 'according': 724, 'just': 718, 'city': 676, 'officials': 669, 'including': 634, 'news': 633, 'donald': 614, 'national': 611, 'called': 608, 'day': 606, 'make': 603, 'country': 587, 'did': 566, 'attack': 563, '000': 559, 'going': 551, 'know': 550, 'american': 549, 'law': 548, 'department': 542, 'house': 537, 'federal': 514, 'government': 487, 'florida': 444, 'court': 387, 'california': 357, 'north': 332, 'mr': 196, 'israel': 173, 'iran': 102}

In [80]:
for k,v in drop_filtered_word_counts.items():
    print(k,v)

AGREE {'said': 2544, 'public': 2267, 'way': 1974, 'time': 1962, 'work': 1929, 'world': 1874, 'says': 1809, 'united': 1799, 'new': 1777, 'told': 1707, 'state': 1328, 'think': 1285, 'support': 1237, 'states': 1170, 'people': 1156, 'school': 998, 'like': 938, 'just': 884, 'including': 778, 'make': 757, 'city': 725, 'day': 705, 'according': 697, 'help': 675, 'news': 673, 'going': 646, '000': 633, 'know': 617, 'need': 612, 'did': 606, 'long': 603, 'american': 564, 'national': 548, 'don': 543, 'million': 525, 'florida': 518, 'house': 507, 'community': 502, 'law': 502, 'company': 487, 'government': 481, 'federal': 466, 'california': 445, 'police': 389, 'health': 345}
AID {'public': 1638, 'said': 1470, 'way': 1310, 'work': 1294, 'time': 1284, 'united': 1243, 'new': 1188, 'water': 1146, 'told': 1113, 'state': 1072, 'right': 1041, 'people': 1027, 'support': 1022, 'states': 938, 'just': 657, 'like': 652, 'including': 615, 'help': 614, 'according': 586, '000': 565, 'school': 560, 'million': 541, 'make': 535, 'city': 529, 'need': 528, 'news': 497, 'federal': 494, 'national': 490, 'day': 489, 'american': 451, 'government': 449, 'funding': 447, 'department': 445, 'community': 445, 'going': 435, 'house': 414, 'florida': 405, 'law': 387, 'county': 375, 'california': 363, 'north': 345, 'health': 337, 'company': 337, 'campaign': 299, 'carolina': 184}
ASSAULT {'right': 4004, 'say': 4001, 'world': 3237, 'united': 3217, 'victims': 3201, 'white': 3172, 'told': 3075, 'time': 2885, 'people': 2805, 'times': 2686, 'new': 2660, 'state': 2437, 'says': 2135, 'states': 2125, 'shooting': 2038, 'shot': 1795, 'police': 1762, 'just': 1697, 'like': 1582, 'killed': 1564, 'attack': 1496, 'according': 1485, 'city': 1467, 'news': 1453, 'old': 1378, 'including': 1325, 'man': 1302, 'day': 1261, 'did': 1241, 'law': 1174, 'know': 1173, 'florida': 1115, 'going': 1110, 'country': 1103, 'home': 1100, 'group': 1095, 'american': 1057, 'officials': 1043, 'department': 1040, 'family': 1036, 'community': 949, 'california': 815, 'gun': 765, 'orlando': 742, 'mateen': 423}
COERCE {'people': 2501, 'said': 2316, 'police': 2280, 'united': 1900, 'time': 1854, 'white': 1812, 'told': 1779, 'new': 1762, 'states': 1739, 'state': 1655, 'trial': 1625, 'public': 1351, 'say': 1238, 'right': 1059, 'according': 982, 'old': 923, 'just': 915, 'like': 864, 'court': 859, 'including': 824, 'law': 798, 'news': 794, 'city': 787, 'case': 779, 'federal': 772, 'did': 756, 'office': 741, 'department': 713, 'man': 711, 'day': 710, 'attorney': 689, 'charges': 677, '000': 666, 'donald': 663, 'home': 633, 'national': 615, 'criminal': 615, 'house': 612, 'media': 608, 'attack': 556, 'justice': 555, 'county': 547, 'government': 539, 'judge': 507, 'florida': 493}
CONCEDE {'political': 893, 'said': 863, 'time': 772, 'white': 732, 'way': 724, 'work': 708, 'told': 676, 'times': 652, 'public': 615, 'state': 598, 'states': 533, 'people': 527, 'think': 523, 'right': 517, 'just': 420, 'like': 401, 'make': 309, 'news': 308, 'according': 307, 'donald': 306, 'office': 299, 'did': 299, 'law': 298, 'federal': 294, 'day': 294, 'know': 293, 'including': 292, 'house': 292, 'don': 285, 'police': 281, 'city': 275, 'going': 272, 'country': 271, 'case': 268, 'american': 263, 'department': 257, 'government': 249, 'election': 240, 'court': 240, 'campaign': 218, 'charges': 211, 'biden': 209, 'justice': 208, 'pardon': 152, 'hunter': 107}
CONSULT {'say': 7301, 'says': 7035, 'work': 6139, 'said': 6096, 'way': 5986, 'world': 5881, 'white': 5790, 'new': 5606, 'told': 5374, 'time': 5371, 'united': 5295, 'people': 4146, 'times': 4122, 'state': 3909, 'think': 3639, 'school': 3537, 'states': 3288, 'just': 3255, 'like': 3182, 'city': 2490, 'including': 2480, 'according': 2409, 'news': 2380, 'day': 2364, 'make': 2267, 'know': 2183, 'did': 2163, 'going': 2065, 'don': 2050, 'right': 2032, 'home': 1943, 'public': 1927, 'american': 1861, 'life': 1840, 'national': 1822, '000': 1792, 'family': 1788, 'group': 1779, 'house': 1758, 'community': 1675, 'law': 1673, 'florida': 1648, 'police': 1601, 'company': 1348, 'attack': 1301}
COOPERATE {'people': 987, 'police': 884, 'said': 824, 'united': 767, 'work': 760, 'time': 746, 'world': 733, 'told': 689, 'support': 688, 'new': 679, 'state': 633, 'states': 552, 'public': 473, 'says': 411, 'like': 372, 'according': 344, 'just': 335, 'including': 323, '000': 283, 'help': 277, 'city': 273, 'news': 272, 'office': 265, 'day': 264, 'department': 264, 'make': 263, 'need': 262, 'did': 252, 'know': 243, 'home': 231, 'million': 229, 'law': 228, 'going': 223, 'national': 221, 'country': 221, 'information': 218, 'american': 215, 'company': 209, 'federal': 207, 'family': 204, 'north': 202, 'county': 201, 'government': 198, 'florida': 190, 'california': 188}
DEMAND {'political': 566, 'time': 473, 'way': 472, 'white': 464, 'work': 446, 'united': 437, 'new': 434, 'told': 428, 'public': 395, 'state': 384, 'people': 369, 'states': 349, 'think': 341, 'right': 323, 'say': 297, 'just': 259, 'like': 236, 'including': 204, 'news': 202, 'called': 202, 'did': 201, 'make': 199, 'law': 197, 'federal': 196, 'according': 192, 'day': 188, 'city': 184, 'don': 177, 'department': 176, 'police': 173, 'going': 171, '000': 170, 'government': 169, 'know': 168, 'national': 168, 'country': 166, 'american': 165, 'case': 165, 'house': 164, 'media': 154, 'court': 154, 'america': 146, 'family': 129, 'attack': 115, 'florida': 113}
DISAPPROVE {'right': 3748, 'public': 3706, 'white': 3118, 'violence': 2943, 'united': 2903, 'world': 2867, 'new': 2843, 'told': 2732, 'time': 2619, 'times': 2570, 'people': 2305, 'say': 2296, 'state': 2127, 'states': 2072, 'statement': 1869, 'says': 1599, 'like': 1515, 'just': 1509, 'according': 1331, 'did': 1324, 'news': 1322, 'including': 1301, 'city': 1264, 'donald': 1264, 'called': 1204, 'day': 1164, 'media': 1164, 'make': 1119, 'law': 1116, 'country': 1113, 'know': 1112, 'going': 1091, 'house': 1071, 'police': 1071, 'case': 1065, 'american': 1063, 'don': 1059, 'attack': 1053, 'court': 1024, 'political': 1023, 'federal': 1023, 'group': 1014, 'government': 857, 'florida': 779, 'company': 695}
MOBILIZE {'say': 124, 'reports': 119, 'work': 97, 'united': 97, 'white': 95, 'world': 93, 'told': 84, 'new': 84, 'tuesday': 83, 'people': 82, 'state': 79, 'time': 73, 'support': 67, 'security': 65, 'states': 64, 'police': 62, 'city': 59, 'including': 50, 'says': 50, 'day': 49, 'national': 48, 'officials': 47, 'like': 44, 'department': 42, 'according': 42, 'attack': 40, 'news': 38, 'just': 38, 'county': 37, 'country': 37, 'law': 36, 'officers': 36, 'force': 35, 'man': 35, 'federal': 34, 'military': 33, 'center': 32, 'near': 31, 'local': 31, 'florida': 30, 'guard': 29, 'enforcement': 29, 'home': 26, 'north': 22, 'crime': 17}
PROTEST {'said': 553, 'protests': 552, 'rally': 538, 'white': 474, 'violence': 441, 'told': 419, 'time': 409, 'university': 396, 'people': 394, 'virginia': 390, 'new': 383, 'state': 366, 'right': 362, 'saturday': 308, 'say': 306, 'students': 294, 'protesters': 271, 'city': 264, 'protest': 258, 'rights': 257, 'police': 233, 'like': 229, 'just': 220, 'day': 209, 'including': 208, 'called': 196, 'country': 192, 'donald': 192, 'group': 189, 'according': 188, 'news': 180, 'did': 180, 'american': 180, 'outside': 178, 'man': 174, 'media': 173, 'government': 169, 'political': 143, 'officers': 135, 'charlottesville': 133, 'black': 109, 'israel': 99, 'kings': 72, 'mr': 53, 'google': 47, 'floyd': 44}
REJECT {'right': 1192, 'public': 1169, 'said': 1152, 'new': 931, 'time': 930, 'united': 925, 'white': 898, 'work': 887, 'told': 865, 'state': 824, 'think': 801, 'say': 703, 'states': 696, 'people': 681, 'security': 519, 'just': 514, 'like': 514, 'says': 464, 'did': 437, 'including': 418, 'according': 395, 'law': 394, 'news': 388, 'make': 388, 'day': 380, 'don': 359, 'donald': 357, 'court': 352, 'going': 352, 'city': 343, 'american': 341, 'political': 337, 'national': 336, 'case': 335, 'house': 329, 'know': 327, 'federal': 323, 'government': 321, 'media': 307, 'florida': 250, 'election': 239, 'party': 237, 'police': 229, 'company': 217, 'judge': 200}
RETREAT {'public': 883, 'press': 836, 'said': 802, 'time': 739, 'work': 721, 'told': 712, 'world': 708, 'new': 693, 'states': 661, 'times': 647, 'state': 605, 'release': 515, 'released': 480, 'people': 440, 'says': 432, 'right': 417, 'like': 368, 'just': 365, 'according': 321, 'news': 309, 'including': 298, 'city': 284, 'day': 270, 'did': 259, 'make': 258, 'long': 244, 'know': 239, 'don': 235, 'department': 233, '000': 231, 'police': 231, 'law': 219, 'life': 210, 'going': 209, 'house': 208, 'american': 203, 'federal': 196, 'home': 192, 'million': 191, 'government': 191, 'media': 190, 'case': 184, 'court': 177, 'company': 166, 'attack': 160}
SANCTION {'people': 413, 'said': 364, 'time': 308, 'white': 304, 'united': 302, 'work': 298, 'public': 288, 'support': 288, 'told': 285, 'new': 280, 'state': 245, 'states': 231, 'right': 218, 'storm': 173, 'like': 158, 'just': 154, 'including': 142, 'according': 137, 'news': 132, 'make': 126, 'did': 126, 'officials': 122, 'city': 120, 'day': 119, '000': 118, 'house': 116, 'national': 114, 'law': 106, 'american': 105, 'going': 105, 'country': 105, 'federal': 103, 'donald': 100, 'california': 100, 'government': 98, 'home': 97, 'group': 96, 'know': 94, 'case': 84, 'florida': 77, 'north': 75, 'company': 74, 'court': 72, 'county': 63, 'hurricane': 46}
SUPPORT {'say': 2989, 'says': 2868, 'said': 2543, 'work': 2483, 'white': 2404, 'world': 2394, 'way': 2381, 'new': 2360, 'united': 2247, 'time': 2207, 'told': 2169, 'support': 1852, 'state': 1789, 'people': 1735, 'think': 1533, 'states': 1449, 'school': 1398, 'like': 1291, 'just': 1275, 'including': 1078, 'city': 980, 'make': 959, 'day': 937, 'right': 926, 'according': 924, 'news': 918, 'public': 897, 'american': 870, 'did': 865, 'know': 852, 'country': 825, 'national': 814, 'community': 813, 'house': 811, 'don': 799, 'going': 795, '000': 772, 'law': 758, 'group': 747, 'government': 712, 'florida': 628, 'campaign': 575, 'police': 558, 'attack': 539, 'israel': 218}
THREATHEN {'said': 818, 'public': 813, 'united': 664, 'time': 644, 'tuesday': 643, 'new': 627, 'told': 620, 'state': 575, 'people': 557, 'water': 543, 'right': 538, 'states': 529, 'storm': 438, 'security': 388, 'like': 345, 'just': 342, 'says': 326, 'according': 321, 'city': 319, 'including': 299, 'news': 290, 'police': 286, 'donald': 278, 'national': 275, 'country': 274, 'make': 272, 'day': 267, 'called': 262, '000': 252, 'going': 251, 'american': 242, 'know': 238, 'law': 237, 'officials': 235, 'department': 233, 'house': 232, 'attack': 229, 'don': 224, 'media': 220, 'government': 215, 'florida': 207, 'federal': 205, 'california': 183, 'north': 142, 'israel': 66}

In [43]:
def add_empath_per_group(dfs, text_col="text", normalize=True):
    out = {}

    for key, sub_df in dfs.items():
        sub_df = sub_df.copy()

        texts = sub_df[text_col].fillna("").astype(str)

        empath_scores = []
        for t in texts:
            if t.strip():
                empath_scores.append(
                    lexicon.analyze(t, normalize=normalize)
                )
            else:
                empath_scores.append({})

        sub_df["empath"] = empath_scores
        out[key] = sub_df

    return out

In [42]:
empath_df = add_empath_per_group(dfs)

In [81]:
drop_empath_df = add_empath_per_group(dfs_drop)

In [83]:
drop_empath_df['AID']

,index,GlobalEventID,date,Year,Actor1Code,Actor1Name,Actor1CountryCode,Actor1EthnicCode,Actor2Code,Actor2Name,...,description,sbert_text_title,embedding_json_title,sbert_text,embedding_json,first_para,first_para_emb,PloverCode,EventLabel,empath
6,16,1200205786,20240925,2024,USA,FLORIDA,USA,NaN,NaN,NaN,...,Tropical Storm Helene's trajectory threatens t...,"Tropical Storm Helene threatens the U.S., Mexico","[0.007524872664362192, 0.10208725184202194, 0....",NaN,NaN,Tropical storm and hurricane watches were issu...,"[0.008987472392618656, 0.0025142861995846033, ...",AID,AID,"{'help': 0.0, 'office': 0.0, 'dance': 0.0, 'mo..."
53,192,1200246221,20240925,2024,MIL,CARRIER,NaN,NaN,NaN,NaN,...,Florida’s Third District Court of Appeal recen...,Order Denying Motion to Dismiss under Florida’...,"[-0.008244303055107594, 0.02947995625436306, 0...",NaN,NaN,Florida’s Third District Court of Appeal recen...,"[0.008134478703141212, -0.002518073422834277, ...",AID,AID,"{'help': 0.006557377049180328, 'office': 0.0, ..."
55,194,1200247990,20240925,2024,REL,ABBOT,NaN,NaN,USA,FLORIDA,...,Tropical Storm Helene is expected to strengthe...,Gov. Abbott sends search and rescue team to Fl...,"[-0.02673930488526821, -0.04822605848312378, 0...",NaN,NaN,Tropical Storm Helene is expected to strengthe...,"[0.0016634989297017455, 0.002456099260598421, ...",AID,AID,"{'help': 0.014925373134328358, 'office': 0.0, ..."
56,195,1200248221,20240925,2024,USA,UNITED STATES,USA,NaN,HLH,MEDICAL SPECIALIST,...,The team headed to Florida is made up of 80 me...,'It's a calling' | 9 women among those on VA T...,"[-0.02080177329480648, 0.003331208834424615, 0...",NaN,NaN,The team headed to Florida is made up of 80 me...,"[0.023279637098312378, -0.04088704660534859, -...",AID,AID,"{'help': 0.01366742596810934, 'office': 0.0022..."
108,351,1200326583,20240925,2024,USA,FLORIDA,USA,NaN,NaN,NaN,...,House approves bill to study making US Jewish ...,Museum on US Jewish history to become part of ...,"[0.008966092951595783, 0.09074261039495468, -0...",NaN,NaN,American Jews are one step closer to having a ...,"[0.04561415687203407, 0.10061408579349518, -0....",AID,AID,"{'help': 0.00683371298405467, 'office': 0.0, '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37833,122714,679572657,20170808,2017,MED,WEBSITE,NaN,NaN,CANEDU,MCGILL,...,From Pathocracy to the (Mis)Anthropocene Psych...,Ecocide and the Psychotic 0.5 Per Cent,"[0.06396777927875519, 0.04475044086575508, -0....",NaN,NaN,From Pathocracy to the (Mis)Anthropocene,"[-0.0013103554956614971, 0.01027937326580286, ...",AID,AID,"{'help': 0.002331002331002331, 'office': 0.001..."
37849,122772,679630956,20170808,2017,BUS,AEROSPACE,NaN,NaN,NaN,NaN,...,"Leesburg, VA (PRWEB) August 08, 2017 -- ProJet...",ProJet Aviation promotes Julie O’Brien and Tin...,"[0.01783275231719017, -0.0002711133856792003, ...",NaN,NaN,"Leesburg, VA (PRWEB) August 08, 2017 -- ProJet...","[0.03776798024773598, 0.04905354231595993, -0....",AID,AID,"{'help': 0.011647254575707155, 'office': 0.006..."
37854,122790,679642700,20170808,2017,USA,VIRGINIA,USA,NaN,NaN,NaN,...,"Avizia, a leading provider of system-wide tele...",Avizia to expand healthcare IT operation in Fa...,"[0.062479496002197266, 0.04440399631857872, -0...",NaN,NaN,"Avizia, a leading provider of system-wide tele...","[0.043314699083566666, -0.05537300184369087, -...",AID,AID,"{'help': 0.009881422924901186, 'office': 0.001..."
37855,122792,679642839,20170808,2017,USA,UNITED STATES,USA,NaN,EDU,STUDENT,...,Kelly Shushok creates an environment for self-...,Interfaith consultant analyzes spiritual cultu...,"[0.03528764471411705, 0.03554699942469597, -0....",NaN,NaN,Shushok’s commitment to the Blacksburg communi...,"[-0.02673555538058281, 0.03598686307668686, -0...",AID,AID,"{'help': 0.0029411764705882353, 'office': 0.00..."
37858,122806,679647649,20170808,2017,USA,CALIFORNIA,USA,NaN,NaN,NaN,...,This is just insane… it’s national suicide if ...,Left Claiming 'Apartheid' If Non-citizens Are ...,"[0.007430342957377434, 0.07771247625350952, -0...",NaN,NaN,Left Claiming ‘Apartheid’ If Non-citizens Are ...,"[0.0047860643826425076, 0.07197187840938568, -...",AID,AID,"{'help': 0.005244755244755245, 'office': 0.0, ..."

In [47]:
def sorted_nonzero_empath(d):
    return sorted(
        ((k, v) for k, v in d.items() if v > 0),
        key=lambda x: x[1],
        reverse=True
    )

In [49]:
for key, df in empath_df.items():
    df["empath_sorted"] = df["empath"].apply(sorted_nonzero_empath)

In [84]:
for key, df in drop_empath_df.items():
    df["empath_sorted"] = df["empath"].apply(sorted_nonzero_empath)

In [51]:
group_empath = {}

for key, df in empath_df.items():
    agg = Counter()
    for d in df["empath"]:
        agg.update(d)

    group_empath[key] = dict(agg.most_common())

In [85]:
drop_group_empath = {}

for key, df in drop_empath_df.items():
    agg = Counter()
    for d in df["empath"]:
        agg.update(d)

    drop_group_empath[key] = dict(agg.most_common())

In [52]:
group_empath['AID']

{'business': 43.56922197351027,
 'government': 36.886458114447,
 'economics': 31.87855262729575,
 'work': 29.240785367591688,
 'money': 28.58200639209145,
 'giving': 27.192476208568735,
 'law': 26.38987483147518,
 'help': 25.615626912516102,
 'leader': 24.269268441979122,
 'communication': 23.586954454561543,
 'payment': 22.773856995748755,
 'valuable': 22.69232368974326,
 'banking': 22.55997886333286,
 'college': 21.263980347765557,
 'internet': 20.300075390312067,
 'crime': 20.18001674398241,
 'school': 18.92523697708976,
 'meeting': 17.877785075252845,
 'real_estate': 17.190712549915457,
 'negative_emotion': 16.84796337140489,
 'technology': 16.62294111884675,
 'politics': 16.483960457165864,
 'speaking': 16.040573931342198,
 'wealthy': 15.689415497672552,
 'messaging': 15.465649364494919,
 'office': 15.418338440292963,
 'dispute': 14.516113324021825,
 'social_media': 13.676822815806826,
 'gain': 13.378690796041244,
 'celebration': 13.242698937610038,
 'stealing': 13.179280974146323,
 'party': 13.141207342257134,
 'programming': 13.049229709095407,
 'traveling': 12.763163173897372,
 'war': 12.605577088226468,
 'reading': 12.591442872188829,
 'journalism': 12.417261081074038,
 'computer': 12.373849951200723,
 'writing': 12.086069001585736,
 'fight': 11.972032524238125,
 'vacation': 11.848277451279657,
 'positive_emotion': 11.402587304697454,
 'poor': 11.178969649982944,
 'urban': 11.009598666421796,
 'occupation': 11.001178146974528,
 'wedding': 10.745395867373846,
 'military': 10.649594141247775,
 'violence': 10.399984454921059,
 'healing': 10.321979462395607,
 'children': 10.069020372227028,
 'family': 10.02265007678257,
 'strength': 9.986769084047129,
 'weapon': 9.91258159435537,
 'shopping': 9.902764264367697,
 'power': 9.859257153719994,
 'achievement': 9.78501135748307,
 'phone': 9.598510091401257,
 'white_collar_job': 9.596054881134638,
 'health': 9.326541168241645,
 'dominant_heirarchical': 9.272050447021773,
 'aggression': 9.048528728236905,
 'science': 9.028016417606445,
 'trust': 9.024308551741962,
 'injury': 8.82955547955552,
 'medical_emergency': 8.724291039780935,
 'competing': 8.669561997607625,
 'movement': 8.574962465799898,
 'home': 8.406595894828412,
 'kill': 8.142993793319928,
 'driving': 8.083599099356332,
 'suffering': 7.973573882573399,
 'friends': 7.9443682864862115,
 'death': 7.873260138124386,
 'prison': 7.725057506312332,
 'sports': 7.71315376257757,
 'shape_and_size': 7.658787887094198,
 'vehicle': 7.530164979103293,
 'air_travel': 7.319609780939121,
 'order': 7.113649300626181,
 'optimism': 7.028544360565042,
 'hearing': 6.9389515235306956,
 'domestic_work': 6.741226683700167,
 'heroic': 6.6355653170726985,
 'listen': 6.59783372608253,
 'negotiate': 6.543962154165923,
 'car': 6.4421977154809555,
 'weather': 6.329029528436181,
 'restaurant': 6.198562727366052,
 'breaking': 6.022133341498096,
 'terrorism': 6.009921667399123,
 'pain': 5.956210456017875,
 'tourism': 5.823719618538415,
 'leisure': 5.708612988727844,
 'beach': 5.3802882790800926,
 'sadness': 5.20480700544911,
 'water': 5.1844419433400795,
 'eating': 5.160840499522309,
 'warmth': 5.1392184442274225,
 'music': 5.095496488392748,
 'rural': 4.99307709862897,
 'love': 4.925203173490271,
 'morning': 4.625830371518128,
 'liquid': 4.595326252491358,
 'art': 4.540069131906139,
 'cleaning': 4.4791791346070555,
 'sailing': 4.46092815588152,
 'cooking': 4.455892773503356,
 'ocean': 4.389774654604684,
 'body': 4.388364419255559,
 'fire': 4.385195453359589,
 'musical': 4.297872148094467,
 'clothing': 4.26077046871529,
 'shame': 4.205901293096545,
 'independence': 4.134881153563464,
 'attractive': 4.054306991998071,
 'cold': 3.859879182366402,
 'fun': 3.786499924936284,
 'fashion': 3.69658490886893,
 'religion': 3.657778169628506,
 'noise': 3.6408389511997536,
 'appearance': 3.632571952484353,
 'play': 3.5365530241644745,
 'philosophy': 3.4329540956855675,
 'sexual': 3.3933346737704535,
 'emotional': 3.3544895619043866,
 'masculine': 3.31543379030875,
 'hate': 3.279649066156726,
 'legend': 3.2400798592520017,
 'swimming': 3.234914020650775,
 'youth': 3.158991835327252,
 'fear': 3.1540029266278387,
 'feminine': 3.0494533749516504,
 'deception': 2.906396531877388,
 'affection': 2.8866508867342717,
 'torment': 2.794345012920329,
 'disappointment': 2.7292253540929825,
 'plant': 2.6941301449118793,
 'pride': 2.693687380823352,
 'animal': 2.6832089514255797,
 'exercise': 2.6762652010462933,
 'beauty': 2.6700560583506863,
 'royalty': 2.6566359825439982,
 'furniture': 2.648672259127222,
 'nervousness': 2.5978337872978763,
 'dance': 2.503999103835291,
 'divine': 2.470268656091405,
 'sleep': 2.4407076692213114,
 'hiking': 2.4299996835756654,
 'confusion': 2.40130086697858,
 'weakness': 2.3682025582593647,
 'ancient': 2.34362057061455,
 'ship': 2.2865211415649207,
 'childish': 2.2595851144252417,
 'contentment': 2.244258104773861,
 'hipster': 2.2021374045836644,
 'toy': 2.175880686461546,
 'rage': 2.170622568598339,
 'fabric': 2.125042981076921,
 'magic': 2.1172208764803706,
 'horror': 2.1061192201816654,
 'tool': 2.087627331740534,
 'sound': 2.03457053500649,
 'hygiene': 2.006213716164168,
 'worship': 1.9929103240212585,
 'alcohol': 1.9536664651910849,
 'joy': 1.8283903939143509,
 'anger': 1.7557526375841943,
 'night': 1.731547325216602,
 'sympathy': 1.6710313066931415,
 'surprise': 1.6604560042537613,
 'blue_collar_job': 1.6566930107710773,
 'neglect': 1.654346199433408,
 'lust': 1.6512717546585634,
 'dominant_personality': 1.6005989791006203,
 'farming': 1.5816120033477414,
 'exotic': 1.5018679289854358,
 'disgust': 1.450048256162449,
 'zest': 1.3445932261232634,
 'anticipation': 1.3030395801206645,
 'timidity': 1.2747569242296608,
 'pet': 1.272347550956075,
 'politeness': 1.2128613608997183,
 'monster': 1.1473000071611759,
 'smell': 1.1266635114870047,
 'envy': 1.1251823056195496,
 'cheerfulness': 0.9881443650378018,
 'ridicule': 0.73576579553854,
 'anonymity': 0.6902103875796077,
 'irritability': 0.6894970851981957,
 'exasperation': 0.6173583229458091,
 'superhero': 0.5420107379197949,
 'swearing_terms': 0.4592590039647696,
 'medieval': 0.35799819336541266,
 'ugliness': 0.35477021581796614}

In [86]:
for k,v in drop_group_empath.items():
    print(k,v)

AGREE {'business': 26.278045405563798, 'government': 17.011676206440143, 'work': 16.279847153798165, 'economics': 16.0839226233017, 'communication': 15.482275572838837, 'meeting': 14.556895893237016, 'leader': 14.454158079059148, 'giving': 14.323298483642887, 'money': 13.154306198293725, 'law': 13.004636363044694, 'crime': 12.432843370523106, 'help': 12.225416178638916, 'party': 12.067150414060876, 'school': 11.750528167465594, 'speaking': 11.637187584696331, 'celebration': 11.611061686638275, 'college': 11.512110161939558, 'traveling': 11.439273828315747, 'internet': 11.254434568459148, 'office': 10.665817091749664, 'valuable': 10.463180211131993, 'payment': 10.373808660857842, 'real_estate': 10.367234502144271, 'vacation': 10.332347523908266, 'banking': 10.199332470213497, 'negative_emotion': 10.160035974207316, 'messaging': 9.52425902814506, 'technology': 9.295034007486969, 'politics': 8.948988804553919, 'dispute': 8.763793818007581, 'family': 8.636840633234259, 'social_media': 8.372249762687035, 'stealing': 8.306650149251114, 'wedding': 8.005425565597417, 'occupation': 7.966891032003805, 'positive_emotion': 7.896519194253788, 'programming': 7.645130974871435, 'reading': 7.568061785878457, 'children': 7.534520674521223, 'air_travel': 7.440658297998298, 'fight': 7.3312510431609885, 'war': 7.257793490841606, 'achievement': 7.2171906178217275, 'computer': 7.193978371651879, 'journalism': 6.800729878965032, 'phone': 6.781711515951984, 'writing': 6.777084260011885, 'urban': 6.7175521157876155, 'gain': 6.632291459941859, 'movement': 6.520063387205037, 'home': 6.437829760082433, 'white_collar_job': 6.423388198744329, 'strength': 6.328775794592985, 'friends': 6.24274009184202, 'violence': 6.101416311024438, 'shopping': 6.091569057460172, 'weapon': 6.054480251638744, 'wealthy': 5.990212951319765, 'driving': 5.939151312272965, 'power': 5.925186624649098, 'healing': 5.819719366807478, 'trust': 5.78180110414762, 'science': 5.683955029318186, 'sports': 5.657381624239181, 'competing': 5.640850904530141, 'military': 5.56837735658075, 'vehicle': 5.493319197959524, 'aggression': 5.369627752438319, 'death': 5.358779553455008, 'health': 5.358713263656488, 'tourism': 5.358658505808128, 'dominant_heirarchical': 5.3302226624036635, 'optimism': 5.234808310504781, 'listen': 5.226497347922143, 'prison': 5.1251079509868696, 'shape_and_size': 5.072907716491476, 'kill': 5.04366076249924, 'injury': 5.020343563311978, 'hearing': 5.006525251428836, 'medical_emergency': 4.981122534068817, 'order': 4.9478827714439335, 'music': 4.725789510616437, 'car': 4.709021551391273, 'domestic_work': 4.441860699029696, 'suffering': 4.370948426208927, 'musical': 4.272284002298082, 'poor': 4.200031949659377, 'leisure': 4.121317575270359, 'negotiate': 4.069434496261876, 'art': 4.036456402623648, 'pain': 3.820960861978446, 'weather': 3.79185042531048, 'restaurant': 3.693326706902465, 'love': 3.426870034596968, 'terrorism': 3.3413655431573317, 'breaking': 3.244354646335871, 'body': 3.2339578860769573, 'heroic': 3.1531842156838734, 'morning': 3.054002580254937, 'sadness': 3.0366125459668734, 'attractive': 2.962953612152988, 'fun': 2.84523437887381, 'rural': 2.807835367191766, 'warmth': 2.8024726026567195, 'clothing': 2.744059219104572, 'play': 2.7227258687854645, 'cold': 2.720994571661271, 'appearance': 2.7145251982991914, 'shame': 2.6391775049455752, 'dance': 2.615262144008825, 'eating': 2.589695985174525, 'independence': 2.574261353212796, 'feminine': 2.542621950062456, 'beach': 2.5347631233096406, 'religion': 2.4428626212609226, 'youth': 2.4149606322125106, 'fashion': 2.3962161522042873, 'cooking': 2.384384445350139, 'sexual': 2.364511817249151, 'sailing': 2.3511952231002295, 'philosophy': 2.238849965854944, 'water': 2.1730681700958057, 'ocean': 2.1640878163910036, 'masculine': 2.089232645374121, 'emotional': 2.0583273127018455, 'legend': 2.050175503079569, 'furniture': 2.030095965445178, 'noise': 2.0246066735119057, 'fire': 2.0211945540415566, 'pride': 2.006530367910335, 'royalty': 1.9382289855708568, 'fear': 1.9232707548143677, 'divine': 1.893199221705788, 'sleep': 1.8924120185947804, 'torment': 1.8877500457019918, 'hate': 1.8734938597349986, 'liquid': 1.8428542842528757, 'nervousness': 1.7742506946849497, 'affection': 1.7605560312239041, 'beauty': 1.7525786205100036, 'cleaning': 1.7522223719669647, 'ship': 1.7360723161511165, 'toy': 1.7299522431367917, 'confusion': 1.6775863631763828, 'childish': 1.6646499941902064, 'exercise': 1.6539335218122824, 'alcohol': 1.6233285454640947, 'hipster': 1.618190715385943, 'deception': 1.6117003078881085, 'hiking': 1.5856903621293768, 'plant': 1.5549547312126308, 'animal': 1.5462358126609375, 'ancient': 1.5092248200607863, 'sound': 1.4967146796820254, 'disappointment': 1.4752234752206723, 'weakness': 1.4661865098765852, 'night': 1.4267800899291816, 'horror': 1.325387339091086, 'magic': 1.318550795319148, 'surprise': 1.2970194292703232, 'worship': 1.2938588223315002, 'contentment': 1.292736818210472, 'tool': 1.2889167956717353, 'dominant_personality': 1.2796847100678173, 'blue_collar_job': 1.2795500475346344, 'fabric': 1.2668397675039087, 'rage': 1.2528813575072975, 'swimming': 1.246674323605693, 'lust': 1.1075059459961623, 'hygiene': 1.1058323569546826, 'sympathy': 1.0708598516250547, 'anger': 1.0071679993996705, 'neglect': 0.968791427703513, 'joy': 0.9213691549135021, 'exotic': 0.8937091228472617, 'zest': 0.8681913419524679, 'farming': 0.8330102938717364, 'anticipation': 0.8024320391674649, 'timidity': 0.7931333268826716, 'politeness': 0.7840387402759675, 'cheerfulness': 0.7768798412588522, 'disgust': 0.7764499360051798, 'monster': 0.759691290742844, 'envy': 0.7220905880726209, 'pet': 0.7211587912414127, 'smell': 0.7127391188694139, 'irritability': 0.475436522080431, 'superhero': 0.439747335307189, 'ridicule': 0.4162892078208829, 'exasperation': 0.39360568368760135, 'anonymity': 0.391232852445209, 'medieval': 0.38103195770227266, 'swearing_terms': 0.2775373830127391, 'ugliness': 0.25985582049920614}
AID {'business': 20.63301189560863, 'government': 16.59587436733355, 'economics': 15.316822117209751, 'work': 13.774061913837038, 'money': 13.632189286059647, 'giving': 13.087515711665253, 'law': 11.754212003397502, 'help': 11.69041875662034, 'communication': 10.977227594392325, 'payment': 10.962425957108088, 'banking': 10.91567787750943, 'valuable': 10.899565409035128, 'leader': 10.710688456714488, 'college': 9.858464688650667, 'internet': 9.65916900697786, 'crime': 8.937291263116, 'school': 8.531985702519863, 'real_estate': 8.276825464225434, 'technology': 8.174258761761392, 'meeting': 8.086552535531583, 'negative_emotion': 7.8825756349820155, 'wealthy': 7.619790335939553, 'speaking': 7.213956731230687, 'messaging': 7.1970441244380705, 'politics': 7.143238292767954, 'office': 6.910678952871517, 'gain': 6.525133344617499, 'celebration': 6.410817084694998, 'party': 6.375908837895423, 'social_media': 6.339999302749275, 'dispute': 6.308707783908792, 'reading': 6.307630849774245, 'programming': 6.278177546599225, 'traveling': 5.8917946159843275, 'computer': 5.84025653581958, 'writing': 5.7991563937652435, 'war': 5.768785153199529, 'stealing': 5.68775182207848, 'journalism': 5.649091385186814, 'vacation': 5.523228049788583, 'positive_emotion': 5.391547124247606, 'poor': 5.383016130390715, 'fight': 5.356118896026313, 'urban': 5.2740313184976495, 'healing': 5.169291449145728, 'violence': 5.060009612858332, 'children': 4.99475738661296, 'occupation': 4.985759158587267, 'wedding': 4.9447284507368225, 'family': 4.823254845816673, 'military': 4.7765525628354535, 'strength': 4.747816021997886, 'health': 4.732762801910683, 'achievement': 4.67990340102208, 'shopping': 4.650616582961082, 'phone': 4.626991436017177, 'science': 4.583484071740951, 'power': 4.563265538460453, 'weapon': 4.542961721475786, 'injury': 4.48787393567834, 'medical_emergency': 4.370991027637335, 'aggression': 4.271907701432497, 'white_collar_job': 4.262709230618216, 'dominant_heirarchical': 4.235445487646114, 'movement': 4.157277833714894, 'trust': 4.101794089658747, 'competing': 4.095127752526592, 'death': 4.019411157960498, 'home': 3.9170788008444246, 'kill': 3.83935634837749, 'suffering': 3.825742669807007, 'driving': 3.7589380181892933, 'sports': 3.735608525243978, 'shape_and_size': 3.625215007982485, 'air_travel': 3.5692530188732783, 'vehicle': 3.5337783167205044, 'optimism': 3.45164455314745, 'prison': 3.411653542776373, 'friends': 3.3453213034012474, 'weather': 3.334378849071685, 'heroic': 3.3014726282316404, 'negotiate': 3.248044796454483, 'domestic_work': 3.240538984751991, 'hearing': 3.2343282061389527, 'listen': 3.0571859426906767, 'order': 3.0497014296856286, 'car': 2.983662422776374, 'breaking': 2.9024972464479766, 'restaurant': 2.8864952309635985, 'terrorism': 2.7914882331371422, 'water': 2.765618191825413, 'beach': 2.7549708307746785, 'pain': 2.674482745308742, 'warmth': 2.6554400093822084, 'leisure': 2.625115887231509, 'music': 2.610612892045072, 'tourism': 2.575118392143142, 'liquid': 2.541650247225919, 'rural': 2.5249361269093313, 'sadness': 2.5172995284390964, 'love': 2.3917156318194013, 'eating': 2.3854194634018557, 'sailing': 2.355451394901933, 'ocean': 2.301882278284832, 'cleaning': 2.2658146406857838, 'art': 2.262388599057095, 'morning': 2.2049818169628748, 'body': 2.2022406928444838, 'fire': 2.1352925473433175, 'cooking': 2.1319283254014505, 'musical': 2.1164888422656323, 'shame': 2.094232027592478, 'cold': 2.0685271671646297, 'clothing': 2.0637309110938857, 'independence': 1.9055788993814984, 'appearance': 1.898065846167444, 'attractive': 1.8183710077857538, 'fashion': 1.8068145253803536, 'swimming': 1.7926906873616717, 'noise': 1.7515622296889832, 'fun': 1.729929721617524, 'youth': 1.704251398126115, 'religion': 1.6683401387295147, 'masculine': 1.634797495019688, 'emotional': 1.6287638397144233, 'play': 1.6264283143790852, 'fear': 1.568850257305203, 'philosophy': 1.5556972225090289, 'animal': 1.5389393654689933, 'sexual': 1.5303922303410245, 'feminine': 1.5163511052561691, 'legend': 1.4885559050941473, 'hate': 1.4449430251762363, 'affection': 1.4230899363711709, 'torment': 1.3838287970934393, 'disappointment': 1.3270349487814401, 'pride': 1.3017479012120745, 'deception': 1.2899071659222072, 'exercise': 1.2857740389583519, 'plant': 1.2619260681112758, 'divine': 1.2481031942045266, 'nervousness': 1.2453101482536746, 'hipster': 1.2169905868755677, 'royalty': 1.2127855845986064, 'hiking': 1.203012584792521, 'dance': 1.1722014263933085, 'ship': 1.1613140519003389, 'weakness': 1.1430964921935522, 'sleep': 1.141317665179472, 'childish': 1.139156560309235, 'furniture': 1.1202030476059213, 'ancient': 1.107300692007956, 'beauty': 1.0959266936971621, 'toy': 1.089032427042203, 'sound': 1.0652653145338582, 'contentment': 1.065098661230422, 'confusion': 1.0396176955292715, 'tool': 1.0221146511266705, 'rage': 1.0078687995518352, 'horror': 1.0028707462289717, 'magic': 0.9994575222470976, 'hygiene': 0.9798457648823815, 'fabric': 0.9454318000143537, 'worship': 0.9384962911776171, 'alcohol': 0.9070502706969701, 'neglect': 0.8469546111431769, 'joy': 0.8315207058844434, 'farming': 0.8249000797845509, 'anger': 0.8248272130826411, 'pet': 0.8073682947198035, 'lust': 0.776299938936405, 'night': 0.7638643368952256, 'surprise': 0.7495071383265929, 'blue_collar_job': 0.7470684808465009, 'exotic': 0.7398116098551235, 'sympathy': 0.7048070880485646, 'disgust': 0.6834516759137447, 'anticipation': 0.6110225548096857, 'timidity': 0.5847252875056236, 'politeness': 0.582420979087264, 'zest': 0.5672756121720953, 'dominant_personality': 0.5595377975188718, 'envy': 0.5458817688792379, 'smell': 0.527440677284151, 'cheerfulness': 0.4858972787077033, 'monster': 0.48399154797630733, 'ridicule': 0.3745596258204458, 'anonymity': 0.3033134340774045, 'irritability': 0.3029289849925393, 'exasperation': 0.2905445362404434, 'superhero': 0.24206666821615708, 'medieval': 0.1949102510046696, 'swearing_terms': 0.18785829187313802, 'ugliness': 0.16531052156378132}
ASSAULT {'crime': 49.26845890746376, 'weapon': 37.65186215129769, 'negative_emotion': 34.25513210602291, 'business': 28.552753745255707, 'stealing': 27.396373217879688, 'government': 26.759050616077374, 'kill': 25.1948421267071, 'communication': 24.971656805897883, 'war': 24.904742136139458, 'law': 24.087790419519603, 'speaking': 23.68583296970376, 'work': 21.267176846041934, 'fight': 21.233588042574315, 'leader': 20.543229820519546, 'aggression': 19.872020227338567, 'dispute': 19.797991344011486, 'party': 19.249002119293756, 'death': 18.87909049980021, 'violence': 18.778908034973, 'children': 18.134874032197857, 'celebration': 17.706813301677652, 'suffering': 17.24056657128357, 'driving': 17.06056904165987, 'internet': 16.447926840847032, 'family': 16.367856719123374, 'vehicle': 15.838020656371992, 'meeting': 15.639039214293675, 'vacation': 15.54157128614461, 'college': 15.130877842992163, 'social_media': 15.041888726288608, 'giving': 14.698005819611787, 'politics': 14.514387552789495, 'urban': 14.348494486075234, 'prison': 14.306650104205984, 'school': 14.305706543008656, 'messaging': 14.27277240687308, 'real_estate': 14.051399539191122, 'traveling': 13.954875208812485, 'home': 13.747069163534702, 'car': 13.679181311015501, 'help': 13.491253748515065, 'wedding': 13.309532399454842, 'pain': 13.273684369118616, 'injury': 12.994950307322448, 'office': 12.89044176743088, 'positive_emotion': 12.78826488285773, 'reading': 12.775164116047383, 'economics': 12.43293767803616, 'occupation': 12.224496780902514, 'phone': 11.90833504611621, 'writing': 11.830981054390989, 'money': 11.630588946432376, 'power': 11.54342067836287, 'terrorism': 11.176771306003397, 'listen': 11.176409031616851, 'white_collar_job': 11.03219927420639, 'journalism': 10.698963997951484, 'military': 10.590463612171945, 'technology': 10.351373458058614, 'strength': 10.189818862864309, 'friends': 10.074386660583356, 'healing': 10.044437472339979, 'medical_emergency': 10.03718038825976, 'hearing': 9.87298273311231, 'banking': 9.741369736740173, 'valuable': 9.647575586137982, 'movement': 9.540712174794471, 'payment': 9.44503754308028, 'sadness': 9.433068149757982, 'sports': 9.200606676653246, 'domestic_work': 9.149286506251807, 'trust': 9.02185198700175, 'programming': 8.623053748845098, 'computer': 8.604473750121965, 'alcohol': 8.481505284915151, 'shape_and_size': 8.091297448411106, 'air_travel': 8.022948882423178, 'sexual': 7.859782039787464, 'order': 7.689628903981777, 'achievement': 7.675988841118797, 'health': 7.6542208307259365, 'leisure': 7.636169874118016, 'competing': 7.520666629582679, 'dominant_heirarchical': 7.473540099684247, 'torment': 7.459374001730447, 'masculine': 7.440759813174213, 'shame': 7.4037827154318405, 'warmth': 7.200213949616378, 'fire': 7.166444543229864, 'musical': 7.131377190928559, 'body': 6.991568530738567, 'music': 6.990056240357927, 'breaking': 6.955041469551069, 'weather': 6.695359843504666, 'hate': 6.511972616770606, 'shopping': 6.440607043613735, 'morning': 6.437350712153348, 'heroic': 6.372147248332756, 'optimism': 6.331773084186817, 'love': 6.16671454003766, 'horror': 6.1183426171990645, 'tourism': 6.089257463462504, 'clothing': 6.053914511510439, 'fear': 6.0526270109017934, 'gain': 5.957354405656334, 'appearance': 5.889412472351069, 'youth': 5.860968182934281, 'feminine': 5.763700814691797, 'weakness': 5.7398605551772555, 'rage': 5.649165141483972, 'cold': 5.403510169637546, 'wealthy': 5.338716564836916, 'fun': 5.337668134763925, 'noise': 5.167156359274658, 'religion': 5.051498256737036, 'science': 5.015905645638783, 'emotional': 4.996107287905453, 'nervousness': 4.855942489993507, 'disappointment': 4.676647601205905, 'play': 4.586682301306655, 'deception': 4.502093209679902, 'art': 4.497834341655755, 'restaurant': 4.43329726212008, 'attractive': 4.413111391632611, 'rural': 4.3312368639323395, 'poor': 4.325427123181857, 'sleep': 4.303756440607981, 'beach': 4.10218233355572, 'negotiate': 4.095082031438424, 'divine': 4.0890877148652045, 'dance': 4.0659553168714275, 'ocean': 3.99939168444065, 'childish': 3.99365641114529, 'surprise': 3.9874334037408876, 'sound': 3.9508050348970016, 'hiking': 3.931331201559054, 'philosophy': 3.8094812271156995, 'sailing': 3.7297219519334175, 'water': 3.7000817191723367, 'fashion': 3.636815891718533, 'animal': 3.5978118270881123, 'night': 3.44538815628843, 'legend': 3.4155763289894376, 'confusion': 3.393107475191362, 'royalty': 3.3838857265037876, 'cleaning': 3.3659237989638897, 'independence': 3.3397753183796546, 'liquid': 3.2953914978537306, 'affection': 3.1546967547232203, 'anger': 3.1472688569880347, 'toy': 2.819593025577485, 'worship': 2.8097886441456277, 'beauty': 2.753819583447071, 'furniture': 2.7222147343208616, 'ancient': 2.64010616546604, 'sympathy': 2.636866705131362, 'pride': 2.5893906898184653, 'exercise': 2.5885174355752745, 'eating': 2.556634398894185, 'monster': 2.5303233559853706, 'disgust': 2.5152103986520045, 'swimming': 2.4226467684300506, 'plant': 2.4042618965566116, 'hipster': 2.3770510861322474, 'envy': 2.3217787904995126, 'cooking': 2.2698443754339226, 'lust': 2.232762404564627, 'ship': 2.207721887909484, 'tool': 2.1715987795264073, 'timidity': 2.105573945015871, 'contentment': 2.065017354205302, 'fabric': 2.0371202252546583, 'neglect': 2.022470779702462, 'magic': 1.9665546860611938, 'hygiene': 1.6473960726467671, 'blue_collar_job': 1.5061369693842226, 'exotic': 1.4127476876533165, 'dominant_personality': 1.367902300505763, 'irritability': 1.3625070746811545, 'smell': 1.3340233322753947, 'joy': 1.2445290686784762, 'cheerfulness': 1.20551986241367, 'superhero': 1.1868858313690613, 'pet': 1.1752019152641833, 'zest': 1.1704770666574142, 'politeness': 1.1561053978172677, 'farming': 1.0672456069091074, 'ridicule': 1.059947704558262, 'anticipation': 1.0269503356843437, 'anonymity': 1.021473065880491, 'exasperation': 0.996179428327286, 'ugliness': 0.6909077513239187, 'swearing_terms': 0.664973411422445, 'medieval': 0.4618813586363106}

In [54]:
for k,v in group_empath.items():
    print(k,v)

AGREE {'business': 56.511528167407164, 'government': 39.236374858030324, 'work': 36.16088514785117, 'communication': 34.90537559913113, 'meeting': 33.99005315915082, 'economics': 33.76819457662186, 'leader': 33.678622609892656, 'law': 31.264163881414706, 'giving': 31.093997563989173, 'crime': 29.763700859783444, 'money': 28.26543515904663, 'help': 26.6462784169926, 'speaking': 26.140805894844576, 'traveling': 25.949831423928302, 'school': 25.92436422694717, 'college': 25.608435104770756, 'party': 25.013044290076387, 'office': 24.98778814150994, 'internet': 24.837884394059, 'celebration': 24.68655388869227, 'vacation': 22.694238917284974, 'banking': 22.59423239225709, 'negative_emotion': 22.473734311757237, 'payment': 22.141053462984903, 'dispute': 22.102005082692816, 'valuable': 21.94248568019802, 'messaging': 21.319348570914293, 'politics': 20.79875726106351, 'stealing': 19.96132067082979, 'technology': 19.78362107587388, 'real_estate': 19.728942402563803, 'family': 19.240580266365257, 'social_media': 18.442604679365644, 'occupation': 18.18402461557423, 'wedding': 17.546826544874246, 'positive_emotion': 17.526376581049636, 'war': 17.344061857917524, 'fight': 17.296038077714694, 'programming': 16.762077027419274, 'reading': 16.316363279335825, 'air_travel': 16.049089017552298, 'children': 15.799946472171428, 'computer': 15.76402208072594, 'achievement': 15.460636876132613, 'white_collar_job': 15.076869643925104, 'phone': 14.929361435062193, 'writing': 14.875003555578765, 'gain': 14.576416451164578, 'friends': 14.511372878074702, 'journalism': 14.471525395840478, 'strength': 14.376886363115812, 'movement': 14.196297482366084, 'weapon': 14.193550588330108, 'power': 13.746540050986532, 'violence': 13.731050289377878, 'urban': 13.625629245594723, 'home': 13.490555472915506, 'trust': 13.353703440460574, 'shopping': 13.177353370421056, 'aggression': 12.657016211190614, 'dominant_heirarchical': 12.647713840734971, 'wealthy': 12.61043389507118, 'competing': 12.595493737606823, 'sports': 12.544314949317949, 'tourism': 12.53888239902901, 'driving': 12.443516861279306, 'prison': 12.382265185390692, 'military': 12.268260930321546, 'healing': 12.081513242643002, 'science': 11.982078473372841, 'optimism': 11.719749848032725, 'death': 11.471647359173275, 'kill': 11.312065942296044, 'vehicle': 11.253543424717568, 'order': 11.143717841605545, 'listen': 11.054065641994644, 'hearing': 10.661975246908352, 'injury': 10.620093069227734, 'shape_and_size': 10.546055339006267, 'health': 10.516558447569654, 'medical_emergency': 9.812169249647418, 'music': 9.81185506764369, 'domestic_work': 9.712657961319202, 'car': 9.513956276896145, 'musical': 9.333909089149701, 'suffering': 9.292113421371953, 'negotiate': 8.945245409805679, 'poor': 8.909612431577118, 'leisure': 8.794530584916116, 'pain': 8.513737521404966, 'art': 8.324658365346396, 'restaurant': 8.196186856752659, 'terrorism': 8.06669973653294, 'love': 7.709327098217635, 'weather': 7.698371658604867, 'body': 7.31631344575679, 'breaking': 6.846008519849237, 'heroic': 6.66889871405319, 'attractive': 6.613937620968386, 'morning': 6.506063441290927, 'clothing': 6.501249243535529, 'sadness': 6.484764583313741, 'warmth': 6.181072632069309, 'sexual': 6.057177758970816, 'fun': 5.851961825094404, 'rural': 5.847125945585693, 'eating': 5.799749380752652, 'independence': 5.738611081911617, 'shame': 5.724456254037285, 'cold': 5.696464830384747, 'religion': 5.649038623786271, 'play': 5.590863948385332, 'appearance': 5.5877438769848125, 'feminine': 5.494363552895314, 'fashion': 5.432543960535186, 'dance': 5.24662598436769, 'beach': 5.246247928472182, 'cooking': 5.180920206322962, 'divine': 5.173035160716964, 'youth': 5.123579679205583, 'furniture': 5.043768482692552, 'sailing': 4.929591542454984, 'philosophy': 4.8996277069134635, 'legend': 4.695164345506572, 'sleep': 4.566606798362843, 'ocean': 4.566037610102033, 'fire': 4.513699075325415, 'emotional': 4.5014901421319795, 'water': 4.499700468198842, 'fear': 4.48178732550354, 'masculine': 4.470757456051917, 'torment': 4.383984280591104, 'royalty': 4.368404881572251, 'noise': 4.342545470162535, 'pride': 4.313478259670595, 'deception': 4.187675327940303, 'affection': 4.160416709408665, 'beauty': 4.110800197552475, 'hate': 4.099728503064337, 'nervousness': 3.897675834565192, 'cleaning': 3.827904482471778, 'ship': 3.827720632797441, 'hiking': 3.6713454409378836, 'confusion': 3.667598580508193, 'liquid': 3.5949232856439766, 'toy': 3.590900934954343, 'hipster': 3.560326856194498, 'exercise': 3.537407800135367, 'childish': 3.4244798209731466, 'magic': 3.3076678621873326, 'disappointment': 3.2887356656504463, 'animal': 3.2784404731303742, 'worship': 3.199084270672042, 'plant': 3.1940044619323404, 'sound': 3.1890084073515217, 'weakness': 3.1559384588138233, 'ancient': 3.151660232317072, 'alcohol': 3.145812901472328, 'tool': 3.124822113068391, 'night': 3.0900913053954335, 'rage': 2.9419323290151027, 'horror': 2.9190617797646317, 'surprise': 2.8347303876566126, 'dominant_personality': 2.811690922475155, 'contentment': 2.76015983333313, 'blue_collar_job': 2.7238047036936357, 'swimming': 2.6385676203426125, 'fabric': 2.6384995567036698, 'hygiene': 2.5460321217328725, 'lust': 2.489186441472068, 'anger': 2.3788338792988073, 'sympathy': 2.3217475796962654, 'zest': 2.1287919983906973, 'neglect': 2.089600839100883, 'exotic': 1.9949983133484979, 'joy': 1.9353811215588053, 'politeness': 1.848799516690099, 'disgust': 1.7940423837954123, 'monster': 1.7525510858766573, 'timidity': 1.7500848495999655, 'farming': 1.7305044569546377, 'anticipation': 1.6958401935509217, 'cheerfulness': 1.6028346296318472, 'pet': 1.4999683715162557, 'envy': 1.4482540791407887, 'smell': 1.390447221995543, 'irritability': 1.0071879943416069, 'superhero': 0.9879797749982407, 'anonymity': 0.9866962285461162, 'exasperation': 0.9159740649874304, 'ridicule': 0.8740918674393572, 'medieval': 0.8708339875684679, 'ugliness': 0.6205223299933202, 'swearing_terms': 0.5779210598859348}
AID {'business': 43.56922197351027, 'government': 36.886458114447, 'economics': 31.87855262729575, 'work': 29.240785367591688, 'money': 28.58200639209145, 'giving': 27.192476208568735, 'law': 26.38987483147518, 'help': 25.615626912516102, 'leader': 24.269268441979122, 'communication': 23.586954454561543, 'payment': 22.773856995748755, 'valuable': 22.69232368974326, 'banking': 22.55997886333286, 'college': 21.263980347765557, 'internet': 20.300075390312067, 'crime': 20.18001674398241, 'school': 18.92523697708976, 'meeting': 17.877785075252845, 'real_estate': 17.190712549915457, 'negative_emotion': 16.84796337140489, 'technology': 16.62294111884675, 'politics': 16.483960457165864, 'speaking': 16.040573931342198, 'wealthy': 15.689415497672552, 'messaging': 15.465649364494919, 'office': 15.418338440292963, 'dispute': 14.516113324021825, 'social_media': 13.676822815806826, 'gain': 13.378690796041244, 'celebration': 13.242698937610038, 'stealing': 13.179280974146323, 'party': 13.141207342257134, 'programming': 13.049229709095407, 'traveling': 12.763163173897372, 'war': 12.605577088226468, 'reading': 12.591442872188829, 'journalism': 12.417261081074038, 'computer': 12.373849951200723, 'writing': 12.086069001585736, 'fight': 11.972032524238125, 'vacation': 11.848277451279657, 'positive_emotion': 11.402587304697454, 'poor': 11.178969649982944, 'urban': 11.009598666421796, 'occupation': 11.001178146974528, 'wedding': 10.745395867373846, 'military': 10.649594141247775, 'violence': 10.399984454921059, 'healing': 10.321979462395607, 'children': 10.069020372227028, 'family': 10.02265007678257, 'strength': 9.986769084047129, 'weapon': 9.91258159435537, 'shopping': 9.902764264367697, 'power': 9.859257153719994, 'achievement': 9.78501135748307, 'phone': 9.598510091401257, 'white_collar_job': 9.596054881134638, 'health': 9.326541168241645, 'dominant_heirarchical': 9.272050447021773, 'aggression': 9.048528728236905, 'science': 9.028016417606445, 'trust': 9.024308551741962, 'injury': 8.82955547955552, 'medical_emergency': 8.724291039780935, 'competing': 8.669561997607625, 'movement': 8.574962465799898, 'home': 8.406595894828412, 'kill': 8.142993793319928, 'driving': 8.083599099356332, 'suffering': 7.973573882573399, 'friends': 7.9443682864862115, 'death': 7.873260138124386, 'prison': 7.725057506312332, 'sports': 7.71315376257757, 'shape_and_size': 7.658787887094198, 'vehicle': 7.530164979103293, 'air_travel': 7.319609780939121, 'order': 7.113649300626181, 'optimism': 7.028544360565042, 'hearing': 6.9389515235306956, 'domestic_work': 6.741226683700167, 'heroic': 6.6355653170726985, 'listen': 6.59783372608253, 'negotiate': 6.543962154165923, 'car': 6.4421977154809555, 'weather': 6.329029528436181, 'restaurant': 6.198562727366052, 'breaking': 6.022133341498096, 'terrorism': 6.009921667399123, 'pain': 5.956210456017875, 'tourism': 5.823719618538415, 'leisure': 5.708612988727844, 'beach': 5.3802882790800926, 'sadness': 5.20480700544911, 'water': 5.1844419433400795, 'eating': 5.160840499522309, 'warmth': 5.1392184442274225, 'music': 5.095496488392748, 'rural': 4.99307709862897, 'love': 4.925203173490271, 'morning': 4.625830371518128, 'liquid': 4.595326252491358, 'art': 4.540069131906139, 'cleaning': 4.4791791346070555, 'sailing': 4.46092815588152, 'cooking': 4.455892773503356, 'ocean': 4.389774654604684, 'body': 4.388364419255559, 'fire': 4.385195453359589, 'musical': 4.297872148094467, 'clothing': 4.26077046871529, 'shame': 4.205901293096545, 'independence': 4.134881153563464, 'attractive': 4.054306991998071, 'cold': 3.859879182366402, 'fun': 3.786499924936284, 'fashion': 3.69658490886893, 'religion': 3.657778169628506, 'noise': 3.6408389511997536, 'appearance': 3.632571952484353, 'play': 3.5365530241644745, 'philosophy': 3.4329540956855675, 'sexual': 3.3933346737704535, 'emotional': 3.3544895619043866, 'masculine': 3.31543379030875, 'hate': 3.279649066156726, 'legend': 3.2400798592520017, 'swimming': 3.234914020650775, 'youth': 3.158991835327252, 'fear': 3.1540029266278387, 'feminine': 3.0494533749516504, 'deception': 2.906396531877388, 'affection': 2.8866508867342717, 'torment': 2.794345012920329, 'disappointment': 2.7292253540929825, 'plant': 2.6941301449118793, 'pride': 2.693687380823352, 'animal': 2.6832089514255797, 'exercise': 2.6762652010462933, 'beauty': 2.6700560583506863, 'royalty': 2.6566359825439982, 'furniture': 2.648672259127222, 'nervousness': 2.5978337872978763, 'dance': 2.503999103835291, 'divine': 2.470268656091405, 'sleep': 2.4407076692213114, 'hiking': 2.4299996835756654, 'confusion': 2.40130086697858, 'weakness': 2.3682025582593647, 'ancient': 2.34362057061455, 'ship': 2.2865211415649207, 'childish': 2.2595851144252417, 'contentment': 2.244258104773861, 'hipster': 2.2021374045836644, 'toy': 2.175880686461546, 'rage': 2.170622568598339, 'fabric': 2.125042981076921, 'magic': 2.1172208764803706, 'horror': 2.1061192201816654, 'tool': 2.087627331740534, 'sound': 2.03457053500649, 'hygiene': 2.006213716164168, 'worship': 1.9929103240212585, 'alcohol': 1.9536664651910849, 'joy': 1.8283903939143509, 'anger': 1.7557526375841943, 'night': 1.731547325216602, 'sympathy': 1.6710313066931415, 'surprise': 1.6604560042537613, 'blue_collar_job': 1.6566930107710773, 'neglect': 1.654346199433408, 'lust': 1.6512717546585634, 'dominant_personality': 1.6005989791006203, 'farming': 1.5816120033477414, 'exotic': 1.5018679289854358, 'disgust': 1.450048256162449, 'zest': 1.3445932261232634, 'anticipation': 1.3030395801206645, 'timidity': 1.2747569242296608, 'pet': 1.272347550956075, 'politeness': 1.2128613608997183, 'monster': 1.1473000071611759, 'smell': 1.1266635114870047, 'envy': 1.1251823056195496, 'cheerfulness': 0.9881443650378018, 'ridicule': 0.73576579553854, 'anonymity': 0.6902103875796077, 'irritability': 0.6894970851981957, 'exasperation': 0.6173583229458091, 'superhero': 0.5420107379197949, 'swearing_terms': 0.4592590039647696, 'medieval': 0.35799819336541266, 'ugliness': 0.35477021581796614}
ASSAULT {'crime': 117.17664803298996, 'weapon': 82.64081456086923, 'negative_emotion': 77.19814622367505, 'business': 68.54229954839397, 'stealing': 65.24033600683352, 'government': 65.00715156799828, 'law': 60.22489254376037, 'communication': 58.16797094801574, 'war': 57.930915535303946, 'kill': 57.498171726570355, 'speaking': 54.70907379639533, 'work': 51.21912445646662, 'leader': 50.523187011930865, 'fight': 49.64956685140433, 'dispute': 48.16198674506684, 'aggression': 45.45605328028855, 'violence': 43.184848120082535, 'death': 42.837608022707165, 'party': 42.49889538238316, 'children': 42.08012295035064, 'internet': 39.9197921580396, 'suffering': 39.28286542868092, 'celebration': 39.19451181235998, 'driving': 39.14443379755869, 'family': 38.164832493264264, 'meeting': 36.55285858646544, 'vehicle': 35.7211487940404, 'prison': 35.508142221396156, 'vacation': 35.08972990773813, 'giving': 34.962641895695846, 'politics': 34.590403393290366, 'social_media': 34.3368466569202, 'college': 34.28476336196668, 'traveling': 34.26902985980556, 'messaging': 33.1373692992643, 'help': 32.94554108204015, 'school': 32.43335548688453, 'office': 32.218688226126645, 'real_estate': 32.11744258614878, 'wedding': 31.88092479008299, 'home': 31.49617602805455, 'urban': 30.94914996514275, 'car': 30.863554345358093, 'reading': 30.483878403461603, 'pain': 30.284759290525603, 'positive_emotion': 29.974721108366708, 'injury': 29.79737596949311, 'economics': 29.58922864789497, 'occupation': 29.387438039141806, 'writing': 28.399627987560578, 'money': 27.457781617735407, 'power': 26.94787067021495, 'phone': 26.799225052223328, 'terrorism': 26.364901693103384, 'military': 26.220549196321542, 'white_collar_job': 25.96742974762618, 'journalism': 25.21663617148653, 'strength': 24.5981370601947, 'listen': 24.535401170526224, 'technology': 24.410379225053155, 'valuable': 24.089137578241118, 'friends': 23.53937810378245, 'payment': 23.231713355731433, 'medical_emergency': 22.71034016435719, 'banking': 22.565102707355535, 'healing': 22.240344482583808, 'hearing': 22.14866885030204, 'sadness': 21.839087296966646, 'movement': 21.244686548885625, 'sports': 21.139452452624926, 'trust': 21.092958752837056, 'computer': 20.86741766501788, 'domestic_work': 20.74625941063074, 'programming': 20.463090968023586, 'achievement': 19.034979326519565, 'competing': 18.99301452179502, 'dominant_heirarchical': 18.93545437592861, 'order': 18.93495150053964, 'air_travel': 18.849244332368148, 'sexual': 18.446825622926035, 'health': 18.278145169253282, 'shape_and_size': 18.120559480563287, 'leisure': 17.348193932170926, 'alcohol': 17.31618742150556, 'shame': 17.024705499899575, 'torment': 16.83849544419331, 'warmth': 16.812700727517466, 'fire': 16.787786366780455, 'masculine': 16.665122921496657, 'breaking': 16.28469111413974, 'body': 16.173436174193373, 'musical': 16.10021893798166, 'shopping': 15.87586757836424, 'hate': 15.705670770756523, 'music': 15.167070444158867, 'tourism': 14.774911821505329, 'heroic': 14.678599837451953, 'optimism': 14.64002624993901, 'gain': 14.415976282904843, 'weather': 14.381321402726162, 'morning': 14.322093707032774, 'fear': 14.280680969932783, 'youth': 14.183549858957283, 'clothing': 14.105290587843134, 'love': 13.98883983666067, 'horror': 13.651146414972361, 'wealthy': 13.163463854661561, 'appearance': 12.908542980767395, 'weakness': 12.8411496523342, 'rage': 12.490710861921107, 'feminine': 12.250406590379812, 'cold': 12.08634483007364, 'religion': 11.804470093623056, 'fun': 11.683903782664656, 'attractive': 11.604550989379629, 'emotional': 11.593867263648628, 'nervousness': 11.465053885480119, 'science': 11.38684266461433, 'noise': 11.323166295827939, 'play': 10.870133964329966, 'restaurant': 10.80749275217289, 'disappointment': 10.547011524939386, 'art': 10.172140356421039, 'poor': 10.15928819024124, 'deception': 10.114467440405102, 'negotiate': 10.077759995888774, 'rural': 9.60755324168199, 'sleep': 9.593507833236085, 'divine': 9.159718054490988, 'sound': 8.830546252913447, 'beach': 8.82275823308739, 'hiking': 8.802878979147765, 'surprise': 8.784786503263218, 'confusion': 8.759287749926706, 'royalty': 8.732643252340104, 'childish': 8.701628970551809, 'ocean': 8.675897467596098, 'philosophy': 8.559565517174915, 'sailing': 8.33829201671661, 'dance': 8.236877271214302, 'cleaning': 8.152732541420447, 'water': 8.057532905503503, 'fashion': 7.948881010921944, 'independence': 7.936886567004585, 'affection': 7.7296741310576405, 'animal': 7.725889811322306, 'night': 7.591216999453989, 'legend': 7.376027440689329, 'liquid': 7.316317890646086, 'anger': 7.307280522746086, 'eating': 7.227208901446986, 'beauty': 7.103226463976476, 'toy': 6.7652688725175985, 'furniture': 6.5984802704091035, 'ancient': 6.487652368861417, 'hipster': 6.445121233775422, 'sympathy': 6.41311731127645, 'worship': 6.380501349305542, 'pride': 6.264094552159115, 'cooking': 6.002843706061176, 'monster': 5.972087650408534, 'lust': 5.791691958852957, 'exercise': 5.733616724110628, 'disgust': 5.724384667838987, 'plant': 5.511536529426784, 'swimming': 5.383594845231173, 'envy': 5.364854409244901, 'fabric': 5.276625570518241, 'ship': 5.173368877058881, 'contentment': 5.035766665977243, 'tool': 5.025808181343041, 'neglect': 4.968462171482009, 'timidity': 4.895375771844131, 'hygiene': 4.434768026757926, 'magic': 4.254995546785174, 'blue_collar_job': 3.6293137696787836, 'dominant_personality': 3.2871182240522256, 'irritability': 3.241996503636015, 'exotic': 3.240757718814773, 'joy': 3.2053476499872056, 'zest': 3.06924414957294, 'smell': 3.0678873197517413, 'cheerfulness': 2.9256165324199763, 'politeness': 2.756263977535131, 'pet': 2.5917742767847574, 'superhero': 2.586133905614997, 'farming': 2.5121134950675894, 'exasperation': 2.383045803874047, 'anticipation': 2.3698386312654502, 'anonymity': 2.338796470303062, 'ridicule': 2.2133498259853677, 'swearing_terms': 1.78919923465272, 'ugliness': 1.5338168207358591, 'medieval': 1.0709676184607666}

In [5]:
df = df.copy()

df_dedup = (
    df.drop_duplicates(
        subset=["title", "EventLabel"],
        keep="first"
    ))

In [6]:
df_dedup

,index,GlobalEventID,date,Year,Actor1Code,Actor1Name,Actor1CountryCode,Actor1EthnicCode,Actor2Code,Actor2Name,...,text,description,sbert_text_title,embedding_json_title,sbert_text,embedding_json,first_para,first_para_emb,PloverCode,EventLabel
0,0,1200203233,20240918,2024,USA,UNITED STATES,USA,NaN,CRM,GANG,...,MIAMI (AP) — Former federal agent Was Tabor sa...,The gang has exploded into the presidential ca...,Tren de Aragua gang started in Venezuela’s pri...,"[-0.002818030072376132, -0.01742059737443924, ...",NaN,NaN,MIAMI (AP) — Former federal agent Was Tabor sa...,"[-0.08164525777101517, -0.027655666694045067, ...",ASSAULT,ASSAULT
1,2,1200203284,20240925,2024,NaN,NaN,NaN,NaN,CHR,CHRISTIAN,...,NASHVILLE (BP) — The word “tumultuous” is one ...,NASHVILLE (BP) — The word “tumultuous” is one ...,"Yarnell: In times of competing allegiances, re...","[-0.0645490437746048, 0.05730828642845154, 0.0...",NaN,NaN,NASHVILLE (BP) — The word “tumultuous” is one ...,"[0.017953015863895416, -0.06336908042430878, -...",DEMAND,DEMAND
2,3,1200203520,20240925,2024,NaN,NaN,NaN,NaN,USA,FLORIDA,...,Yahoo is using AI to generate takeaways from t...,Weather experts are expecting Hurricane Helene...,How Strong Could Hurricane Helene Get When It ...,"[-0.018027156591415405, 0.024802444502711296, ...",NaN,NaN,Yahoo is using AI to generate takeaways from t...,"[-0.018082909286022186, 0.06462761014699936, -...",CONSULT,CONSULT
4,5,1200203590,20240925,2024,NaN,NaN,NaN,NaN,USA,FLORIDA,...,Yahoo is using AI to generate takeaways from t...,Since the non-endorsement by the national gove...,"Florida, Georgia Teamsters break with national...","[-0.049125298857688904, -0.03338903561234474, ...",NaN,NaN,Yahoo is using AI to generate takeaways from t...,"[-0.018082909286022186, 0.06462761014699936, -...",ASSAULT,ASSAULT
5,7,1200204067,20240925,2024,CRM,GANG,NaN,NaN,USA,UNITED STATES,...,MIAMI (AP) — Former federal agent Was Tabor sa...,The gang has exploded into the presidential ca...,Tren de Aragua gang started in Venezuela’s pri...,"[-0.002818030072376132, -0.01742059737443924, ...",NaN,NaN,MIAMI (AP) — Former federal agent Was Tabor sa...,"[-0.08164525777101517, -0.027655666694045067, ...",REJECT,REJECT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89982,122970,679730864,20170808,2017,USA,UNITED STATES,USA,NaN,GOV,PRESIDENT,...,President Donald Trump promised an America-Fir...,President Donald Trump promised an America-Fir...,"Trump, Cooper hold strong positions on Atlanti...","[0.001870636478997767, -0.035346224904060364, ...",NaN,NaN,President Donald Trump promised an America-Fir...,"[-0.07812009751796722, 0.0563594251871109, 0.0...",DISAPPROVE,DISAPPROVE
89985,122973,679732457,20170808,2017,EDU,SCHOOL,NaN,NaN,NaN,NaN,...,President Donald Trump was briefed today about...,President Donald Trump was briefed today about...,WVU Providing Multi-Pronged Approach Solving t...,"[0.015047898516058922, -0.004980273544788361, ...",NaN,NaN,President Donald Trump was briefed today about...,"[0.0483584962785244, -0.012323571369051933, 0....",COOPERATE,COOPERATE
89986,122975,679733002,20170808,2017,MED,BLOGGER,NaN,NaN,BUS,INDUSTRY,...,Who's the Guru? It's you – local voters in the...,NaN,Loudoun County to host 2018 beer bloggers conf...,"[0.020191552117466927, -0.014680474996566772, ...",NaN,NaN,Who's the Guru? It's you – local voters in the...,"[0.028580108657479286, -0.04236813634634018, 0...",CONSULT,CONSULT
89987,122977,679733469,20170808,2017,USA,UNITED STATES,USA,NaN,NaN,NaN,...,Ed Gillespie and Ralph Northam say they will d...,Too many of Virginia's schools are in dire shape.,Opinion | Bricks and mortar may be key in the ...,"[0.03240766003727913, 0.12859293818473816, 0.0...",NaN,NaN,Ed Gillespie and Ralph Northam say they will d...,"[-0.003782308427616954, 0.0422658771276474, 0....",RETREAT,RETREAT
89988,122978,679733481,20170808,2017,USA,IOWA,USA,NaN,NaN,NaN,...,The State of Iowa has issued an advisory bulle...,The State of Iowa has issued an advisory bulle...,Iowa Warns About Use of Copper Mugs with Alcoh...,"[-0.03137285262346268, 0.05549786612391472, 0....",NaN,NaN,The State of Iowa has issued an advisory bulle...,"[-0.045085739344358444, 0.03218259662389755, 0...",THREATHEN,THREATHEN

In [7]:
df_ec = df.copy()

df_ec["event_label_concat"] = (
    df_ec.groupby("title")["EventLabel"]
      .transform(lambda x: "_".join(sorted(set(x.astype(str)))))
)

In [8]:
df_final = (
    df_ec.drop_duplicates(subset=["title"])
      .reset_index(drop=True)
)

In [9]:
df_final

,index,GlobalEventID,date,Year,Actor1Code,Actor1Name,Actor1CountryCode,Actor1EthnicCode,Actor2Code,Actor2Name,...,description,sbert_text_title,embedding_json_title,sbert_text,embedding_json,first_para,first_para_emb,PloverCode,EventLabel,event_label_concat
0,0,1200203233,20240918,2024,USA,UNITED STATES,USA,NaN,CRM,GANG,...,The gang has exploded into the presidential ca...,Tren de Aragua gang started in Venezuela’s pri...,"[-0.002818030072376132, -0.01742059737443924, ...",NaN,NaN,MIAMI (AP) — Former federal agent Was Tabor sa...,"[-0.08164525777101517, -0.027655666694045067, ...",ASSAULT,ASSAULT,ASSAULT_COERCE_REJECT
1,2,1200203284,20240925,2024,NaN,NaN,NaN,NaN,CHR,CHRISTIAN,...,NASHVILLE (BP) — The word “tumultuous” is one ...,"Yarnell: In times of competing allegiances, re...","[-0.0645490437746048, 0.05730828642845154, 0.0...",NaN,NaN,NASHVILLE (BP) — The word “tumultuous” is one ...,"[0.017953015863895416, -0.06336908042430878, -...",DEMAND,DEMAND,DEMAND
2,3,1200203520,20240925,2024,NaN,NaN,NaN,NaN,USA,FLORIDA,...,Weather experts are expecting Hurricane Helene...,How Strong Could Hurricane Helene Get When It ...,"[-0.018027156591415405, 0.024802444502711296, ...",NaN,NaN,Yahoo is using AI to generate takeaways from t...,"[-0.018082909286022186, 0.06462761014699936, -...",CONSULT,CONSULT,AGREE_CONSULT
3,5,1200203590,20240925,2024,NaN,NaN,NaN,NaN,USA,FLORIDA,...,Since the non-endorsement by the national gove...,"Florida, Georgia Teamsters break with national...","[-0.049125298857688904, -0.03338903561234474, ...",NaN,NaN,Yahoo is using AI to generate takeaways from t...,"[-0.018082909286022186, 0.06462761014699936, -...",ASSAULT,ASSAULT,ASSAULT_SUPPORT_THREATHEN
4,9,1200204213,20240925,2024,EDU,STUDENT,NaN,NaN,NaN,NaN,...,Read how members of the university community r...,A day to remember: FIU celebrates Top 50,"[0.021655291318893433, -0.011736852116882801, ...",NaN,NaN,The university that never stops has experience...,"[0.07788405567407608, -0.07917836308479309, 0....",CONSULT,CONSULT,CONSULT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37908,122970,679730864,20170808,2017,USA,UNITED STATES,USA,NaN,GOV,PRESIDENT,...,President Donald Trump promised an America-Fir...,"Trump, Cooper hold strong positions on Atlanti...","[0.001870636478997767, -0.035346224904060364, ...",NaN,NaN,President Donald Trump promised an America-Fir...,"[-0.07812009751796722, 0.0563594251871109, 0.0...",DISAPPROVE,DISAPPROVE,DISAPPROVE
37909,122973,679732457,20170808,2017,EDU,SCHOOL,NaN,NaN,NaN,NaN,...,President Donald Trump was briefed today about...,WVU Providing Multi-Pronged Approach Solving t...,"[0.015047898516058922, -0.004980273544788361, ...",NaN,NaN,President Donald Trump was briefed today about...,"[0.0483584962785244, -0.012323571369051933, 0....",COOPERATE,COOPERATE,COOPERATE
37910,122975,679733002,20170808,2017,MED,BLOGGER,NaN,NaN,BUS,INDUSTRY,...,NaN,Loudoun County to host 2018 beer bloggers conf...,"[0.020191552117466927, -0.014680474996566772, ...",NaN,NaN,Who's the Guru? It's you – local voters in the...,"[0.028580108657479286, -0.04236813634634018, 0...",CONSULT,CONSULT,CONSULT
37911,122977,679733469,20170808,2017,USA,UNITED STATES,USA,NaN,NaN,NaN,...,Too many of Virginia's schools are in dire shape.,Opinion | Bricks and mortar may be key in the ...,"[0.03240766003727913, 0.12859293818473816, 0.0...",NaN,NaN,Ed Gillespie and Ralph Northam say they will d...,"[-0.003782308427616954, 0.0422658771276474, 0....",RETREAT,RETREAT,RETREAT
37912,122978,679733481,20170808,2017,USA,IOWA,USA,NaN,NaN,NaN,...,The State of Iowa has issued an advisory bulle...,Iowa Warns About Use of Copper Mugs with Alcoh...,"[-0.03137285262346268, 0.05549786612391472, 0....",NaN,NaN,The State of Iowa has issued an advisory bulle...,"[-0.045085739344358444, 0.03218259662389755, 0...",THREATHEN,THREATHEN,THREATHEN

In [10]:
df_multiple_codes = df_final[
    df_final["event_label_concat"].str.contains("_")  # fallback heuristic
]

In [11]:
df_multiple_codes

,index,GlobalEventID,date,Year,Actor1Code,Actor1Name,Actor1CountryCode,Actor1EthnicCode,Actor2Code,Actor2Name,...,description,sbert_text_title,embedding_json_title,sbert_text,embedding_json,first_para,first_para_emb,PloverCode,EventLabel,event_label_concat
0,0,1200203233,20240918,2024,USA,UNITED STATES,USA,NaN,CRM,GANG,...,The gang has exploded into the presidential ca...,Tren de Aragua gang started in Venezuela’s pri...,"[-0.002818030072376132, -0.01742059737443924, ...",NaN,NaN,MIAMI (AP) — Former federal agent Was Tabor sa...,"[-0.08164525777101517, -0.027655666694045067, ...",ASSAULT,ASSAULT,ASSAULT_COERCE_REJECT
2,3,1200203520,20240925,2024,NaN,NaN,NaN,NaN,USA,FLORIDA,...,Weather experts are expecting Hurricane Helene...,How Strong Could Hurricane Helene Get When It ...,"[-0.018027156591415405, 0.024802444502711296, ...",NaN,NaN,Yahoo is using AI to generate takeaways from t...,"[-0.018082909286022186, 0.06462761014699936, -...",CONSULT,CONSULT,AGREE_CONSULT
3,5,1200203590,20240925,2024,NaN,NaN,NaN,NaN,USA,FLORIDA,...,Since the non-endorsement by the national gove...,"Florida, Georgia Teamsters break with national...","[-0.049125298857688904, -0.03338903561234474, ...",NaN,NaN,Yahoo is using AI to generate takeaways from t...,"[-0.018082909286022186, 0.06462761014699936, -...",ASSAULT,ASSAULT,ASSAULT_SUPPORT_THREATHEN
7,19,1200205864,20240925,2024,USA,CHARLOTTE,USA,NaN,NaN,NaN,...,"One county warned that the storm, which is exp...",Tropical Storm Helene evacuation map as storm ...,"[0.0638221725821495, 0.08435751497745514, 0.04...",NaN,NaN,Several Florida counties have issued mandatory...,"[0.030011611059308052, -0.024009326472878456, ...",SANCTION,SANCTION,SANCTION_SUPPORT
8,20,1200205887,20240925,2024,USA,UNITED STATES,USA,NaN,NaN,NaN,...,"Ryan Routh, the suspect in the second Trump as...",Ryan Routh charged with attempted assassinatio...,"[-0.03664088249206543, 0.05994853749871254, -0...",NaN,NaN,"Ryan Routh, the suspect in the second Trump as...","[-0.008147599175572395, 0.021718882024288177, ...",ASSAULT,ASSAULT,ASSAULT_COERCE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37861,122823,679656651,20170808,2017,MIL,MILITARY BASE,NaN,NaN,NaN,NaN,...,The armed forces are concerned about more than...,Here's Why the U.S. Military is Scared of Drones,"[0.07015137374401093, 0.012341306544840336, 0....",NaN,NaN,"Among the dangers faced by the U.S. military, ...","[0.10064809769392014, -0.015102533623576164, -...",ASSAULT,ASSAULT,ASSAULT_CONSULT
37880,122877,679687790,20170808,2017,USACVL,UNITED STATES,USA,NaN,NaN,NaN,...,Can a Republican win there?,Opinion | The GOP’s challenge in Virginia,"[-0.0002878196828532964, 0.03428173065185547, ...",NaN,NaN,In the latest poll in Virginia’s gubernatorial...,"[0.06598247587680817, -0.015836024656891823, -...",DISAPPROVE,DISAPPROVE,DISAPPROVE_REJECT
37885,122887,679695385,20170808,2017,USA,VIRGINIA,USA,NaN,BUS,BUSINESS,...,"Draftco Inc., a machine and fabrication shop, ...","Draftco Inc. to invest $450,000, create 16 new...","[-0.013736411929130554, -0.023327047005295753,...",NaN,NaN,"Draftco Inc., a machine and fabrication shop, ...","[-0.03974677994847298, 0.006161803845316172, -...",SUPPORT,SUPPORT,AID_SUPPORT
37891,122902,679700492,20170808,2017,NaN,NaN,NaN,NaN,MIL,ARMY,...,NaN,Defense Systems,"[-0.04630216211080551, 0.04322230815887451, -0...",NaN,NaN,"News, analysis, and ideas driving the future o...","[-0.0165393128991127, -0.028577638790011406, -...",CONSULT,CONSULT,ASSAULT_CONSULT_COOPERATE
37895,122917,679703921,20170808,2017,NaN,NaN,NaN,NaN,USA,UNITED STATES,...,The US Army has refused a call by several Cong...,Brooklyn streets will keep names of Confederat...,"[-0.0540521964430809, -0.005775600206106901, -...",NaN,NaN,The US Army has refused a call by several Cong...,"[-0.07827053964138031, 0.08962520956993103, -0...",ASSAULT,ASSAULT,ASSAULT_CONCEDE_CONSULT_DISAPPROVE

In [23]:
cat_labels = df_multiple_codes["event_label_concat"].tolist()

In [13]:
cat_labels.sort()

In [43]:
len(df)

89989

In [24]:
count_cat_labels = Counter(cat_labels).most_common()

In [25]:
count_cat_labels

[('ASSAULT_CONSULT', 485),
 ('CONSULT_SUPPORT', 394),
 ('CONSULT_DISAPPROVE', 393),
 ('ASSAULT_DISAPPROVE', 378),
 ('AGREE_CONSULT', 334),
 ('ASSAULT_COERCE', 255),
 ('COERCE_DISAPPROVE', 248),
 ('DISAPPROVE_SUPPORT', 232),
 ('COERCE_CONSULT', 185),
 ('AID_CONSULT', 181),
 ('ASSAULT_SUPPORT', 174),
 ('CONSULT_REJECT', 137),
 ('AGREE_SUPPORT', 132),
 ('DISAPPROVE_REJECT', 123),
 ('AID_DISAPPROVE', 114),
 ('AID_SUPPORT', 111),
 ('AGREE_DISAPPROVE', 110),
 ('COERCE_SUPPORT', 102),
 ('CONSULT_COOPERATE', 101),
 ('AGREE_AID', 97),
 ('AGREE_ASSAULT', 90),
 ('CONCEDE_CONSULT', 88),
 ('CONSULT_RETREAT', 84),
 ('AID_ASSAULT', 80),
 ('CONSULT_THREATHEN', 78),
 ('ASSAULT_REJECT', 77),
 ('CONCEDE_DISAPPROVE', 77),
 ('REJECT_SUPPORT', 76),
 ('COERCE_REJECT', 74),
 ('ASSAULT_THREATHEN', 71),
 ('ASSAULT_CONSULT_DISAPPROVE', 70),
 ('DISAPPROVE_THREATHEN', 68),
 ('ASSAULT_RETREAT', 66),
 ('ASSAULT_COOPERATE', 66),
 ('COERCE_RETREAT', 61),
 ('COERCE_PROTEST', 61),
 ('CONSULT_DEMAND', 59),
 ('ASSAULT_CONCEDE', 57),
 ('AID_COERCE', 57),
 ('RETREAT_SUPPORT', 56),
 ('DISAPPROVE_RETREAT', 56),
 ('AGREE_COERCE', 55),
 ('COERCE_CONCEDE', 54),
 ('CONSULT_PROTEST', 53),
 ('AID_COOPERATE', 52),
 ('DISAPPROVE_PROTEST', 52),
 ('COERCE_THREATHEN', 48),
 ('AGREE_REJECT', 48),
 ('ASSAULT_COERCE_DISAPPROVE', 48),
 ('CONSULT_DISAPPROVE_SUPPORT', 47),
 ('COOPERATE_DISAPPROVE', 47),
 ('COOPERATE_SUPPORT', 47),
 ('ASSAULT_CONSULT_SUPPORT', 47),
 ('CONCEDE_SUPPORT', 44),
 ('ASSAULT_COERCE_CONSULT', 44),
 ('DEMAND_DISAPPROVE', 43),
 ('AGREE_CONSULT_SUPPORT', 42),
 ('CONSULT_SANCTION', 41),
 ('ASSAULT_PROTEST', 41),
 ('ASSAULT_DEMAND', 39),
 ('SUPPORT_THREATHEN', 39),
 ('AGREE_CONCEDE', 38),
 ('ASSAULT_DISAPPROVE_SUPPORT', 37),
 ('COERCE_COOPERATE', 35),
 ('AGREE_COOPERATE', 35),
 ('COERCE_DEMAND', 31),
 ('DEMAND_SUPPORT', 31),
 ('COERCE_CONSULT_DISAPPROVE', 29),
 ('DISAPPROVE_SANCTION', 29),
 ('AID_REJECT', 28),
 ('CONSULT_DISAPPROVE_REJECT', 28),
 ('CONCEDE_RETREAT', 28),
 ('AGREE_RETREAT', 28),
 ('AGREE_CONSULT_DISAPPROVE', 27),
 ('AID_RETREAT', 25),
 ('AGREE_AID_CONSULT', 25),
 ('AID_THREATHEN', 24),
 ('COERCE_CONSULT_SUPPORT', 24),
 ('AID_CONSULT_SUPPORT', 23),
 ('AID_CONCEDE', 23),
 ('PROTEST_SUPPORT', 22),
 ('COERCE_SANCTION', 22),
 ('COOPERATE_REJECT', 22),
 ('AID_ASSAULT_CONSULT', 21),
 ('COERCE_DISAPPROVE_SUPPORT', 21),
 ('AGREE_ASSAULT_CONSULT', 20),
 ('CONSULT_DEMAND_DISAPPROVE', 20),
 ('REJECT_RETREAT', 20),
 ('ASSAULT_SANCTION', 20),
 ('ASSAULT_DISAPPROVE_REJECT', 19),
 ('AGREE_DEMAND', 19),
 ('CONSULT_REJECT_SUPPORT', 19),
 ('PROTEST_REJECT', 19),
 ('AID_DISAPPROVE_SUPPORT', 18),
 ('AID_CONSULT_DISAPPROVE', 18),
 ('AGREE_CONSULT_REJECT', 17),
 ('AGREE_SANCTION', 17),
 ('REJECT_THREATHEN', 17),
 ('ASSAULT_COERCE_CONCEDE', 17),
 ('SANCTION_SUPPORT', 16),
 ('AID_DEMAND', 16),
 ('ASSAULT_CONSULT_DISAPPROVE_SUPPORT', 16),
 ('COOPERATE_RETREAT', 16),
 ('AGREE_DISAPPROVE_SUPPORT', 16),
 ('COERCE_CONCEDE_DISAPPROVE', 16),
 ('AID_ASSAULT_DISAPPROVE', 15),
 ('COERCE_DISAPPROVE_REJECT', 15),
 ('AGREE_COERCE_CONSULT', 15),
 ('CONCEDE_REJECT', 15),
 ('AGREE_THREATHEN', 15),
 ('DISAPPROVE_SUPPORT_THREATHEN', 15),
 ('ASSAULT_COERCE_REJECT', 14),
 ('DISAPPROVE_REJECT_SUPPORT', 14),
 ('AID_ASSAULT_SUPPORT', 14),
 ('DEMAND_REJECT', 14),
 ('ASSAULT_COERCE_SUPPORT', 13),
 ('CONCEDE_COOPERATE', 13),
 ('ASSAULT_MOBILIZE', 13),
 ('CONCEDE_DEMAND', 13),
 ('AGREE_AID_SUPPORT', 12),
 ('RETREAT_THREATHEN', 12),
 ('DISAPPROVE_RETREAT_SUPPORT', 12),
 ('AID_CONSULT_COOPERATE', 12),
 ('CONSULT_MOBILIZE', 12),
 ('AID_COERCE_CONSULT', 12),
 ('AGREE_CONSULT_COOPERATE', 12),
 ('AGREE_PROTEST', 12),
 ('ASSAULT_CONSULT_DEMAND', 12),
 ('DEMAND_THREATHEN', 11),
 ('COERCE_CONCEDE_CONSULT', 11),
 ('ASSAULT_CONCEDE_CONSULT', 11),
 ('AGREE_ASSAULT_DISAPPROVE', 11),
 ('ASSAULT_COERCE_RETREAT', 11),
 ('CONCEDE_THREATHEN', 11),
 ('ASSAULT_COERCE_CONSULT_DISAPPROVE', 11),
 ('PROTEST_THREATHEN', 11),
 ('COERCE_DISAPPROVE_THREATHEN', 10),
 ('ASSAULT_CONSULT_COOPERATE', 10),
 ('CONSULT_DISAPPROVE_RETREAT', 10),
 ('ASSAULT_COERCE_THREATHEN', 10),
 ('CONCEDE_CONSULT_DISAPPROVE', 10),
 ('AID_COERCE_DISAPPROVE', 10),
 ('CONCEDE_CONSULT_SUPPORT', 10),
 ('AGREE_ASSAULT_SUPPORT', 10),
 ('ASSAULT_DEMAND_DISAPPROVE', 10),
 ('CONSULT_DISAPPROVE_PROTEST', 10),
 ('AGREE_AID_CONSULT_SUPPORT', 10),
 ('ASSAULT_CONSULT_RETREAT', 10),
 ('CONCEDE_DISAPPROVE_SUPPORT', 10),
 ('AID_PROTEST', 10),
 ('COERCE_CONSULT_COOPERATE', 9),
 ('AGREE_CONSULT_DEMAND', 9),
 ('ASSAULT_CONSULT_THREATHEN', 9),
 ('COERCE_CONSULT_RETREAT', 9),
 ('AGREE_MOBILIZE', 9),
 ('AGREE_REJECT_SUPPORT', 9),
 ('AID_SANCTION', 9),
 ('ASSAULT_COOPERATE_DISAPPROVE', 9),
 ('AGREE_COERCE_DISAPPROVE', 9),
 ('COERCE_DEMAND_DISAPPROVE', 9),
 ('ASSAULT_DISAPPROVE_RETREAT', 9),
 ('ASSAULT_DISAPPROVE_PROTEST', 9),
 ('AID_MOBILIZE', 9),
 ('ASSAULT_CONSULT_REJECT', 8),
 ('CONSULT_DISAPPROVE_THREATHEN', 8),
 ('COOPERATE_SANCTION', 8),
 ('ASSAULT_DISAPPROVE_THREATHEN', 8),
 ('AGREE_COERCE_CONSULT_DISAPPROVE', 8),
 ('COERCE_CONSULT_PROTEST', 8),
 ('COOPERATE_DISAPPROVE_SUPPORT', 8),
 ('PROTEST_SANCTION', 8),
 ('ASSAULT_CONSULT_PROTEST', 8),
 ('COERCE_CONSULT_THREATHEN', 8),
 ('AGREE_DISAPPROVE_REJECT', 8),
 ('ASSAULT_COERCE_PROTEST', 8),
 ('DEMAND_RETREAT', 8),
 ('AGREE_AID_CONSULT_DISAPPROVE', 8),
 ('MOBILIZE_THREATHEN', 7),
 ('AID_CONCEDE_CONSULT', 7),
 ('ASSAULT_COERCE_SANCTION', 7),
 ('AID_ASSAULT_COOPERATE', 7),
 ('REJECT_SANCTION', 7),
 ('ASSAULT_COERCE_DISAPPROVE_SUPPORT', 7),
 ('COOPERATE_DEMAND', 7),
 ('COERCE_DISAPPROVE_SANCTION', 7),
 ('AID_DISAPPROVE_REJECT', 7),
 ('CONSULT_COOPERATE_SUPPORT', 7),
 ('ASSAULT_DISAPPROVE_REJECT_SUPPORT', 7),
 ('COERCE_CONSULT_DISAPPROVE_SUPPORT', 7),
 ('COERCE_CONCEDE_SUPPORT', 7),
 ('COERCE_DISAPPROVE_PROTEST', 7),
 ('COERCE_CONSULT_REJECT', 7),
 ('ASSAULT_CONCEDE_DISAPPROVE', 7),
 ('DEMAND_DISAPPROVE_SUPPORT', 7),
 ('ASSAULT_DEMAND_SUPPORT', 7),
 ('CONSULT_RETREAT_SUPPORT', 7),
 ('AGREE_CONCEDE_DISAPPROVE', 6),
 ('AGREE_COERCE_SUPPORT', 6),
 ('AID_ASSAULT_COERCE_DISAPPROVE', 6),
 ('AGREE_AID_ASSAULT', 6),
 ('AGREE_CONCEDE_CONSULT', 6),
 ('ASSAULT_REJECT_SUPPORT', 6),
 ('CONSULT_DISAPPROVE_SANCTION', 6),
 ('COERCE_CONSULT_DEMAND', 6),
 ('AGREE_CONSULT_SANCTION', 6),
 ('ASSAULT_RETREAT_SUPPORT', 6),
 ('CONSULT_SANCTION_SUPPORT', 6),
 ('DEMAND_SANCTION', 6),
 ('COERCE_CONCEDE_REJECT', 6),
 ('DEMAND_PROTEST', 6),
 ('AGREE_CONSULT_RETREAT_SUPPORT', 6),
 ('AGREE_CONSULT_RETREAT', 6),
 ('COERCE_MOBILIZE', 6),
 ('ASSAULT_CONSULT_DISAPPROVE_REJECT', 6),
 ('COOPERATE_THREATHEN', 6),
 ('COERCE_CONCEDE_THREATHEN', 6),
 ('COERCE_CONCEDE_PROTEST', 6),
 ('AID_COERCE_CONSULT_DISAPPROVE', 6),
 ('CONSULT_PROTEST_SUPPORT', 6),
 ('ASSAULT_COERCE_COOPERATE', 6),
 ('ASSAULT_COERCE_CONCEDE_DISAPPROVE', 5),
 ('ASSAULT_COERCE_CONSULT_SUPPORT', 5),
 ('COERCE_REJECT_RETREAT', 5),
 ('COOPERATE_MOBILIZE', 5),
 ('AID_COOPERATE_SUPPORT', 5),
 ('AID_CONSULT_REJECT', 5),
 ('COERCE_CONCEDE_DEMAND', 5),
 ('AID_ASSAULT_COERCE', 5),
 ('PROTEST_RETREAT', 5),
 ('AID_CONSULT_DISAPPROVE_SUPPORT', 5),
 ('AGREE_CONSULT_DISAPPROVE_SUPPORT', 5),
 ('AGREE_AID_ASSAULT_CONSULT', 5),
 ('AGREE_DISAPPROVE_RETREAT', 5),
 ('SANCTION_THREATHEN', 5),
 ('AID_DISAPPROVE_PROTEST', 5),
 ('AGREE_ASSAULT_CONSULT_SUPPORT', 5),
 ('CONSULT_REJECT_RETREAT', 5),
 ('AID_DISAPPROVE_THREATHEN', 5),
 ('AGREE_ASSAULT_CONCEDE', 5),
 ('AGREE_CONSULT_THREATHEN', 5),
 ('CONCEDE_PROTEST', 5),
 ('CONSULT_PROTEST_REJECT', 5),
 ('ASSAULT_DISAPPROVE_SANCTION', 5),
 ('DISAPPROVE_REJECT_THREATHEN', 5),
 ('ASSAULT_DISAPPROVE_SUPPORT_THREATHEN', 5),
 ('ASSAULT_CONSULT_COOPERATE_DISAPPROVE', 5),
 ('ASSAULT_SUPPORT_THREATHEN', 4),
 ('COERCE_DISAPPROVE_RETREAT', 4),
 ('AGREE_AID_COOPERATE', 4),
 ('MOBILIZE_SUPPORT', 4),
 ('AID_CONSULT_DEMAND', 4),
 ('ASSAULT_RETREAT_THREATHEN', 4),
 ('AGREE_DISAPPROVE_THREATHEN', 4),
 ('AID_REJECT_SUPPORT', 4),
 ('AID_ASSAULT_CONSULT_COOPERATE', 4),
 ('COERCE_RETREAT_SUPPORT', 4),
 ('ASSAULT_COERCE_DEMAND', 4),
 ('CONCEDE_DISAPPROVE_REJECT', 4),
 ('ASSAULT_CONCEDE_CONSULT_DISAPPROVE_SUPPORT', 4),
 ('AID_COERCE_DEMAND', 4),
 ('ASSAULT_CONSULT_SANCTION', 4),
 ('AGREE_AID_COERCE', 4),
 ('COERCE_CONCEDE_RETREAT', 4),
 ('DISAPPROVE_SANCTION_SUPPORT', 4),
 ('AGREE_CONCEDE_REJECT', 4),
 ('AGREE_AID_DISAPPROVE', 4),
 ('CONSULT_COOPERATE_DISAPPROVE', 4),
 ('CONSULT_DEMAND_REJECT', 4),
 ('CONCEDE_SUPPORT_THREATHEN', 4),
 ('RETREAT_SANCTION', 4),
 ('AID_CONSULT_RETREAT', 4),
 ('DISAPPROVE_MOBILIZE', 4),
 ('ASSAULT_COERCE_DEMAND_DISAPPROVE', 4),
 ('AID_RETREAT_SUPPORT', 4),
 ('MOBILIZE_PROTEST', 4),
 ('CONSULT_DEMAND_SUPPORT', 4),
 ('AID_CONSULT_SUPPORT_THREATHEN', 4),
 ('CONSULT_COOPERATE_REJECT', 4),
 ('COERCE_COOPERATE_DISAPPROVE', 4),
 ('COERCE_SANCTION_SUPPORT', 4),
 ('CONSULT_REJECT_THREATHEN', 4),
 ('CONSULT_RETREAT_THREATHEN', 4),
 ('ASSAULT_REJECT_RETREAT', 4),
 ('COERCE_COOPERATE_PROTEST', 4),
 ('DISAPPROVE_PROTEST_SUPPORT', 4),
 ('AGREE_ASSAULT_THREATHEN', 4),
 ('AID_SUPPORT_THREATHEN', 4),
 ('CONSULT_COOPERATE_DEMAND', 3),
 ('AID_COOPERATE_RETREAT', 3),
 ('CONSULT_DISAPPROVE_RETREAT_SUPPORT', 3),
 ('DISAPPROVE_RETREAT_SANCTION', 3),
 ('AID_ASSAULT_COERCE_CONSULT', 3),
 ('DISAPPROVE_RETREAT_SUPPORT_THREATHEN', 3),
 ('AGREE_ASSAULT_CONSULT_RETREAT_SUPPORT', 3),
 ('ASSAULT_COERCE_CONSULT_THREATHEN', 3),
 ('CONCEDE_DEMAND_DISAPPROVE', 3),
 ('COERCE_CONSULT_RETREAT_SUPPORT', 3),
 ('AGREE_COOPERATE_DISAPPROVE', 3),
 ('CONSULT_DEMAND_DISAPPROVE_SUPPORT', 3),
 ('AGREE_AID_SANCTION', 3),
 ('DISAPPROVE_REJECT_RETREAT', 3),
 ('AGREE_ASSAULT_COOPERATE', 3),
 ('AGREE_COOPERATE_SUPPORT', 3),
 ('AID_CONCEDE_REJECT', 3),
 ('ASSAULT_COERCE_CONSULT_RETREAT', 3),
 ('AID_COOPERATE_DISAPPROVE', 3),
 ('ASSAULT_PROTEST_REJECT', 3),
 ('AGREE_ASSAULT_CONSULT_DISAPPROVE_SUPPORT', 3),
 ('CONCEDE_SANCTION', 3),
 ('AGREE_CONCEDE_DISAPPROVE_SUPPORT', 3),
 ('CONCEDE_CONSULT_PROTEST', 3),
 ('ASSAULT_CONSULT_DISAPPROVE_SANCTION', 3),
 ('AGREE_CONCEDE_RETREAT', 3),
 ('AGREE_ASSAULT_CONSULT_RETREAT', 3),
 ('ASSAULT_COERCE_CONCEDE_CONSULT', 3),
 ('AGREE_COERCE_DISAPPROVE_SUPPORT', 3),
 ('CONCEDE_CONSULT_REJECT', 3),
 ('AGREE_COERCE_CONCEDE', 3),
 ('AGREE_AID_RETREAT', 3),
 ('ASSAULT_COERCE_CONSULT_DISAPPROVE_REJECT', 3),
 ('CONSULT_SUPPORT_THREATHEN', 3),
 ('COERCE_SUPPORT_THREATHEN', 3),
 ('ASSAULT_CONCEDE_DISAPPROVE_REJECT', 3),
 ('DISAPPROVE_REJECT_SANCTION', 3),
 ('CONSULT_MOBILIZE_SUPPORT', 3),
 ('CONSULT_PROTEST_THREATHEN', 3),
 ('CONCEDE_CONSULT_DEMAND', 3),
 ('ASSAULT_CONCEDE_RETREAT', 3),
 ('COERCE_CONSULT_DISAPPROVE_RETREAT', 3),
 ('COERCE_CONSULT_SANCTION', 3),
 ('CONCEDE_DISAPPROVE_REJECT_SUPPORT', 3),
 ('AGREE_COERCE_COOPERATE', 3),
 ('AID_ASSAULT_COERCE_SUPPORT', 3),
 ('AID_ASSAULT_DISAPPROVE_REJECT', 3),
 ('ASSAULT_CONCEDE_SUPPORT', 3),
 ('ASSAULT_CONCEDE_CONSULT_SUPPORT', 3),
 ('AGREE_AID_CONCEDE', 3),
 ('CONSULT_DISAPPROVE_REJECT_SUPPORT', 3),
 ('COERCE_PROTEST_THREATHEN', 3),
 ('AGREE_CONSULT_DISAPPROVE_RETREAT', 3),
 ('AGREE_SANCTION_SUPPORT', 3),
 ('CONCEDE_REJECT_SUPPORT', 3),
 ('AID_CONSULT_PROTEST', 3),
 ('AGREE_REJECT_RETREAT', 3),
 ('AID_CONCEDE_DISAPPROVE', 3),
 ('COERCE_REJECT_SUPPORT', 3),
 ('COOPERATE_PROTEST', 3),
 ('AID_DEMAND_SUPPORT', 3),
 ('REJECT_RETREAT_THREATHEN', 3),
 ('ASSAULT_CONCEDE_CONSULT_DISAPPROVE', 3),
 ('AID_CONSULT_COOPERATE_SUPPORT', 3),
 ('CONSULT_DEMAND_THREATHEN', 2),
 ('AID_CONSULT_DISAPPROVE_REJECT', 2),
 ('AID_CONSULT_MOBILIZE', 2),
 ('AID_ASSAULT_CONSULT_THREATHEN', 2),
 ('ASSAULT_DISAPPROVE_RETREAT_THREATHEN', 2),
 ('AID_ASSAULT_CONCEDE_DISAPPROVE', 2),
 ('AGREE_AID_REJECT_SUPPORT', 2),
 ('AID_DISAPPROVE_REJECT_SUPPORT', 2),
 ('AID_REJECT_THREATHEN', 2),
 ('COERCE_RETREAT_THREATHEN', 2),
 ('AGREE_COERCE_CONSULT_DISAPPROVE_REJECT', 2),
 ('AGREE_CONSULT_DISAPPROVE_REJECT', 2),
 ('ASSAULT_MOBILIZE_SUPPORT', 2),
 ('AGREE_ASSAULT_CONCEDE_CONSULT_DISAPPROVE', 2),
 ('ASSAULT_DEMAND_THREATHEN', 2),
 ('COERCE_CONSULT_REJECT_SUPPORT', 2),
 ('ASSAULT_COERCE_DISAPPROVE_RETREAT', 2),
 ('AGREE_DISAPPROVE_REJECT_SUPPORT', 2),
 ('AGREE_COOPERATE_RETREAT', 2),
 ('AID_CONSULT_THREATHEN', 2),
 ('REJECT_RETREAT_SANCTION', 2),
 ('AGREE_ASSAULT_COERCE', 2),
 ('CONCEDE_MOBILIZE', 2),
 ('COERCE_CONSULT_REJECT_RETREAT', 2),
 ('ASSAULT_COOPERATE_SUPPORT_THREATHEN', 2),
 ('AGREE_ASSAULT_CONSULT_DISAPPROVE', 2),
 ('AGREE_CONCEDE_COOPERATE', 2),
 ('ASSAULT_CONSULT_MOBILIZE', 2),
 ('AID_COERCE_REJECT', 2),
 ('COERCE_DEMAND_REJECT', 2),
 ('CONCEDE_DISAPPROVE_THREATHEN', 2),
 ('AID_ASSAULT_COERCE_CONCEDE_DEMAND_SUPPORT', 2),
 ('DEMAND_REJECT_RETREAT', 2),
 ('AGREE_COERCE_CONSULT_SUPPORT', 2),
 ('COOPERATE_MOBILIZE_SUPPORT', 2),
 ('CONCEDE_CONSULT_REJECT_SUPPORT', 2),
 ('REJECT_SUPPORT_THREATHEN', 2),
 ('AGREE_CONCEDE_SUPPORT', 2),
 ('ASSAULT_CONCEDE_REJECT', 2),
 ('CONCEDE_REJECT_RETREAT_SUPPORT', 2),
 ('AID_COERCE_COOPERATE', 2),
 ('AGREE_ASSAULT_DEMAND', 2),
 ('AID_COERCE_THREATHEN', 2),
 ('AID_ASSAULT_CONSULT_DISAPPROVE_THREATHEN', 2),
 ('AID_COERCE_SUPPORT', 2),
 ('AGREE_CONSULT_PROTEST_SUPPORT', 2),
 ('CONSULT_DISAPPROVE_SUPPORT_THREATHEN', 2),
 ('ASSAULT_COERCE_COOPERATE_THREATHEN', 2),
 ('COERCE_CONSULT_DISAPPROVE_REJECT_THREATHEN', 2),
 ('AID_DISAPPROVE_RETREAT', 2),
 ('COERCE_PROTEST_REJECT', 2),
 ('AID_ASSAULT_CONSULT_DISAPPROVE', 2),
 ('COERCE_PROTEST_SUPPORT', 2),
 ('AID_ASSAULT_DISAPPROVE_RETREAT', 2),
 ('AID_PROTEST_SUPPORT', 2),
 ('ASSAULT_CONCEDE_DISAPPROVE_SUPPORT', 2),
 ('COERCE_CONCEDE_CONSULT_DISAPPROVE_REJECT', 2),
 ('ASSAULT_CONSULT_DISAPPROVE_SUPPORT_THREATHEN', 2),
 ('CONCEDE_DISAPPROVE_RETREAT', 2),
 ('ASSAULT_CONCEDE_CONSULT_THREATHEN', 2),
 ('AGREE_COOPERATE_REJECT', 2),
 ('CONCEDE_CONSULT_DISAPPROVE_SUPPORT', 2),
 ('AGREE_DEMAND_DISAPPROVE', 2),
 ('AGREE_ASSAULT_RETREAT', 2),
 ('ASSAULT_DEMAND_REJECT_SUPPORT', 2),
 ('COERCE_DISAPPROVE_REJECT_RETREAT', 2),
 ('COERCE_CONSULT_COOPERATE_PROTEST', 2),
 ('ASSAULT_CONCEDE_MOBILIZE', 2),
 ('COERCE_DEMAND_RETREAT', 2),
 ('ASSAULT_COOPERATE_THREATHEN', 2),
 ('ASSAULT_CONSULT_DISAPPROVE_THREATHEN', 2),
 ('CONCEDE_DISAPPROVE_SANCTION', 2),
 ('AID_COERCE_DISAPPROVE_REJECT_SUPPORT', 2),
 ('CONCEDE_DISAPPROVE_RETREAT_SUPPORT', 2),
 ('ASSAULT_COERCE_DISAPPROVE_SANCTION', 2),
 ('AID_DEMAND_DISAPPROVE', 2),
 ('CONSULT_COOPERATE_PROTEST', 2),
 ('CONSULT_DEMAND_RETREAT', 2),
 ('AID_CONCEDE_RETREAT', 2),
 ('AGREE_DISAPPROVE_PROTEST_SUPPORT', 2),
 ('CONCEDE_CONSULT_SANCTION', 2),
 ('COOPERATE_DISAPPROVE_RETREAT', 2),
 ('ASSAULT_COERCE_DISAPPROVE_PROTEST', 2),
 ('AID_COOPERATE_DEMAND', 2),
 ('AGREE_COERCE_DEMAND_SUPPORT', 2),
 ('AGREE_ASSAULT_CONCEDE_CONSULT', 2),
 ('AID_COERCE_PROTEST', 2),
 ('DEMAND_REJECT_SUPPORT', 2),
 ('CONCEDE_REJECT_THREATHEN', 2),
 ('COERCE_COOPERATE_DISAPPROVE_REJECT', 2),
 ('AGREE_DEMAND_REJECT', 2),
 ('COERCE_CONSULT_DISAPPROVE_REJECT_SUPPORT', 2),
 ('AID_ASSAULT_DISAPPROVE_PROTEST', 2),
 ('ASSAULT_CONSULT_RETREAT_SUPPORT', 2),
 ('ASSAULT_MOBILIZE_PROTEST', 2),
 ('AGREE_ASSAULT_COERCE_DISAPPROVE_PROTEST', 2),
 ('AGREE_AID_DISAPPROVE_THREATHEN', 2),
 ('COERCE_CONCEDE_CONSULT_DISAPPROVE', 2),
 ('ASSAULT_REJECT_THREATHEN', 2),
 ('AGREE_DEMAND_SUPPORT', 2),
 ('AID_COERCE_CONCEDE_DISAPPROVE', 2),
 ('AGREE_AID_CONSULT_COOPERATE', 2),
 ('AGREE_ASSAULT_DISAPPROVE_SUPPORT', 2),
 ('COERCE_DISAPPROVE_PROTEST_REJECT', 2),
 ('ASSAULT_DISAPPROVE_REJECT_THREATHEN', 2),
 ('CONSULT_REJECT_SANCTION_SUPPORT', 2),
 ('COERCE_PROTEST_SANCTION', 2),
 ('AGREE_DISAPPROVE_PROTEST', 2),
 ('AID_CONSULT_SANCTION', 2),
 ('ASSAULT_PROTEST_THREATHEN', 2),
 ('PROTEST_SUPPORT_THREATHEN', 2),
 ('COOPERATE_REJECT_SUPPORT', 2),
 ('AID_ASSAULT_DISAPPROVE_SUPPORT', 2),
 ('DEMAND_DISAPPROVE_REJECT', 2),
 ('COERCE_CONCEDE_COOPERATE', 2),
 ('AID_DEMAND_REJECT', 2),
 ('AGREE_ASSAULT_COERCE_CONSULT_DISAPPROVE', 2),
 ('REJECT_SANCTION_SUPPORT', 2),
 ('AID_ASSAULT_CONSULT_REJECT', 2),
 ('AID_ASSAULT_DEMAND', 2),
 ('REJECT_RETREAT_SUPPORT', 2),
 ('ASSAULT_CONSULT_SUPPORT_THREATHEN', 2),
 ('DEMAND_RETREAT_SUPPORT', 2),
 ('AGREE_ASSAULT_REJECT', 2),
 ('AGREE_CONSULT_DISAPPROVE_RETREAT_SUPPORT', 2),
 ('ASSAULT_COERCE_MOBILIZE', 2),
 ('AGREE_AID_CONSULT_DISAPPROVE_MOBILIZE_PROTEST_SANCTION', 2),
 ('DISAPPROVE_MOBILIZE_THREATHEN', 2),
 ('AID_MOBILIZE_PROTEST', 2),
 ('PROTEST_REJECT_SUPPORT', 2),
 ('ASSAULT_COERCE_REJECT_THREATHEN', 2),
 ('COERCE_DISAPPROVE_MOBILIZE_REJECT', 2),
 ('AGREE_AID_THREATHEN', 2),
 ('ASSAULT_COOPERATE_RETREAT', 2),
 ('CONSULT_DISAPPROVE_PROTEST_SUPPORT', 2),
 ('AGREE_CONSULT_DEMAND_SUPPORT', 2),
 ('DISAPPROVE_RETREAT_THREATHEN', 2),
 ('AID_COERCE_DISAPPROVE_REJECT', 2),
 ('ASSAULT_DEMAND_DISAPPROVE_RETREAT', 2),
 ('COERCE_DEMAND_SUPPORT', 2),
 ('AGREE_ASSAULT_CONSULT_COOPERATE', 2),
 ('COERCE_REJECT_SANCTION', 2),
 ('AGREE_COERCE_DISAPPROVE_REJECT', 2),
 ('COERCE_RETREAT_SANCTION', 2),
 ('AGREE_COOPERATE_DISAPPROVE_SUPPORT', 2),
 ('AID_REJECT_SANCTION', 2),
 ('AGREE_AID_COERCE_DISAPPROVE_SANCTION_SUPPORT', 2),
 ('ASSAULT_CONSULT_DISAPPROVE_RETREAT', 2),
 ('AID_CONSULT_DISAPPROVE_RETREAT', 2),
 ('COERCE_CONSULT_DISAPPROVE_REJECT', 2),
 ('MOBILIZE_REJECT', 2),
 ('AGREE_AID_CONCEDE_CONSULT_SUPPORT', 2),
 ('COERCE_DISAPPROVE_SUPPORT_THREATHEN', 2),
 ('AGREE_CONCEDE_COOPERATE_DEMAND_DISAPPROVE_SUPPORT', 2),
 ('AGREE_CONSULT_DISAPPROVE_THREATHEN', 2),
 ('ASSAULT_COERCE_CONSULT_DEMAND', 2),
 ('AID_COERCE_CONSULT_SUPPORT', 2),
 ('ASSAULT_CONSULT_DEMAND_DISAPPROVE', 2),
 ('ASSAULT_CONCEDE_DEMAND_DISAPPROVE', 2),
 ('AGREE_COERCE_RETREAT', 2),
 ('CONSULT_SANCTION_THREATHEN', 1),
 ('AGREE_AID_ASSAULT_CONSULT_DEMAND_DISAPPROVE_RETREAT_SUPPORT', 1),
 ('AGREE_AID_ASSAULT_COERCE_CONCEDE_CONSULT_COOPERATE_DISAPPROVE_PROTEST_REJECT_RETREAT_SUPPORT_THREATHEN',
  1),
 ('AGREE_AID_ASSAULT_CONSULT_RETREAT', 1),
 ('CONSULT_DEMAND_SUPPORT_THREATHEN', 1),
 ('AGREE_AID_ASSAULT_COERCE_CONCEDE_CONSULT_DISAPPROVE_REJECT_RETREAT_SANCTION_SUPPORT',
  1),
 ('AGREE_AID_ASSAULT_COERCE_CONCEDE_CONSULT_DEMAND_DISAPPROVE_RETREAT_SUPPORT_THREATHEN',
  1),
 ('AID_COOPERATE_MOBILIZE', 1),
 ('AGREE_AID_ASSAULT_COERCE_CONCEDE_CONSULT_COOPERATE_DEMAND_DISAPPROVE_PROTEST_REJECT_RETREAT_SANCTION_SUPPORT_THREATHEN',
  1),
 ('AID_COOPERATE_SANCTION_SUPPORT', 1),
 ('AGREE_CONSULT_COOPERATE_MOBILIZE', 1),
 ('AGREE_AID_ASSAULT_COERCE_CONCEDE_CONSULT_COOPERATE_DEMAND_DISAPPROVE_MOBILIZE_PROTEST_REJECT_RETREAT_SANCTION_SUPPORT_THREATHEN',
  1),
 ('AGREE_COOPERATE_DEMAND', 1),
 ('AGREE_AID_COERCE_CONSULT_DISAPPROVE', 1),
 ('COOPERATE_MOBILIZE_SANCTION', 1),
 ('AID_ASSAULT_DISAPPROVE_SUPPORT_THREATHEN', 1),
 ('AID_ASSAULT_COERCE_CONSULT_COOPERATE_DEMAND_DISAPPROVE_REJECT_RETREAT_SANCTION_SUPPORT',
  1),
 ('AGREE_PROTEST_SANCTION', 1),
 ('AGREE_CONCEDE_DEMAND', 1),
 ('AID_COERCE_SANCTION', 1),
 ('AID_COERCE_CONSULT_PROTEST', 1),
 ('AGREE_ASSAULT_COERCE_DISAPPROVE_THREATHEN', 1),
 ('AID_ASSAULT_COERCE_DISAPPROVE_THREATHEN', 1),
 ('AGREE_COERCE_SUPPORT_THREATHEN', 1),
 ('COERCE_DEMAND_PROTEST', 1),
 ('AGREE_RETREAT_SUPPORT', 1),
 ('AID_DISAPPROVE_SANCTION_THREATHEN', 1),
 ('COERCE_DEMAND_SANCTION_THREATHEN', 1),
 ('ASSAULT_COERCE_CONSULT_DISAPPROVE_RETREAT', 1),
 ('AID_ASSAULT_CONCEDE_REJECT_SUPPORT', 1),
 ('AGREE_ASSAULT_SANCTION', 1),
 ('COERCE_DISAPPROVE_REJECT_THREATHEN', 1),
 ('ASSAULT_COERCE_CONCEDE_CONSULT_SUPPORT_THREATHEN', 1),
 ('AID_ASSAULT_COOPERATE_RETREAT', 1),
 ('AID_ASSAULT_CONSULT_COOPERATE_SUPPORT', 1),
 ('AGREE_COOPERATE_DISAPPROVE_THREATHEN', 1),
 ('AID_CONCEDE_CONSULT_SUPPORT', 1),
 ('ASSAULT_COERCE_CONCEDE_CONSULT_DISAPPROVE', 1),
 ('AID_COOPERATE_SUPPORT_THREATHEN', 1),
 ('AGREE_AID_ASSAULT_CONSULT_DEMAND', 1),
 ('COERCE_COOPERATE_DISAPPROVE_MOBILIZE', 1),
 ('AGREE_AID_COERCE_SUPPORT', 1),
 ('AGREE_AID_CONSULT_REJECT_SUPPORT', 1),
 ('AGREE_ASSAULT_COERCE_CONSULT_COOPERATE_DISAPPROVE_SANCTION_SUPPORT_THREATHEN',
  1),
 ('AID_DISAPPROVE_PROTEST_SANCTION_THREATHEN', 1),
 ('AGREE_CONSULT_COOPERATE_DISAPPROVE_REJECT_THREATHEN', 1),
 ('AGREE_AID_ASSAULT_COERCE_DEMAND_DISAPPROVE', 1),
 ('AGREE_COOPERATE_DISAPPROVE_RETREAT', 1),
 ('AGREE_AID_CONSULT_THREATHEN', 1),
 ('CONSULT_COOPERATE_RETREAT_THREATHEN', 1),
 ('AGREE_AID_REJECT', 1),
 ('AGREE_COERCE_CONSULT_COOPERATE_DISAPPROVE_RETREAT_SUPPORT', 1),
 ('AID_ASSAULT_CONSULT_DISAPPROVE_REJECT_SANCTION', 1),

In [26]:
len(count_cat_labels)

1063